import FVSquad.ElectionBroadcastChain
import FVSquad.MultiStepReachability

/-!
# BroadcastLifecycle — Connecting BroadcastSeq to RaftReachable

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

This file provides the **lifecycle integration** theorems that connect the
`BroadcastSeq` model (from `ElectionBroadcastChain.lean`) to the `RaftReachable`
inductive predicate (from `RaftTrace.lean` via `MultiStepReachability.lean`).

## The Gap Being Closed

`ElectionBroadcastChain.lean` (EBC6) proves that given a `BroadcastSeq` covering all
voters, the `hqc_preserved` condition of `RaftReachable.step` can be discharged from
concrete election conditions — rather than being an abstract hypothesis.

`MultiStepReachability.lean` (MS1) proves that a `ValidAEList` starting from a
`RaftReachable` state produces a `RaftReachable` end state.

The missing link: a `BroadcastSeq` is not directly a `ValidAEList`. This file proves:

1. **BL1** (`broadcastSeq_to_validAEList`): convert a `BroadcastSeq` into a `ValidAEList`.

2. **BL2** (`raftReachable_after_broadcast`): a `BroadcastSeq` from a `RaftReachable`
   state produces a `RaftReachable` end state.

3. **BL3** (`raftReachable_from_init_broadcast`): a `BroadcastSeq` from the
   `initialCluster` produces a `RaftReachable` state.

Together, these theorems complete the `ElectionBroadcastChain → RaftReachable`
lifecycle connection:

```
initialCluster (init)                    ← RaftReachable.init
    ↓  BroadcastSeq (BL3 / BL1 + MS3)
cs_bc                                    ← RaftReachable (BL2 / BL3)
    ↓  broadcastSeq_hqc_preserved (EBC6) → hqc_preserved derived
    ↓  ValidAEStep (with concrete hqc_preserved)
cs_next                                  ← RaftReachable (validAEStep_raftReachable, CPS2)
```

## Theorem Index

| ID  | Name                               | Description                                                  |
|-----|------------------------------------|--------------------------------------------------------------|
| BL1 | `broadcastSeq_to_validAEList`      | Convert BroadcastSeq → ValidAEList                           |
| BL2 | `raftReachable_after_broadcast`    | BroadcastSeq from RaftReachable start → RaftReachable end    |
| BL3 | `raftReachable_from_init_broadcast`| BroadcastSeq from initialCluster → RaftReachable             |

**Sorry count**: 0.  All theorems proved without `sorry`.

🔬 Generated by Lean Squad automated formal verification (Run 112).
-/

open FVSquad.RaftSafety
open FVSquad.ConcreteTransitions
open FVSquad.ConcreteProtocolStep
open FVSquad.RaftTrace
open FVSquad.MultiStepReachability
open FVSquad.ElectionBroadcastChain

namespace FVSquad.BroadcastLifecycle

/-! ## BL1: Convert BroadcastSeq to ValidAEList -/

/-- **BL1** — Every `BroadcastSeq` can be viewed as a `ValidAEList`.

    A `BroadcastSeq` is a chain of `ValidAEStep` transitions (one per voter).
    A `ValidAEList` is also a chain of `ValidAEStep` transitions.  The difference
    is that `BroadcastSeq` carries additional bookkeeping (voter index function,
    prevLogIndex = 0, leader identity).  Forgetting this extra structure yields a
    `ValidAEList`.

    **Proof**: structural induction on `BroadcastSeq`.
    - `nil`: `ValidAEList.nil cs`.
    - `cons hstep _ tail`: `ValidAEList.cons hstep (BL1 tail)`. -/
theorem broadcastSeq_to_validAEList (E : Type) [DecidableEq E]
    (lead : Nat) (voterIdx : Nat → Nat) (vs : List Nat)
    (cs_init cs_final : ClusterState E)
    (hseq : BroadcastSeq E lead voterIdx vs cs_init cs_final) :
    ValidAEList E cs_init cs_final := by
  induction hseq with
  | nil cs => exact ValidAEList.nil cs
  | cons hstep _ _ _ _ _ ih =>
    exact ValidAEList.cons hstep ih

/-! ## BL2: BroadcastSeq from RaftReachable start → RaftReachable end -/

/-- **BL2** — If `cs_init` is `RaftReachable`, then the final state of any
    `BroadcastSeq` from `cs_init` is also `RaftReachable`.

    **Proof**: BL1 converts `BroadcastSeq` to `ValidAEList`; MS1
    (`listStep_raftReachable`) then gives the result. -/
theorem raftReachable_after_broadcast (E : Type) [DecidableEq E]
    (lead : Nat) (voterIdx : Nat → Nat) (vs : List Nat)
    (cs_init cs_final : ClusterState E)
    (hreach : RaftReachable cs_init)
    (hseq : BroadcastSeq E lead voterIdx vs cs_init cs_final) :
    RaftReachable cs_final :=
  listStep_raftReachable hreach (broadcastSeq_to_validAEList E lead voterIdx vs cs_init cs_final hseq)

/-! ## BL3: BroadcastSeq from initialCluster → RaftReachable -/

/-- **BL3** — A `BroadcastSeq` from the `initialCluster` produces a `RaftReachable` state.

    **Proof**: `RaftReachable.init` gives the base case; BL2 finishes.

    **Significance**: this is the simplest concrete way to produce a `RaftReachable`
    state: start from `initialCluster`, broadcast AppendEntries to all voters.
    The resulting state is formally verified to be safe (by `raftReachable_safe`, RT2). -/
theorem raftReachable_from_init_broadcast (E : Type) [DecidableEq E]
    (lead : Nat) (voterIdx : Nat → Nat) (voters : List Nat)
    (cs_final : ClusterState E)
    (hseq : BroadcastSeq E lead voterIdx voters (initialCluster voters) cs_final) :
    RaftReachable cs_final :=
  raftReachable_after_broadcast E lead voterIdx voters _ cs_final
    (RaftReachable.init voters) hseq

/-! ## Correspondence examples -/

-- BL1: The identity broadcast (nil) converts to ValidAEList.nil
example (E : Type) [DecidableEq E] (lead : Nat) (vi : Nat → Nat) (cs : ClusterState E) :
    ValidAEList E cs cs :=
  broadcastSeq_to_validAEList E lead vi [] cs cs (BroadcastSeq.nil cs)

-- BL2: The identity broadcast preserves RaftReachable
example (E : Type) [DecidableEq E] (lead : Nat) (vi : Nat → Nat) (cs : ClusterState E)
    (h : RaftReachable cs) :
    RaftReachable cs :=
  raftReachable_after_broadcast E lead vi [] cs cs h (BroadcastSeq.nil cs)

end FVSquad.BroadcastLifecycle
