import FVSquad.AEBroadcastInvariant
import FVSquad.ElectionConcreteModel
import FVSquad.LeaderCompleteness

/-!
# ElectionBroadcastChain — Inductive Broadcast Sequence for `hqc_preserved`

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

This file formalises the **broadcast induction chain**: a finite sequence of valid
AppendEntries steps (one per voter) establishes `HaeCovered` for all voters, which in
turn discharges the `hqc_preserved` hypothesis of `RaftReachable.step`.

## The Gap This File Closes

`AEBroadcastInvariant.lean` (ABI3/ABI6/ABI8) shows that each individual AE step
extends the covered voter set and provides the schema for the full broadcast.  However,
ABI5 (`haeCovered_induction`) is a placeholder returning `True` — it does not connect
a concrete sequence of intermediate cluster states.

This file defines the `BroadcastSeq` inductive type, threading intermediate states
through the sequence, and proves the key theorems:

```
ValidAEStep × n
   → BroadcastSeq voters cs_init cs_final
   → HaeCovered voters cs_final.logs lead voterIdx    (EBC4)
   → hqc_preserved (for subsequent step)              (EBC5)
```

This closes **B3** from `formal-verification/CRITIQUE.md`:
> *Connect broadcast model to full Raft election lifecycle.*

## Theorem Index

| ID   | Name                               | Description                                           |
|------|------------------------------------|-------------------------------------------------------|
| EBC1 | `broadcastSeq_log_other`           | Non-broadcast voter's log is unchanged                |
| EBC2 | `broadcastSeq_lead_log`            | Leader's log is unchanged through the broadcast       |
| EBC3 | `broadcastSeq_haeCovered_voter`    | After step + tail, head voter still has agreement     |
| EBC4 | `broadcastSeq_haeCovered`          | Full broadcast → `HaeCovered voters`                  |
| EBC5 | `haeCovered_to_hae_all`            | Extend `HaeCovered` to universal `hae` via non-voters |
| EBC6 | `broadcastSeq_hqc_preserved`       | Full chain: Broadcast + election → `hqc_preserved`    |

🔬 Generated by Lean Squad automated formal verification (Run 90).
-/

open FVSquad.RaftSafety
open FVSquad.ConcreteTransitions
open FVSquad.ConcreteProtocolStep
open FVSquad.RaftElection
open FVSquad.LeaderCompleteness
open FVSquad.ElectionConcreteModel
open FVSquad.AEBroadcastInvariant

namespace FVSquad.ElectionBroadcastChain

/-! ## BroadcastSeq: sequence of AE steps, one per voter -/

/-- `BroadcastSeq lead voterIdx vs cs_init cs_final` represents a sequence of valid
    AppendEntries steps — one per voter in `vs` — threading from cluster state
    `cs_init` to `cs_final`.  Each step uses `prevLogIndex = 0`.

    The `hv_out` field (`v ∉ vs`) ensures each voter appears at most once in the
    remaining tail, preventing double-coverage complications. -/
inductive BroadcastSeq (E : Type) [DecidableEq E] (lead : Nat) (voterIdx : Nat → Nat) :
    List Nat → ClusterState E → ClusterState E → Prop where
  /-- Base: empty broadcast, state unchanged. -/
  | nil (cs : ClusterState E) : BroadcastSeq E lead voterIdx [] cs cs
  /-- Step: one AE step for voter `v`, followed by the broadcast to remaining voters. -/
  | cons {vs : List Nat} {cs cs' cs'' : ClusterState E} {v : Nat} {msg : AppendEntriesMsg E}
      (hstep    : ValidAEStep E cs lead v msg cs')
      (hprev0   : msg.prevLogIndex = 0)
      (hlead_ne : lead ≠ v)
      (hbound   : 1 ≤ voterIdx v)
      (hv_out   : v ∉ vs)
      (htail    : BroadcastSeq E lead voterIdx vs cs' cs'') :
      BroadcastSeq E lead voterIdx (v :: vs) cs cs''

/-! ## EBC1: Non-broadcast voter's log is unchanged -/

/-- **EBC1** — The log function of any voter `w ∉ vs` is preserved pointwise through a
    broadcast sequence targeting voters in `vs`.

    **Proof**: induction on `BroadcastSeq`.
    - Base: `cs_final = cs_init`.
    - Step (`cons`): `w ≠ v` and `w ∉ vs₀`.
      `hstep.hlogs'_other w (· ≠ v)` gives `cs'.logs w = cs.logs w`;
      the IH on the tail gives `cs''.logs w = cs'.logs w`;
      transitivity completes the chain.

    **Significance**: voter `v`'s agreement established in step `k` is not destroyed by
    steps `k+1, …, n` targeting other voters.  Used in EBC3. -/
theorem broadcastSeq_log_other (E : Type) [DecidableEq E]
    (lead : Nat) (voterIdx : Nat → Nat) (vs : List Nat)
    (cs_init cs_final : ClusterState E)
    (hseq : BroadcastSeq E lead voterIdx vs cs_init cs_final)
    (w : Nat) (hw : w ∉ vs) :
    cs_final.logs w = cs_init.logs w := by
  induction hseq with
  | nil => rfl
  | cons hstep _ _ _ _ htail ih =>
    simp only [List.mem_cons, not_or] at hw
    exact (ih hw.2).trans (hstep.hlogs'_other w hw.1)

/-! ## EBC2: Leader's log is unchanged through the broadcast -/

/-- **EBC2** — The leader's log function is unchanged by a broadcast sequence that
    does not include the leader among the targeted voters (`lead ∉ vs`).

    **Proof**: direct application of EBC1 with `w = lead`. -/
theorem broadcastSeq_lead_log (E : Type) [DecidableEq E]
    (lead : Nat) (voterIdx : Nat → Nat) (vs : List Nat)
    (cs_init cs_final : ClusterState E)
    (hseq : BroadcastSeq E lead voterIdx vs cs_init cs_final)
    (hlead_not_in : lead ∉ vs) :
    cs_final.logs lead = cs_init.logs lead :=
  broadcastSeq_log_other E lead voterIdx vs cs_init cs_final hseq lead hlead_not_in

/-! ## EBC3: Head voter still has agreement in the final state -/

/-- **EBC3** — After a `cons` step (establishing agreement for voter `v` in state `cs'`)
    followed by a tail broadcast (producing `cs''`), voter `v` still has agreement
    at the final state `cs''`.

    **Chain**: `cs''.logs v k = cs'.logs v k = cs'.logs lead k = cs''.logs lead k`
    - First equality: `v ∉ vs₀` → EBC1 on the tail
    - Middle equality: ABI1b (`hae_for_voter_of_validAEStep`) on the single step `cs → cs'`
    - Third equality: EBC2 on the tail (leader's log unchanged) -/
theorem broadcastSeq_haeCovered_voter (E : Type) [DecidableEq E]
    (lead : Nat) (voterIdx : Nat → Nat) (vs : List Nat)
    (cs cs' cs'' : ClusterState E)
    (v : Nat) (msg : AppendEntriesMsg E)
    (hstep    : ValidAEStep E cs lead v msg cs')
    (hprev0   : msg.prevLogIndex = 0)
    (hlead_ne : lead ≠ v)
    (hbound   : 1 ≤ voterIdx v)
    (hv_out   : v ∉ vs)
    (hlead_out : lead ∉ vs)
    (htail    : BroadcastSeq E lead voterIdx vs cs' cs'')
    (k : Nat) (hk : k ≤ voterIdx v) :
    cs''.logs v k = cs''.logs lead k := by
  -- cs''.logs v = cs'.logs v  (EBC1: v ∉ vs, tail does not touch v)
  have hv_eq : cs''.logs v = cs'.logs v :=
    broadcastSeq_log_other E lead voterIdx vs cs' cs'' htail v hv_out
  -- cs''.logs lead = cs'.logs lead  (EBC2: lead ∉ vs, tail does not touch lead)
  have hl_eq : cs''.logs lead = cs'.logs lead :=
    broadcastSeq_lead_log E lead voterIdx vs cs' cs'' htail hlead_out
  -- cs'.logs v k = cs'.logs lead k  (ABI1b: AE step with prevLogIndex=0)
  have hae : cs'.logs v k = cs'.logs lead k :=
    hae_for_voter_of_validAEStep E hstep hprev0 hlead_ne voterIdx hbound k hk
  -- Combine the three equalities
  rw [congrFun hv_eq k, congrFun hl_eq k, hae]

/-! ## EBC4: Full broadcast → HaeCovered for all voters -/

/-- **EBC4** — After a `BroadcastSeq` covering all voters in `vs`, the `HaeCovered`
    predicate holds for every voter in `vs` at the final state.

    **Proof**: induction on `BroadcastSeq`.
    - Base (`nil`): vacuously true.
    - Step (`cons`):
      - EBC3 gives agreement for voter `v` in the final state.
      - The IH gives `HaeCovered E vs₀ cs''.logs lead voterIdx` for tail voters.
      - Combining with EBC3 gives `HaeCovered E (v :: vs₀) cs''.logs lead voterIdx`.

    **Significance**: this is the key new result of this file — a proper inductive proof
    that replaces the `True`-returning placeholder `haeCovered_induction` (ABI5). -/
theorem broadcastSeq_haeCovered (E : Type) [DecidableEq E]
    (lead : Nat) (voterIdx : Nat → Nat) (vs : List Nat)
    (cs_init cs_final : ClusterState E)
    (hseq : BroadcastSeq E lead voterIdx vs cs_init cs_final)
    (hlead_not_in : lead ∉ vs) :
    HaeCovered E vs cs_final.logs lead voterIdx := by
  induction hseq with
  | nil =>
    intro w hw; simp at hw
  | cons hstep hprev0 hlead_ne hbound hv_out htail ih =>
    simp only [List.mem_cons, not_or] at hlead_not_in
    have ih_res := ih hlead_not_in.2
    intro w hw_mem k hk
    rcases List.mem_cons.mp hw_mem with rfl | hw_in
    · -- w = v: agreement preserved through the tail broadcast sequence
      exact broadcastSeq_haeCovered_voter E lead voterIdx _ _ _ _ _ _
              hstep hprev0 hlead_ne hbound hv_out hlead_not_in.2 htail k hk
    · -- w ∈ vs₀: inductive hypothesis
      exact ih_res w hw_in k hk

/-! ## EBC5: Extend HaeCovered to universal hae -/

/-- **EBC5** — Convert `HaeCovered (hd :: tl)` to a universal `hae` hypothesis.

    The `hqc_preserved_of_hae` (ECM4) requires `∀ w k, k ≤ voterLog w → logs w k = lead k`
    for ALL `w`, not just those in the voter list.  For voters outside the list, we
    accept an explicit hypothesis `hnv_hae` (typically, non-voters have empty logs).

    **Usage**: combine EBC4 result with `hnv_hae : ∀ w ∉ voters, hae w` to get universal hae.
    In the typical Raft setup, non-voter nodes have empty logs, so `hae` for them holds
    trivially at index 0. -/
theorem haeCovered_to_hae_all (E : Type)
    (hd : Nat) (tl : List Nat)
    (logs : VoterLogs E) (lead : Nat)
    (voterLog : Nat → LogId)
    (hcov : HaeCovered E (hd :: tl) logs lead (fun w => (voterLog w).index))
    (hnv_hae : ∀ w, w ∉ (hd :: tl) →
                    ∀ k, k ≤ (voterLog w).index → logs w k = logs lead k) :
    ∀ w k, k ≤ (voterLog w).index → logs w k = logs lead k := by
  intro w k hk
  by_cases hw : w ∈ (hd :: tl)
  · exact hcov w hw k hk
  · exact hnv_hae w hw k hk

/-! ## EBC6: Full chain — Broadcast + election → hqc_preserved -/

/-- **EBC6** — Complete bridge theorem: a `BroadcastSeq` from an election state, combined
    with the election conditions, discharges `hqc_preserved` for any subsequent AE step.

    **Chain**:
    1. EBC4: `BroadcastSeq voters cs_bc cs_post` → `HaeCovered voters cs_post.logs lead voterIdx`
    2. EBC5: `HaeCovered voters` + `hnv_hae` → universal `hae`
    3. ECM4 (`hqc_preserved_of_hae`): universal `hae` + election `hwin` + `hstep`
       → `∀ k e, isQuorumCommitted cs_post.voters cs_post.logs k e →`
          `      isQuorumCommitted cs_next.voters cs_next.logs k e`

    **Hypotheses** (beyond the broadcast sequence):
    - `hwin`: the leader won the election in `term` under the vote `record`
    - `hnv_hae`: for voters `w ∉ (hd :: tl)`, their logs agree with the leader's
      (typically vacuous if only `hd :: tl` are cluster members)
    - `hlog_none`, `hcand_mono`, `hconsist`, `hvoter_idx`: standard well-formedness

    **Significance**: this is the main export of the file, closing the B3 gap.
    The `hqc_preserved` hypothesis of `RaftReachable.step` is no longer abstract —
    it is proved from a concrete election + AE broadcast sequence. -/
theorem broadcastSeq_hqc_preserved [DecidableEq E]
    (lead : Nat) (voterLog : Nat → LogId)
    (hd : Nat) (tl : List Nat)
    (cs_bc cs_post : ClusterState E)
    (hseq : BroadcastSeq E lead (fun w => (voterLog w).index) (hd :: tl)
              cs_bc cs_post)
    (hlead_not_in : lead ∉ (hd :: tl))
    {cs_next : ClusterState E} {v_next : Nat} {msg_next : AppendEntriesMsg E}
    (hstep : ValidAEStep E cs_post lead v_next msg_next cs_next)
    (hvoters : cs_post.voters = hd :: tl)
    (record : VoteRecord) (term : Nat)
    (candLastTerm candLastIndex : Nat → Nat)
    (hwin      : wonInTerm (hd :: tl) record term lead = true)
    (hnv_hae   : ∀ w, w ∉ (hd :: tl) →
                     ∀ k, k ≤ (voterLog w).index →
                     cs_post.logs w k = cs_post.logs lead k)
    (hlog_none : ∀ w k, k > (voterLog w).index → cs_post.logs w k = none)
    (hcand_mono : ∀ j k, j ≤ k → cs_post.logs lead k = none →
                          cs_post.logs lead j = none)
    (hconsist  : VoteRecordConsistency record voterLog candLastTerm candLastIndex)
    (hvoter_idx : ∀ w k e, w ∈ (hd :: tl) → cs_post.logs w k = some e →
                             k ≤ (voterLog w).index) :
    ∀ k e, isQuorumCommitted cs_post.voters cs_post.logs k e →
           isQuorumCommitted cs_next.voters cs_next.logs k e :=
  -- Step 1: EBC4 gives HaeCovered (hd :: tl) at cs_post
  let hcov := broadcastSeq_haeCovered E lead (fun w => (voterLog w).index) (hd :: tl)
                cs_bc cs_post hseq hlead_not_in
  -- Step 2: EBC5 extends to universal hae
  let hae_all := haeCovered_to_hae_all E hd tl cs_post.logs lead voterLog hcov hnv_hae
  -- Step 3: ECM4 discharges hqc_preserved
  hqc_preserved_of_hae hstep hd tl hvoters record term voterLog candLastTerm candLastIndex
    hwin hae_all hlog_none hcand_mono hconsist hvoter_idx

end FVSquad.ElectionBroadcastChain
