/-!
# HasNextEntries — Model and Proofs for `applied_index_upper_bound` / `has_next_entries_since`

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

This file provides a formal model of `RaftLog::applied_index_upper_bound` and
`RaftLog::has_next_entries_since` (`src/raft_log.rs:447–491`) and proves their key
correctness properties.

## Background

`applied_index_upper_bound` computes the ceiling on which log entries may be applied:

```rust
fn applied_index_upper_bound(&self) -> u64 {
    std::cmp::min(
        self.committed,
        self.persisted + self.max_apply_unpersisted_log_limit,
    )
}
```

Normally equals `committed`.  When `max_apply_unpersisted_log_limit > 0`, allows applying
entries up to `persisted + limit` ahead of full persistence.

`has_next_entries_since(since_idx)`:

```rust
pub fn has_next_entries_since(&self, since_idx: u64) -> bool {
    let offset = cmp::max(since_idx + 1, self.first_index());
    let high = self.applied_index_upper_bound() + 1;
    high > offset
}
```

Returns `true` iff there is at least one index in `[offset, upper_bound]` that has not
been consumed since `since_idx`.

## Theorem Index

| ID    | Name                                           | Description                                                          |
|-------|------------------------------------------------|----------------------------------------------------------------------|
| HNE1  | `upperBound_le_committed`                      | Upper bound ≤ committed                                              |
| HNE2  | `upperBound_le_persisted_plus`                 | Upper bound ≤ persisted + limit                                      |
| HNE3  | `upperBound_eq_committed_when_persisted_large` | If persisted + limit ≥ committed → upper bound = committed           |
| HNE4  | `upperBound_eq_persisted_plus_when_small`      | If persisted + limit < committed → upper bound = persisted + limit   |
| HNE5  | `upperBound_mono_committed`                    | Upper bound is monotone in committed                                 |
| HNE6  | `upperBound_mono_persisted`                    | Upper bound is monotone in persisted                                 |
| HNE7  | `upperBound_mono_limit`                        | Upper bound is monotone in limit                                     |
| HNE8  | `upperBound_zero_limit_eq_min`                 | With limit = 0, upper bound = min(committed, persisted)              |
| HNE9  | `hasNextEntriesSince_true_iff`                 | Biconditional: returns true ↔ offset ≤ upperBound                    |
| HNE10 | `hasNextEntriesSince_false_of_ge_bound`        | since_idx ≥ upperBound → returns false                               |
| HNE11 | `hasNextEntriesSince_anti_mono_since`          | Anti-monotone in since_idx                                           |
| HNE12 | `hasNextEntriesSince_mono_committed`           | Monotone in committed                                                |
| HNE13 | `hasNextEntriesSince_mono_persisted`           | Monotone in persisted                                                |
| HNE14 | `hasNextEntries_eq_since_applied`              | hasNextEntries = hasNextEntriesSince applied                         |

**Sorry count**: 0.  All theorems proved without `sorry`.

🔬 Generated by Lean Squad automated formal verification (Run 111).
-/

namespace FVSquad.HasNextEntries

/-! ## Core definitions -/

/-- Model of `RaftLog::applied_index_upper_bound`:
    `min(committed, persisted + max_apply_unpersisted_log_limit)`. -/
def appliedIndexUpperBound (committed persisted limit : Nat) : Nat :=
  min committed (persisted + limit)

/-- Model of `RaftLog::has_next_entries_since`.
    `firstIndex` corresponds to `self.first_index()`.
    Returns true iff there is at least one apply-ready entry since `sinceIdx`. -/
def hasNextEntriesSince (firstIndex committed persisted limit sinceIdx : Nat) : Bool :=
  let offset := max (sinceIdx + 1) firstIndex
  let high   := appliedIndexUpperBound committed persisted limit
  high + 1 > offset

/-- Model of `RaftLog::has_next_entries` (calls `has_next_entries_since(self.applied)`). -/
def hasNextEntries (firstIndex committed persisted limit applied : Nat) : Bool :=
  hasNextEntriesSince firstIndex committed persisted limit applied

/-! ## HNE1–HNE8: Properties of `appliedIndexUpperBound` -/

/-- **HNE1** — Upper bound never exceeds `committed`. -/
theorem HNE1_upperBound_le_committed (committed persisted limit : Nat) :
    appliedIndexUpperBound committed persisted limit ≤ committed := by
  simp [appliedIndexUpperBound, Nat.min_le_left]

/-- **HNE2** — Upper bound never exceeds `persisted + limit`. -/
theorem HNE2_upperBound_le_persisted_plus (committed persisted limit : Nat) :
    appliedIndexUpperBound committed persisted limit ≤ persisted + limit := by
  simp [appliedIndexUpperBound, Nat.min_le_right]

/-- **HNE3** — When `persisted + limit ≥ committed`, the upper bound equals `committed`. -/
theorem HNE3_upperBound_eq_committed_when_persisted_large
    (committed persisted limit : Nat)
    (h : persisted + limit ≥ committed) :
    appliedIndexUpperBound committed persisted limit = committed := by
  simp [appliedIndexUpperBound, Nat.min_def]; omega

/-- **HNE4** — When `persisted + limit < committed`, the upper bound equals `persisted + limit`. -/
theorem HNE4_upperBound_eq_persisted_plus_when_small
    (committed persisted limit : Nat)
    (h : persisted + limit < committed) :
    appliedIndexUpperBound committed persisted limit = persisted + limit := by
  simp [appliedIndexUpperBound, Nat.min_def]; omega

/-- **HNE5** — Upper bound is monotone in `committed`. -/
theorem HNE5_upperBound_mono_committed
    (c1 c2 persisted limit : Nat) (hle : c1 ≤ c2) :
    appliedIndexUpperBound c1 persisted limit ≤ appliedIndexUpperBound c2 persisted limit := by
  simp only [appliedIndexUpperBound, Nat.min_def]
  split <;> split <;> omega

/-- **HNE6** — Upper bound is monotone in `persisted`. -/
theorem HNE6_upperBound_mono_persisted
    (committed p1 p2 limit : Nat) (hle : p1 ≤ p2) :
    appliedIndexUpperBound committed p1 limit ≤ appliedIndexUpperBound committed p2 limit := by
  simp only [appliedIndexUpperBound, Nat.min_def]
  split <;> split <;> omega

/-- **HNE7** — Upper bound is monotone in `limit`. -/
theorem HNE7_upperBound_mono_limit
    (committed persisted l1 l2 : Nat) (hle : l1 ≤ l2) :
    appliedIndexUpperBound committed persisted l1 ≤ appliedIndexUpperBound committed persisted l2 := by
  simp only [appliedIndexUpperBound, Nat.min_def]
  split <;> split <;> omega

/-- **HNE8** — With `limit = 0`, upper bound equals `min(committed, persisted)`. -/
theorem HNE8_upperBound_zero_limit_eq_min
    (committed persisted : Nat) :
    appliedIndexUpperBound committed persisted 0 = min committed persisted := by
  simp [appliedIndexUpperBound]

/-! ## HNE9–HNE13: Properties of `hasNextEntriesSince` -/

/-- **HNE9** — Biconditional: `hasNextEntriesSince` returns `true` iff
    `max(sinceIdx + 1, firstIndex) ≤ appliedIndexUpperBound`. -/
theorem HNE9_hasNextEntriesSince_true_iff
    (firstIndex committed persisted limit sinceIdx : Nat) :
    hasNextEntriesSince firstIndex committed persisted limit sinceIdx = true ↔
    max (sinceIdx + 1) firstIndex ≤ appliedIndexUpperBound committed persisted limit := by
  simp [hasNextEntriesSince]
  omega

/-- **HNE10** — If `sinceIdx ≥ appliedIndexUpperBound`, returns `false`. -/
theorem HNE10_hasNextEntriesSince_false_of_ge_bound
    (firstIndex committed persisted limit sinceIdx : Nat)
    (h : sinceIdx ≥ appliedIndexUpperBound committed persisted limit) :
    hasNextEntriesSince firstIndex committed persisted limit sinceIdx = false := by
  simp [hasNextEntriesSince, Nat.not_lt]
  omega

/-- **HNE11** — Anti-monotone in `sinceIdx`: smaller `sinceIdx` ⇒ at least as likely to be `true`. -/
theorem HNE11_hasNextEntriesSince_anti_mono_since
    (firstIndex committed persisted limit j k : Nat)
    (hjk : j ≤ k)
    (htrue : hasNextEntriesSince firstIndex committed persisted limit k = true) :
    hasNextEntriesSince firstIndex committed persisted limit j = true := by
  simp [hasNextEntriesSince] at *
  omega

/-- **HNE12** — Monotone in `committed`: if true for `c1`, then true for any `c2 ≥ c1`. -/
theorem HNE12_hasNextEntriesSince_mono_committed
    (firstIndex c1 c2 persisted limit sinceIdx : Nat)
    (hle : c1 ≤ c2)
    (htrue : hasNextEntriesSince firstIndex c1 persisted limit sinceIdx = true) :
    hasNextEntriesSince firstIndex c2 persisted limit sinceIdx = true := by
  simp [hasNextEntriesSince, appliedIndexUpperBound] at *
  omega

/-- **HNE13** — Monotone in `persisted`: if true for `p1`, then true for any `p2 ≥ p1`. -/
theorem HNE13_hasNextEntriesSince_mono_persisted
    (firstIndex committed p1 p2 limit sinceIdx : Nat)
    (hle : p1 ≤ p2)
    (htrue : hasNextEntriesSince firstIndex committed p1 limit sinceIdx = true) :
    hasNextEntriesSince firstIndex committed p2 limit sinceIdx = true := by
  simp [hasNextEntriesSince, appliedIndexUpperBound] at *
  omega

/-! ## HNE14: Connection between `hasNextEntries` and `hasNextEntriesSince` -/

/-- **HNE14** — `hasNextEntries` equals `hasNextEntriesSince applied`. -/
theorem HNE14_hasNextEntries_eq_since_applied
    (firstIndex committed persisted limit applied : Nat) :
    hasNextEntries firstIndex committed persisted limit applied =
    hasNextEntriesSince firstIndex committed persisted limit applied :=
  rfl

/-! ## Correspondence examples (compile-time guards) -/

-- HNE1 example: upper bound ≤ committed
#guard appliedIndexUpperBound 10 8 0 = 8
#guard appliedIndexUpperBound 10 8 5 = 10
#guard appliedIndexUpperBound 10 5 2 = 7

-- HNE3 example: persisted + limit ≥ committed → equals committed
#guard appliedIndexUpperBound 10 8 2 = 10   -- 8+2=10 ≥ 10
#guard appliedIndexUpperBound 10 8 3 = 10   -- 8+3=11 > 10

-- HNE9 examples: hasNextEntriesSince biconditional
#guard hasNextEntriesSince 1 5 5 0 2 = true   -- upper=5, offset=max(3,1)=3 ≤ 5
#guard hasNextEntriesSince 1 5 5 0 5 = false  -- upper=5, offset=max(6,1)=6 > 5
#guard hasNextEntriesSince 1 5 3 0 2 = true   -- upper=3, offset=3 ≤ 3
#guard hasNextEntriesSince 1 5 3 0 3 = false  -- upper=3, offset=4 > 3
#guard hasNextEntriesSince 1 5 3 3 4 = true   -- upper=min(5,6)=5, offset=5 ≤ 5
#guard hasNextEntriesSince 1 0 0 0 0 = false  -- upper=0, offset=max(1,1)=1 > 0

-- HNE12: monotone in committed
-- offset = max(2+1,1)=3, upper = min(3,5)=3, 3+1=4 > 3 → true
#guard hasNextEntriesSince 1 3 5 0 2 = true

end FVSquad.HasNextEntries
