/-!
# IsContinuousEnts — Formal Spec for `is_continuous_ents`

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

This file provides a formal specification and proofs for `is_continuous_ents`
(`src/util.rs`), which checks that a second batch of log entries continues exactly
where the last entry of a prior batch left off.

## Background

`is_continuous_ents(msg, ents)` returns `true` when either slice is empty, or when
`msg.entries.last().index + 1 = ents.first().index`.  It is used to validate that two
partial AppendEntries reply buffers can be safely concatenated.

## Model

We abstract both `Message.entries` and `ents` to `List Nat` (log indices only; terms
and payloads are irrelevant to the predicate).  The Lean function `isContinuousEnts`
mirrors the Rust implementation exactly.

**Abstractions / omissions**:
- Entry terms and data payloads are omitted; only log indices are modelled.
- The Rust function takes a `Message` object; we abstract `msg.entries` to a plain
  list of indices.
- Error paths and the `u64` overflow of `index + 1` are not modelled (we use `Nat`).

Source: `src/util.rs` (`is_continuous_ents`)
🔬 Generated by Lean Squad automated formal verification.
-/

namespace FVSquad.IsContinuousEnts

-- ═══════════════════════════════════════════════════════════
-- Core definition
-- ═══════════════════════════════════════════════════════════

/-- Formal model of `is_continuous_ents`.

    Both `msgEnts` and `ents` are lists of log indices.
    Returns `true` when the slices are trivially continuous (either is empty) or
    when `msgEnts.getLast!` + 1 = `ents.head!`.

    Models `is_continuous_ents` in `src/util.rs`. -/
def isContinuousEnts (msgEnts : List Nat) (ents : List Nat) : Bool :=
  match msgEnts.getLast?, ents.head? with
  | some lastIdx, some firstIdx => lastIdx + 1 == firstIdx
  | _, _ => true

-- ═══════════════════════════════════════════════════════════
-- Theorems
-- ═══════════════════════════════════════════════════════════

/-! ### ICE1 — empty `msgEnts` → always true -/

/-- If `msgEnts` is empty, `isContinuousEnts` returns `true` regardless of `ents`. -/
theorem ICE1_empty_msg_true (ents : List Nat) :
    isContinuousEnts [] ents = true := by
  simp [isContinuousEnts]

/-! ### ICE2 — empty `ents` → always true -/

/-- If `ents` is empty, `isContinuousEnts` returns `true` regardless of `msgEnts`. -/
theorem ICE2_empty_ents_true (msgEnts : List Nat) :
    isContinuousEnts msgEnts [] = true := by
  simp [isContinuousEnts]

/-! ### ICE3 — consecutive single entries → true -/

/-- Two single-element lists with consecutive indices are continuous. -/
theorem ICE3_singleton_consecutive (a b : Nat) (h : a + 1 = b) :
    isContinuousEnts [a] [b] = true := by
  simp [isContinuousEnts, h]

/-! ### ICE4 — gap → false -/

/-- If `lastMsg + 1 < first`, there is a gap: `isContinuousEnts` returns false. -/
theorem ICE4_gap_false (lastMsg first : Nat) (hgap : lastMsg + 1 < first) :
    isContinuousEnts [lastMsg] [first] = false := by
  simp [isContinuousEnts]
  omega

/-! ### ICE5 — overlap → false -/

/-- If `first ≤ lastMsg`, there is an overlap: `isContinuousEnts` returns false
    (provided `first ≠ lastMsg + 1`). -/
theorem ICE5_overlap_false (lastMsg first : Nat) (hov : first ≤ lastMsg) :
    isContinuousEnts [lastMsg] [first] = false := by
  simp [isContinuousEnts]
  omega

/-! ### ICE6 — characterisation: both non-empty, exact continuation -/

/-- When `msgEnts` ends with `m` and `ents` starts with `e`,
    `isContinuousEnts` returns `true` iff `m + 1 = e`. -/
theorem ICE6_characterisation (m e : Nat) (mRest eRest : List Nat) :
    isContinuousEnts (mRest ++ [m]) (e :: eRest) = (m + 1 == e) := by
  simp [isContinuousEnts]

/-! ### ICE7 — only last element of `msgEnts` matters -/

/-- The result depends only on the **last** index of `msgEnts` and the **first** of `ents`. -/
theorem ICE7_only_last_matters (pre : List Nat) (lastMsg : Nat) (ents : List Nat) :
    isContinuousEnts (pre ++ [lastMsg]) ents =
    isContinuousEnts [lastMsg] ents := by
  simp [isContinuousEnts]

/-! ### ICE8 — `isContinuousEnts` of `[a]` and `[a+1]` is true (canonical case) -/

/-- The canonical case: `[a]` followed by `[a+1]` is continuous. -/
theorem ICE8_canonical (a : Nat) :
    isContinuousEnts [a] [a + 1] = true := by
  simp [isContinuousEnts]

end FVSquad.IsContinuousEnts
