/-
  Formal specification and proofs for `RaftLog::is_up_to_date`
  Source: src/raft_log.rs

  This function implements the Raft log comparison rule (§5.4.1 of the Raft paper):
  a candidate's log (term, last_index) is "at least as up-to-date" as a voter's log
  (voter_term, voter_index) iff:
    term > voter_term  ∨  (term = voter_term ∧ last_index ≥ voter_index)

  This is exactly lexicographic order on (term, index) pairs.

  The Rust code:
    pub fn is_up_to_date(&self, last_index: u64, term: u64) -> bool {
        term > self.last_term()
            || (term == self.last_term() && last_index >= self.last_index())
    }

  Model: We abstract `RaftLog` to a pair `LogId := (term : Nat, index : Nat)`.
  - `Nat` instead of `u64` (no overflow; practical log sizes << 2^63)
  - No I/O, storage, or mutable state — pure comparison function

  🔬 Generated by Lean Squad automated formal verification.
  See: formal-verification/specs/is_up_to_date_informal.md
-/

-- ============================================================
-- Type definition: a log identifier (last term, last index)
-- ============================================================

structure LogId where
  term  : Nat
  index : Nat
  deriving Repr, BEq, DecidableEq

-- ============================================================
-- Implementation model
-- ============================================================

/-- `isUpToDate voter cand_term cand_index`: returns true iff the candidate log
    `(cand_term, cand_index)` is at least as up-to-date as the voter log `voter`.

    Directly mirrors the Rust:
      `term > self.last_term() || (term == self.last_term() && last_index >= self.last_index())`
-/
def isUpToDate (voter : LogId) (cand_term cand_index : Nat) : Bool :=
  cand_term > voter.term || (cand_term == voter.term && cand_index >= voter.index)

-- ============================================================
-- Specification: the relation ≥_log as a Prop
-- ============================================================

/-- The log order as a proposition: candidate ≥_log voter. -/
def logGe (voter_term voter_index cand_term cand_index : Nat) : Prop :=
  cand_term > voter_term ∨ (cand_term = voter_term ∧ cand_index ≥ voter_index)

-- ============================================================
-- Correctness of the implementation
-- ============================================================

/-- IU1: The implementation correctly reflects the specification. -/
theorem isUpToDate_iff (voter : LogId) (ct ci : Nat) :
    isUpToDate voter ct ci = true ↔ logGe voter.term voter.index ct ci := by
  simp only [isUpToDate, logGe]
  constructor
  · intro h
    simp only [Bool.or_eq_true, Bool.and_eq_true] at h
    rcases h with h | ⟨h1, h2⟩
    · left; simp only [decide_eq_true_eq] at h; exact h
    · right; constructor
      · simp only [beq_iff_eq] at h1; exact h1
      · simp only [decide_eq_true_eq] at h2; exact h2
  · intro h
    simp only [Bool.or_eq_true, Bool.and_eq_true]
    rcases h with h | ⟨h1, h2⟩
    · left; simp only [decide_eq_true_eq]; exact h
    · right; constructor
      · simp only [beq_iff_eq]; exact h1
      · simp only [decide_eq_true_eq]; exact h2

/-- IU2 (false case): The negation also reflects the spec. -/
theorem isUpToDate_false_iff (voter : LogId) (ct ci : Nat) :
    isUpToDate voter ct ci = false ↔ ¬ logGe voter.term voter.index ct ci := by
  have h := isUpToDate_iff voter ct ci
  cases hb : isUpToDate voter ct ci <;> simp_all

-- ============================================================
-- Core properties of the log ordering
-- ============================================================

/-- IU3 (Reflexivity): Every log is at least as up-to-date as itself. -/
theorem isUpToDate_refl (voter : LogId) :
    isUpToDate voter voter.term voter.index = true := by
  simp [isUpToDate]

/-- IU4 (Reflexivity via logGe): The log order is reflexive. -/
theorem logGe_refl (t i : Nat) : logGe t i t i := by
  simp [logGe]

/-- IU5 (Higher term wins): If the candidate term is strictly higher, it's always up-to-date. -/
theorem isUpToDate_high_term (voter : LogId) (ct ci : Nat) (h : ct > voter.term) :
    isUpToDate voter ct ci = true := by
  rw [isUpToDate_iff]
  exact Or.inl h

/-- IU6 (Lower term loses): If the candidate term is strictly lower, it's never up-to-date. -/
theorem isUpToDate_low_term (voter : LogId) (ct ci : Nat) (h : ct < voter.term) :
    isUpToDate voter ct ci = false := by
  simp [isUpToDate]
  omega

/-- IU7 (Same term): When terms are equal, the index decides. -/
theorem isUpToDate_same_term (voter : LogId) (ci : Nat) (h : ci ≥ voter.index) :
    isUpToDate voter voter.term ci = true := by
  simp [isUpToDate, h]

/-- IU8 (Same term, shorter): When terms are equal and candidate index is smaller, it loses. -/
theorem isUpToDate_same_term_short (voter : LogId) (ci : Nat) (h : ci < voter.index) :
    isUpToDate voter voter.term ci = false := by
  simp [isUpToDate]
  omega

-- ============================================================
-- Order properties
-- ============================================================

/-- IU9 (Totality): For any two log IDs, at least one is ≥_log the other. -/
theorem logGe_total (t1 i1 t2 i2 : Nat) :
    logGe t1 i1 t2 i2 ∨ logGe t2 i2 t1 i1 := by
  simp [logGe]
  omega

/-- IU10 (Totality via isUpToDate). -/
theorem isUpToDate_total (v1 v2 : LogId) :
    isUpToDate v1 v2.term v2.index = true ∨ isUpToDate v2 v1.term v1.index = true := by
  rw [isUpToDate_iff, isUpToDate_iff]
  exact logGe_total v1.term v1.index v2.term v2.index

/-- IU11 (Antisymmetry): If A ≥_log B and B ≥_log A then A = B. -/
theorem logGe_antisymm (t1 i1 t2 i2 : Nat)
    (h1 : logGe t1 i1 t2 i2) (h2 : logGe t2 i2 t1 i1) :
    t1 = t2 ∧ i1 = i2 := by
  simp [logGe] at h1 h2
  omega

/-- IU12 (Antisymmetry via isUpToDate). -/
theorem isUpToDate_antisymm (v1 v2 : LogId)
    (h1 : isUpToDate v1 v2.term v2.index = true)
    (h2 : isUpToDate v2 v1.term v1.index = true) :
    v1 = v2 := by
  rw [isUpToDate_iff] at h1 h2
  have ⟨ht, hi⟩ := logGe_antisymm v1.term v1.index v2.term v2.index h1 h2
  cases v1; cases v2; simp_all

/-- IU13 (Transitivity): The log order is transitive. -/
theorem logGe_trans (t1 i1 t2 i2 t3 i3 : Nat)
    (h1 : logGe t2 i2 t3 i3) (h2 : logGe t1 i1 t2 i2) :
    logGe t1 i1 t3 i3 := by
  simp [logGe] at *
  omega

/-- IU14 (Transitivity via isUpToDate). -/
theorem isUpToDate_trans (v1 v2 v3 : LogId)
    (h1 : isUpToDate v2 v3.term v3.index = true)
    (h2 : isUpToDate v1 v2.term v2.index = true) :
    isUpToDate v1 v3.term v3.index = true := by
  rw [isUpToDate_iff] at *
  exact logGe_trans v1.term v1.index v2.term v2.index v3.term v3.index h1 h2

-- ============================================================
-- Relationship to lexicographic order
-- ============================================================

/-- IU15: `isUpToDate` is equivalent to lexicographic order on (term, index) pairs.
    We express this without Prod.le (not available in stdlib) by unfolding the definition. -/
theorem isUpToDate_iff_lex (voter : LogId) (ct ci : Nat) :
    isUpToDate voter ct ci = true ↔
    (ct > voter.term ∨ (ct = voter.term ∧ ci ≥ voter.index)) := by
  rw [isUpToDate_iff]; rfl

-- ============================================================
-- Safety property: the election restriction
-- ============================================================

/-- IU16: A voter grants a vote only to a candidate that is at least as up-to-date.
    This means: if a committed entry E is in the voter's log (at or before voter_index),
    and the candidate's log is up-to-date, then the candidate's log index is at least
    as large as the voter's when their terms match.

    Concretely: if terms match and the candidate passes the check, it has at least
    as many entries as the voter. -/
theorem isUpToDate_same_term_length (voter : LogId) (ci : Nat)
    (h : isUpToDate voter voter.term ci = true) :
    ci ≥ voter.index := by
  simp [isUpToDate] at h
  omega

/-- IU17: Strict up-to-date (strictly more up-to-date): candidate strictly dominates voter. -/
def strictlyUpToDate (voter : LogId) (ct ci : Nat) : Prop :=
  ct > voter.term ∨ (ct = voter.term ∧ ci > voter.index)

/-- IU18: Strictly up-to-date ↔ up-to-date but not equal. -/
theorem strictlyUpToDate_iff (voter : LogId) (ct ci : Nat) :
    strictlyUpToDate voter ct ci ↔
    (isUpToDate voter ct ci = true ∧ ¬ (ct = voter.term ∧ ci = voter.index)) := by
  rw [isUpToDate_iff]
  simp [strictlyUpToDate, logGe]
  omega

-- ============================================================
-- Decidability / evaluation examples
-- ============================================================

-- Voter log: term=3, index=10
#eval isUpToDate ⟨3, 10⟩ 3 10   -- true  (equal)
#eval isUpToDate ⟨3, 10⟩ 3 11   -- true  (same term, longer)
#eval isUpToDate ⟨3, 10⟩ 3 9    -- false (same term, shorter)
#eval isUpToDate ⟨3, 10⟩ 4 1    -- true  (higher term)
#eval isUpToDate ⟨3, 10⟩ 2 100  -- false (lower term)
#eval isUpToDate ⟨3, 10⟩ 3 0    -- false (same term, index=0 < 10)

-- Decided examples:
example : isUpToDate ⟨3, 10⟩ 3 10 = true  := by decide
example : isUpToDate ⟨3, 10⟩ 3 11 = true  := by decide
example : isUpToDate ⟨3, 10⟩ 3 9  = false := by decide
example : isUpToDate ⟨3, 10⟩ 4 1  = true  := by decide
example : isUpToDate ⟨3, 10⟩ 2 100 = false := by decide
