/-!
  # Unstable log: formal spec and proofs

  Formalises `src/log_unstable.rs` — the unstable (not-yet-persisted) log segment
  in TiKV's Raft implementation.

  ## Model

  * `entries : List Nat` — entry terms; position `i` has log index `offset + i`
  * `offset   : Nat`     — log index of `entries[0]`
  * `snapshot : Option (Nat × Nat)` — `some (index, term)` of a pending snapshot, or `none`

  Abstractions (omitted from model):
  * Entry payloads (only terms are tracked)
  * Logger (side effect, elided)
  * `entries_size` (byte accounting; not needed for correctness)
  * Panic / fatal-log pre-conditions (we model only the success path)
  * `u64` overflow (we use `Nat`; practical log sizes ≪ 2⁶³)

  Source: `src/log_unstable.rs`
  Informal spec: `formal-verification/specs/log_unstable_informal.md`

  🔬 Generated by Lean Squad automated formal verification.
-/

-- ═══════════════════════════════════════════════════════════
-- Data structure
-- ═══════════════════════════════════════════════════════════

/-- Abstract model of the unstable log segment.
    `entries[i]` has log term `entries[i]` and log index `offset + i`. -/
structure Unstable where
  offset   : Nat
  entries  : List Nat         -- terms; index of entries[i] is offset + i
  snapshot : Option (Nat × Nat)  -- some (snap_index, snap_term) or none
  deriving Repr, DecidableEq

-- ═══════════════════════════════════════════════════════════
-- Query functions
-- ═══════════════════════════════════════════════════════════

/-- Returns `snapshot.index + 1` if a snapshot is pending, else None.
    Models `Unstable::maybe_first_index`. -/
def maybeFirstIndex (u : Unstable) : Option Nat :=
  u.snapshot.map (fun ⟨sidx, _⟩ => sidx + 1)

/-- Returns the last log index in the unstable segment.
    Models `Unstable::maybe_last_index`. -/
def maybeLastIndex (u : Unstable) : Option Nat :=
  match u.entries with
  | []     => u.snapshot.map (fun ⟨sidx, _⟩ => sidx)
  | _ :: _ => some (u.offset + u.entries.length - 1)

/-- Returns the term of the entry at log index `idx`, if present.
    Models `Unstable::maybe_term`. -/
def maybeTerm (u : Unstable) (idx : Nat) : Option Nat :=
  if idx < u.offset then
    match u.snapshot with
    | none              => none
    | some ⟨sidx, st⟩  => if idx = sidx then some st else none
  else
    u.entries[idx - u.offset]?

-- ═══════════════════════════════════════════════════════════
-- State transitions
-- ═══════════════════════════════════════════════════════════

/-- Advance offset past all entries (entries have been persisted to stable storage).
    Pre-condition: entries non-empty; last entry has the expected index/term (assumed).
    Models `Unstable::stable_entries`. -/
def stableEntries (u : Unstable) : Unstable :=
  { u with offset := u.offset + u.entries.length, entries := [] }

/-- Clear the pending snapshot (it has been persisted).
    Pre-condition: snapshot = some (index, _) (assumed).
    Models `Unstable::stable_snap`. -/
def stableSnap (u : Unstable) : Unstable :=
  { u with snapshot := none }

/-- Restore state from a new snapshot.
    Models `Unstable::restore`. -/
def restore (snapIdx snapTerm : Nat) : Unstable :=
  { offset := snapIdx + 1, entries := [], snapshot := some (snapIdx, snapTerm) }

/-- Append new entry terms starting at log index `after`, truncating if needed.
    Pre-condition: `newTerms` is non-empty (assumed).
    Three cases mirror the Rust implementation exactly.
    Models `Unstable::truncate_and_append`. -/
def truncateAndAppend (u : Unstable) (newTerms : List Nat) (after : Nat) : Unstable :=
  if after = u.offset + u.entries.length then
    -- Case 1: `after` is the next slot — append directly
    { u with entries := u.entries ++ newTerms }
  else if after ≤ u.offset then
    -- Case 2: `after` predates offset — replace entire entries
    { u with offset := after, entries := newTerms }
  else
    -- Case 3: `after` is inside the current window — truncate then append
    { u with entries := u.entries.take (after - u.offset) ++ newTerms }

/-- Return entry terms with log indices in `[lo, hi)`.
    Pre-condition: `u.offset ≤ lo ≤ hi ≤ u.offset + u.entries.length` (assumed).
    Models `Unstable::slice`. -/
def slice (u : Unstable) (lo hi : Nat) : List Nat :=
  (u.entries.drop (lo - u.offset)).take (hi - lo)

-- ═══════════════════════════════════════════════════════════
-- Eval examples (sanity-check the model)
-- ═══════════════════════════════════════════════════════════

private def uEx : Unstable :=
  { offset := 5, entries := [10, 20, 30], snapshot := none }

#eval maybeLastIndex uEx           -- expected: some 7  (= 5 + 3 - 1)
#eval maybeTerm uEx 5              -- expected: some 10 (entries[0])
#eval maybeTerm uEx 6              -- expected: some 20 (entries[1])
#eval maybeTerm uEx 8              -- expected: none    (out of range)

-- truncateAndAppend case 1: after = offset + len = 8 → append
#eval (truncateAndAppend uEx [40, 50] 8).entries  -- expected: [10,20,30,40,50]
-- truncateAndAppend case 2: after = 3 ≤ 5 = offset → replace
#eval (truncateAndAppend uEx [40, 50] 3).offset   -- expected: 3
#eval (truncateAndAppend uEx [40, 50] 3).entries  -- expected: [40,50]
-- truncateAndAppend case 3: after = 6; 5 < 6 < 8 → truncate+append
#eval (truncateAndAppend uEx [40, 50] 6).entries  -- expected: [10,40,50]

-- ═══════════════════════════════════════════════════════════
-- maybeFirstIndex theorems
-- ═══════════════════════════════════════════════════════════

/-- MFI1: maybeFirstIndex is None when no snapshot. -/
theorem maybeFirstIndex_none (u : Unstable) (h : u.snapshot = none) :
    maybeFirstIndex u = none := by
  simp [maybeFirstIndex, h]

/-- MFI2: maybeFirstIndex is snapshot.index + 1 when snapshot present. -/
theorem maybeFirstIndex_some (u : Unstable) (sidx sterm : Nat)
    (h : u.snapshot = some (sidx, sterm)) :
    maybeFirstIndex u = some (sidx + 1) := by
  simp [maybeFirstIndex, h]

-- ═══════════════════════════════════════════════════════════
-- maybeLastIndex theorems
-- ═══════════════════════════════════════════════════════════

/-- MLI1: maybeLastIndex is None when entries empty and no snapshot. -/
theorem maybeLastIndex_empty_none (u : Unstable)
    (he : u.entries = []) (hs : u.snapshot = none) :
    maybeLastIndex u = none := by
  simp [maybeLastIndex, he, hs]

/-- MLI2: maybeLastIndex is snapshot.index when entries empty and snapshot present. -/
theorem maybeLastIndex_snapshot (u : Unstable) (sidx sterm : Nat)
    (he : u.entries = []) (hs : u.snapshot = some (sidx, sterm)) :
    maybeLastIndex u = some sidx := by
  simp [maybeLastIndex, he, hs]

/-- MLI3: maybeLastIndex is offset + len - 1 when entries non-empty. -/
theorem maybeLastIndex_entries (u : Unstable) (hne : u.entries ≠ []) :
    maybeLastIndex u = some (u.offset + u.entries.length - 1) := by
  unfold maybeLastIndex
  match u.entries, hne with
  | _ :: _, _ => simp

-- ═══════════════════════════════════════════════════════════
-- maybeTerm theorems
-- ═══════════════════════════════════════════════════════════

/-- MT1: maybeTerm is None when idx < offset and no snapshot. -/
theorem maybeTerm_before_no_snapshot (u : Unstable) (idx : Nat)
    (h1 : idx < u.offset) (h2 : u.snapshot = none) :
    maybeTerm u idx = none := by
  simp [maybeTerm, h1, h2]

/-- MT2: maybeTerm returns snapshot term when idx = snapshot.index and idx < offset. -/
theorem maybeTerm_snapshot_hit (u : Unstable) (sidx sterm : Nat)
    (h1 : sidx < u.offset) (h2 : u.snapshot = some (sidx, sterm)) :
    maybeTerm u sidx = some sterm := by
  simp [maybeTerm, h1, h2]

/-- MT3: maybeTerm is None when idx < offset, snapshot present, but idx ≠ snapshot.index. -/
theorem maybeTerm_snapshot_miss (u : Unstable) (sidx sterm idx : Nat)
    (h1 : idx < u.offset) (h2 : u.snapshot = some (sidx, sterm)) (h3 : idx ≠ sidx) :
    maybeTerm u idx = none := by
  simp [maybeTerm, h1, h2, h3]

/-- MT4: maybeTerm returns the entry term when idx is within the entries range. -/
theorem maybeTerm_entries_hit (u : Unstable) (idx : Nat)
    (h1 : u.offset ≤ idx) (h2 : idx - u.offset < u.entries.length) :
    maybeTerm u idx = some (u.entries[idx - u.offset]'h2) := by
  simp only [maybeTerm, if_neg (Nat.not_lt.mpr h1)]
  exact List.getElem?_eq_getElem h2

/-- MT5: maybeTerm is None when idx ≥ offset + entries.length. -/
theorem maybeTerm_entries_miss (u : Unstable) (idx : Nat)
    (h1 : u.offset ≤ idx) (h2 : u.entries.length ≤ idx - u.offset) :
    maybeTerm u idx = none := by
  simp only [maybeTerm, if_neg (Nat.not_lt.mpr h1)]
  exact List.getElem?_eq_none h2

-- ═══════════════════════════════════════════════════════════
-- stableEntries theorems
-- ═══════════════════════════════════════════════════════════

/-- SE1: offset advances past all entries. -/
theorem stableEntries_offset (u : Unstable) :
    (stableEntries u).offset = u.offset + u.entries.length := by
  simp [stableEntries]

/-- SE2: entries are cleared. -/
theorem stableEntries_entries_empty (u : Unstable) :
    (stableEntries u).entries = [] := by
  simp [stableEntries]

/-- SE3: snapshot is preserved. -/
theorem stableEntries_snapshot (u : Unstable) :
    (stableEntries u).snapshot = u.snapshot := by
  simp [stableEntries]

/-- SE4: offset strictly advances when entries were non-empty. -/
theorem stableEntries_offset_advances (u : Unstable) (h : u.entries ≠ []) :
    u.offset < (stableEntries u).offset := by
  simp only [stableEntries]
  have hlen : 0 < u.entries.length := by
    cases h_eq : u.entries with
    | nil  => exact absurd h_eq h
    | cons _ _ => simp
  omega

/-- SE5: maybeLastIndex after stableEntries is None (no entries, no change to snapshot). -/
theorem stableEntries_maybeLastIndex_none (u : Unstable)
    (hs : u.snapshot = none) :
    maybeLastIndex (stableEntries u) = none := by
  simp [stableEntries, maybeLastIndex, hs]

-- ═══════════════════════════════════════════════════════════
-- stableSnap theorems
-- ═══════════════════════════════════════════════════════════

/-- SS1: snapshot is cleared. -/
theorem stableSnap_no_snapshot (u : Unstable) :
    (stableSnap u).snapshot = none := by
  simp [stableSnap]

/-- SS2: entries are preserved. -/
theorem stableSnap_entries (u : Unstable) :
    (stableSnap u).entries = u.entries := by
  simp [stableSnap]

/-- SS3: offset is preserved. -/
theorem stableSnap_offset (u : Unstable) :
    (stableSnap u).offset = u.offset := by
  simp [stableSnap]

-- ═══════════════════════════════════════════════════════════
-- restore theorems
-- ═══════════════════════════════════════════════════════════

/-- RE1: offset is set to snapIdx + 1. -/
theorem restore_offset (snapIdx snapTerm : Nat) :
    (restore snapIdx snapTerm).offset = snapIdx + 1 := by
  simp [restore]

/-- RE2: entries are empty after restore. -/
theorem restore_entries_empty (snapIdx snapTerm : Nat) :
    (restore snapIdx snapTerm).entries = [] := by
  simp [restore]

/-- RE3: snapshot is set to (snapIdx, snapTerm). -/
theorem restore_snapshot (snapIdx snapTerm : Nat) :
    (restore snapIdx snapTerm).snapshot = some (snapIdx, snapTerm) := by
  simp [restore]

/-- RE4: maybeLastIndex after restore is the snapshot index. -/
theorem restore_maybeLastIndex (snapIdx snapTerm : Nat) :
    maybeLastIndex (restore snapIdx snapTerm) = some snapIdx := by
  simp [maybeLastIndex, restore]

/-- RE5: maybeFirstIndex after restore is snapIdx + 1. -/
theorem restore_maybeFirstIndex (snapIdx snapTerm : Nat) :
    maybeFirstIndex (restore snapIdx snapTerm) = some (snapIdx + 1) := by
  simp [maybeFirstIndex, restore]

/-- RE6: maybeTerm at the snapshot index returns the snapshot term. -/
theorem restore_maybeTerm_hit (snapIdx snapTerm : Nat) :
    maybeTerm (restore snapIdx snapTerm) snapIdx = some snapTerm := by
  simp [maybeTerm, restore]

/-- RE7: maybeTerm below the snapshot index returns None. -/
theorem restore_maybeTerm_before (snapIdx snapTerm idx : Nat) (h : idx < snapIdx) :
    maybeTerm (restore snapIdx snapTerm) idx = none := by
  simp only [maybeTerm, restore]
  have h1 : idx < snapIdx + 1 := by omega
  rw [if_pos h1]
  have h2 : idx ≠ snapIdx := by omega
  simp [h2]

-- ═══════════════════════════════════════════════════════════
-- truncateAndAppend theorems
-- ═══════════════════════════════════════════════════════════

/-- TAA1 (Case 1): when after = offset + len, entries are appended directly. -/
theorem truncateAndAppend_case1 (u : Unstable) (newTerms : List Nat) (after : Nat)
    (h : after = u.offset + u.entries.length) :
    (truncateAndAppend u newTerms after).entries = u.entries ++ newTerms := by
  unfold truncateAndAppend
  rw [if_pos h]

/-- TAA2 (Case 1): length after append. -/
theorem truncateAndAppend_case1_length (u : Unstable) (newTerms : List Nat) (after : Nat)
    (h : after = u.offset + u.entries.length) :
    (truncateAndAppend u newTerms after).entries.length =
    u.entries.length + newTerms.length := by
  rw [truncateAndAppend_case1 u newTerms after h, List.length_append]

/-- TAA3 (Case 1): offset is unchanged. -/
theorem truncateAndAppend_case1_offset (u : Unstable) (newTerms : List Nat) (after : Nat)
    (h : after = u.offset + u.entries.length) :
    (truncateAndAppend u newTerms after).offset = u.offset := by
  unfold truncateAndAppend
  rw [if_pos h]

/-- TAA4 (Case 2): when after ≤ offset, entries are replaced and offset updated. -/
theorem truncateAndAppend_case2 (u : Unstable) (newTerms : List Nat) (after : Nat)
    (h1 : after ≠ u.offset + u.entries.length) (h2 : after ≤ u.offset) :
    (truncateAndAppend u newTerms after).offset = after ∧
    (truncateAndAppend u newTerms after).entries = newTerms := by
  unfold truncateAndAppend
  rw [if_neg h1, if_pos h2]
  exact ⟨rfl, rfl⟩

/-- TAA5 (Case 3): when offset < after < offset + len, truncate then append. -/
theorem truncateAndAppend_case3 (u : Unstable) (newTerms : List Nat) (after : Nat)
    (h1 : after ≠ u.offset + u.entries.length) (h2 : ¬(after ≤ u.offset)) :
    (truncateAndAppend u newTerms after).entries =
    u.entries.take (after - u.offset) ++ newTerms := by
  unfold truncateAndAppend
  rw [if_neg h1, if_neg h2]

/-- TAA6 (Case 3): length after truncate+append. -/
theorem truncateAndAppend_case3_length (u : Unstable) (newTerms : List Nat) (after : Nat)
    (h1 : after ≠ u.offset + u.entries.length) (h2 : ¬(after ≤ u.offset))
    (h3 : after - u.offset ≤ u.entries.length) :
    (truncateAndAppend u newTerms after).entries.length =
    (after - u.offset) + newTerms.length := by
  rw [truncateAndAppend_case3 u newTerms after h1 h2, List.length_append, List.length_take]
  simp [Nat.min_eq_left h3]

/-- TAA7: snapshot is always preserved by truncateAndAppend. -/
theorem truncateAndAppend_snapshot_preserved (u : Unstable) (newTerms : List Nat) (after : Nat) :
    (truncateAndAppend u newTerms after).snapshot = u.snapshot := by
  unfold truncateAndAppend
  by_cases h1 : after = u.offset + u.entries.length
  · rw [if_pos h1]
  · rw [if_neg h1]
    by_cases h2 : after ≤ u.offset
    · rw [if_pos h2]
    · rw [if_neg h2]

-- ═══════════════════════════════════════════════════════════
-- slice theorems
-- ═══════════════════════════════════════════════════════════

/-- SL1: slice length equals hi - lo (given valid bounds). -/
theorem slice_length (u : Unstable) (lo hi : Nat)
    (h1 : u.offset ≤ lo) (h2 : lo ≤ hi) (h3 : hi ≤ u.offset + u.entries.length) :
    (slice u lo hi).length = hi - lo := by
  unfold slice
  rw [List.length_take, List.length_drop]
  simp only [Nat.min_def]
  split
  · omega
  · omega

-- ═══════════════════════════════════════════════════════════
-- Well-formedness invariant
-- ═══════════════════════════════════════════════════════════

/-- Well-formedness: snapshot index is strictly before offset.
    This ensures the snapshot does not overlap with the entries window. -/
def wf (u : Unstable) : Prop :=
  match u.snapshot with
  | none             => True
  | some ⟨sidx, _⟩  => sidx < u.offset

/-- WF1: restore satisfies the invariant. -/
theorem restore_wf (snapIdx snapTerm : Nat) : wf (restore snapIdx snapTerm) := by
  simp [wf, restore]

/-- WF2: stableEntries preserves the invariant. -/
theorem stableEntries_wf (u : Unstable) (h : wf u) : wf (stableEntries u) := by
  unfold wf stableEntries at *
  cases hsnap : u.snapshot with
  | none =>
    simp
  | some p =>
    obtain ⟨sidx, _⟩ := p
    simp only [hsnap] at h ⊢
    omega

/-- WF3: stableSnap satisfies the invariant (trivially: no snapshot). -/
theorem stableSnap_wf (u : Unstable) : wf (stableSnap u) := by
  simp [wf, stableSnap]

/-- WF4: truncateAndAppend case 1 preserves wf (offset and snapshot unchanged). -/
theorem truncateAndAppend_case1_wf (u : Unstable) (newTerms : List Nat) (after : Nat)
    (h : after = u.offset + u.entries.length) (hwf : wf u) :
    wf (truncateAndAppend u newTerms after) := by
  unfold wf
  rw [truncateAndAppend_snapshot_preserved, truncateAndAppend_case1_offset u newTerms after h]
  exact hwf
