import FVSquad.HasNextEntries

/-!
# NextEntries — Formal Spec for `next_entries_since` / `next_entries`

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

This file formalises the key correctness properties of `RaftLog::next_entries_since`
and `RaftLog::next_entries` (`src/raft_log.rs:447–492`), building on the boolean
companion in `HasNextEntries.lean` (HNE1–HNE14, Run 111).

## Source

```rust
pub fn next_entries_since(&self, since_idx: u64, max_size: Option<u64>) -> Option<Vec<Entry>> {
    let offset = cmp::max(since_idx + 1, self.first_index());
    let high = self.applied_index_upper_bound() + 1;
    if high > offset {
        match self.slice(offset, high, max_size, ...) {
            Ok(vec) => return Some(vec),
            Err(e)  => fatal!(...),
        }
    }
    None
}

pub fn next_entries(&self, max_size: Option<u64>) -> Option<Vec<Entry>> {
    self.next_entries_since(self.applied, max_size)
}
```

## Model

We model entry slots as their log indices (`Nat`). `max_size` truncation
is ignored — the full slice `[offset .. upperBound]` is always returned in the abstract
model, where `offset = max(sinceIdx + 1, firstIndex)` and
`upperBound = appliedIndexUpperBound(committed, persisted, limit)`.

## Theorem Index

| ID   | Name                               | Description                                          |
|------|------------------------------------|------------------------------------------------------|
| NE1  | `NE1_none_iff_not_has`             | Returns `none` ↔ `hasNextEntriesSince = false`       |
| NE2  | `NE2_some_length`                  | If `Some(es)`, length = upper_bound − offset + 1     |
| NE3  | `NE3_some_indices`                 | The i-th element equals offset + i                   |
| NE4  | `NE4_anti_mono_since`              | Anti-monotone in `sinceIdx`                          |
| NE5  | `NE5_mono_committed`               | Monotone in `committed`                              |
| NE6  | `NE6_mono_persisted`               | Monotone in `persisted`                              |
| NE7  | `NE7_eq_since_applied`             | `next_entries = next_entries_since(applied)`         |

**Sorry count**: 0.  All theorems proved without `sorry`.

🔬 Generated by Lean Squad automated formal verification (Run 113).
-/

namespace FVSquad.NextEntries

open FVSquad.HasNextEntries

/-! ## Core model -/

/-- Compute `offset = max(sinceIdx + 1, firstIndex)`. -/
def neOffset (firstIndex sinceIdx : Nat) : Nat :=
  max (sinceIdx + 1) firstIndex

/-- Model of `next_entries_since` returning `Option (List Nat)` (entry log indices).
    Returns the slice `[offset .. upperBound]` as a list when `offset ≤ upperBound`,
    otherwise `none`. `max_size` is abstracted away. -/
def nextEntriesSince (firstIndex committed persisted limit sinceIdx : Nat) : Option (List Nat) :=
  let ub  := appliedIndexUpperBound committed persisted limit
  let off := neOffset firstIndex sinceIdx
  if off ≤ ub then
    some (List.range (ub - off + 1) |>.map (· + off))
  else
    none

/-- Model of `next_entries` (calls `next_entries_since(applied)`). -/
def nextEntries (firstIndex committed persisted limit applied : Nat) : Option (List Nat) :=
  nextEntriesSince firstIndex committed persisted limit applied

/-! ## Core auxiliary: isSome ↔ offset ≤ upperBound -/

private theorem isSome_iff (fi c p l si : Nat) :
    (nextEntriesSince fi c p l si).isSome ↔
    neOffset fi si ≤ appliedIndexUpperBound c p l := by
  simp [nextEntriesSince]

/-! ## NE1: Returns none ↔ hasNextEntriesSince = false -/

/-- **NE1** — `nextEntriesSince` returns `none` iff `hasNextEntriesSince = false`. -/
theorem NE1_none_iff_not_has
    (fi c p l si : Nat) :
    nextEntriesSince fi c p l si = none ↔
    hasNextEntriesSince fi c p l si = false := by
  simp only [nextEntriesSince, hasNextEntriesSince, neOffset, appliedIndexUpperBound]
  split
  · simp; omega
  · simp; omega

/-! ## NE2: Length of returned slice -/

/-- **NE2** — When `Some(es)` is returned, the length equals `upperBound − offset + 1`. -/
theorem NE2_some_length
    (fi c p l si : Nat) (es : List Nat)
    (h : nextEntriesSince fi c p l si = some es) :
    es.length = appliedIndexUpperBound c p l - neOffset fi si + 1 := by
  simp only [nextEntriesSince] at h
  split at h
  · simp only [Option.some.injEq] at h; subst h
    simp [List.length_map, List.length_range]
  · exact absurd h (by simp)

/-! ## NE3: Entries are at contiguous indices starting at offset -/

/-- **NE3** — The `i`-th element (0-based) of the returned slice equals `offset + i`. -/
theorem NE3_some_indices
    (fi c p l si : Nat) (es : List Nat)
    (h : nextEntriesSince fi c p l si = some es)
    (i : Nat) (hi : i < es.length) :
    es[i]'hi = neOffset fi si + i := by
  simp only [nextEntriesSince] at h
  split at h
  · simp only [Option.some.injEq] at h; subst h
    simp [List.getElem_map, List.getElem_range]
    omega
  · exact absurd h (by simp)

/-! ## NE4–NE6: Monotonicity — proved via hasNextEntriesSince (HNE11–HNE13) -/

/-- Helper: `nextEntriesSince` is isSome iff `hasNextEntriesSince = true`. -/
private theorem isSome_eq_has (fi c p l si : Nat) :
    (nextEntriesSince fi c p l si).isSome = (hasNextEntriesSince fi c p l si) := by
  simp [nextEntriesSince, hasNextEntriesSince, neOffset, appliedIndexUpperBound]
  split <;> simp <;> omega

/-- **NE4** — Anti-monotone in `sinceIdx`: smaller index ⇒ at least as many entries. -/
theorem NE4_anti_mono_since
    (fi c p l j k : Nat) (hjk : j ≤ k)
    (hk : (nextEntriesSince fi c p l k).isSome = true) :
    (nextEntriesSince fi c p l j).isSome = true := by
  rw [isSome_eq_has] at *
  exact HNE11_hasNextEntriesSince_anti_mono_since fi c p l j k hjk hk

/-- **NE5** — Monotone in `committed`. -/
theorem NE5_mono_committed
    (fi c1 c2 p l si : Nat) (hle : c1 ≤ c2)
    (h1 : (nextEntriesSince fi c1 p l si).isSome = true) :
    (nextEntriesSince fi c2 p l si).isSome = true := by
  rw [isSome_eq_has] at *
  exact HNE12_hasNextEntriesSince_mono_committed fi c1 c2 p l si hle h1

/-- **NE6** — Monotone in `persisted`. -/
theorem NE6_mono_persisted
    (fi c p1 p2 l si : Nat) (hle : p1 ≤ p2)
    (h1 : (nextEntriesSince fi c p1 l si).isSome = true) :
    (nextEntriesSince fi c p2 l si).isSome = true := by
  rw [isSome_eq_has] at *
  exact HNE13_hasNextEntriesSince_mono_persisted fi c p1 p2 l si hle h1

/-! ## NE7: nextEntries = nextEntriesSince(applied) -/

/-- **NE7** — `nextEntries` equals `nextEntriesSince applied`. -/
theorem NE7_eq_since_applied
    (fi c p l applied : Nat) :
    nextEntries fi c p l applied = nextEntriesSince fi c p l applied :=
  rfl

/-! ## Correspondence examples (compile-time guards) -/

-- NE1: none iff has = false
#guard nextEntriesSince 1 5 5 0 5 = none        -- offset=6 > ub=5 → none
#guard nextEntriesSince 1 5 5 0 4 = some [5]    -- offset=5 ≤ ub=5 → [5]
#guard nextEntriesSince 1 5 5 0 3 = some [4, 5] -- offset=4 ≤ ub=5 → [4,5]
#guard nextEntriesSince 1 0 0 0 0 = none        -- ub=0, offset=1 > 0 → none

-- NE2: length check
#guard (nextEntriesSince 1 5 5 0 3).map List.length = some 2  -- 5-4+1=2
#guard (nextEntriesSince 1 10 7 0 4).map List.length = some 3 -- ub=min(10,7)=7, offset=5

-- NE3: contiguous indices
#guard nextEntriesSince 1 5 5 0 2 = some [3, 4, 5]  -- offset=3, ub=5
#guard nextEntriesSince 1 10 7 0 4 = some [5, 6, 7] -- offset=5, ub=7

-- NE4: anti-monotone in sinceIdx
#guard (nextEntriesSince 1 5 5 0 5).isSome = false
#guard (nextEntriesSince 1 5 5 0 4).isSome = true

-- NE5/NE6: monotone in committed / persisted
#guard (nextEntriesSince 1 3 5 0 2).isSome = true
#guard (nextEntriesSince 1 5 5 0 2).isSome = true

-- NE7: nextEntries = nextEntriesSince applied
#guard nextEntries 1 5 5 0 3 = nextEntriesSince 1 5 5 0 3

end FVSquad.NextEntries
