import FVSquad.NextEntries

/-!
# NextEntriesCorrespondence — Compile-time Correspondence Tests

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

Static correspondence validation for `nextEntriesSince` / `nextEntries` /
`hasNextEntriesSince` via `#guard` assertions that run at `lake build` time.

## Strategy (Task 8, Route B)

The `#guard` cases here are mirrored in the Rust function
`test_next_entries_correspondence` in `src/raft_log.rs` (see end of file).

- **Lean side**: `#guard` evaluates the model at lake-build time.
- **Rust side**: `assert_eq!` validates the implementation at `cargo test` time.

Together they give direct behavioural evidence that the Lean model and the Rust
implementation agree on 20 representative inputs.

## Fixture

The Rust test starts with a snapshot at index 3 and appends entries at indices
4–10 (all term 1). Thus `firstIndex = 4`.

Key parameters: `(applied, persisted, committed, limit)` → `expected isSome`.
The Lean model ignores `max_size`; `limit` maps to `max_apply_unpersisted_log_limit`.

## Case Table (isSome)

| # | applied | persisted | committed | limit | expected isSome | expected slice |
|---|---------|-----------|-----------|-------|-----------------|----------------|
| 1 | 0       | 3         | 3         | 0     | false           | None           |
| 2 | 0       | 3         | 4         | 0     | false           | None           |
| 3 | 0       | 3         | 4         | UNLT  | true            | [4]            |
| 4 | 0       | 4         | 6         | 0     | true            | [4]            |
| 5 | 0       | 4         | 6         | 2     | true            | [4,5,6]        |
| 6 | 0       | 4         | 10        | 0     | true            | [4]            |
| 7 | 0       | 4         | 10        | 2     | true            | [4,5,6]        |
| 8 | 0       | 4         | 10        | 6     | true            | [4..10]        |
| 9 | 3       | 4         | 3         | UNLT  | false           | None           |
|10 | 3       | 5         | 5         | UNLT  | true            | [4,5]          |
|11 | 4       | 5         | 5         | UNLT  | true            | [5]            |
|12 | 5       | 5         | 5         | 0     | false           | None           |
|13 | 5       | 7         | 7         | UNLT  | true            | [6,7]          |
|14 | 7       | 7         | 7         | UNLT  | false           | None           |
|15 | 8       | 6         | 8         | 0     | false           | None (applied>ub)|
|16 | 3       | 6         | 7         | UNLT  | true            | [4,5,6,7]      |
|17 | 3       | 7         | 6         | UNLT  | true            | [4,5,6]        |
|18 | 4       | 5         | 7         | UNLT  | true            | [5,6,7]        |
|19 | 4       | 7         | 5         | UNLT  | true            | [5]            |
|20 | 4       | 7         | 7         | 0     | true            | [5,6,7]        |

UNLT = very large limit (we use 10000).

🔬 Generated by Lean Squad automated formal verification (Run 113).
-/

open FVSquad.NextEntries FVSquad.HasNextEntries

-- Shorthand: use firstIndex = 4 for all cases (snapshot at 3)
private def fi : Nat := 4
-- Large limit standing in for "unlimited"
private def UNLT : Nat := 10000

/-! ## Case 1: applied=0, persisted=3, committed=3, limit=0 → None -/
-- ub = min(3, 3+0)=3, offset=max(1,4)=4, 4>3 → none
#guard nextEntriesSince fi 3 3 0 0 = none
#guard hasNextEntriesSince fi 3 3 0 0 = false

/-! ## Case 2: applied=0, persisted=3, committed=4, limit=0 → None -/
-- ub = min(4, 3+0)=3, offset=4, 4>3 → none
#guard nextEntriesSince fi 4 3 0 0 = none
#guard hasNextEntriesSince fi 4 3 0 0 = false

/-! ## Case 3: applied=0, persisted=3, committed=4, limit=UNLT → Some [4] -/
-- ub = min(4, 3+UNLT)=4, offset=4, 4≤4 → some [4]
#guard nextEntriesSince fi 4 3 UNLT 0 = some [4]
#guard hasNextEntriesSince fi 4 3 UNLT 0 = true

/-! ## Case 4: applied=0, persisted=4, committed=6, limit=0 → Some [4] -/
-- ub = min(6, 4+0)=4, offset=4 → some [4]
#guard nextEntriesSince fi 6 4 0 0 = some [4]

/-! ## Case 5: applied=0, persisted=4, committed=6, limit=2 → Some [4,5,6] -/
-- ub = min(6, 4+2)=6, offset=4 → some [4,5,6]
#guard nextEntriesSince fi 6 4 2 0 = some [4, 5, 6]

/-! ## Case 6: applied=0, persisted=4, committed=10, limit=0 → Some [4] -/
-- ub = min(10, 4+0)=4, offset=4 → some [4]
#guard nextEntriesSince fi 10 4 0 0 = some [4]

/-! ## Case 7: applied=0, persisted=4, committed=10, limit=2 → Some [4,5,6] -/
-- ub = min(10, 4+2)=6, offset=4 → some [4,5,6]
#guard nextEntriesSince fi 10 4 2 0 = some [4, 5, 6]

/-! ## Case 8: applied=0, persisted=4, committed=10, limit=6 → Some [4..10] -/
-- ub = min(10, 4+6)=10, offset=4 → some [4,5,6,7,8,9,10]
#guard nextEntriesSince fi 10 4 6 0 = some [4, 5, 6, 7, 8, 9, 10]

/-! ## Case 9: applied=3, persisted=4, committed=3, limit=UNLT → None -/
-- ub = min(3, UNLT)=3, offset=max(4,4)=4, 4>3 → none
#guard nextEntriesSince fi 3 4 UNLT 3 = none
#guard hasNextEntriesSince fi 3 4 UNLT 3 = false

/-! ## Case 10: applied=3, persisted=5, committed=5, limit=UNLT → Some [4,5] -/
-- ub = min(5, UNLT)=5, offset=max(4,4)=4, 4≤5 → some [4,5]
#guard nextEntriesSince fi 5 5 UNLT 3 = some [4, 5]
#guard hasNextEntriesSince fi 5 5 UNLT 3 = true

/-! ## Case 11: applied=4, persisted=5, committed=5, limit=UNLT → Some [5] -/
-- ub=5, offset=max(5,4)=5, 5≤5 → some [5]
#guard nextEntriesSince fi 5 5 UNLT 4 = some [5]

/-! ## Case 12: applied=5, persisted=5, committed=5, limit=0 → None -/
-- ub = min(5,5)=5, offset=max(6,4)=6, 6>5 → none
#guard nextEntriesSince fi 5 5 0 5 = none

/-! ## Case 13: applied=5, persisted=7, committed=7, limit=UNLT → Some [6,7] -/
-- ub=7, offset=max(6,4)=6, 6≤7 → some [6,7]
#guard nextEntriesSince fi 7 7 UNLT 5 = some [6, 7]

/-! ## Case 14: applied=7, persisted=7, committed=7, limit=UNLT → None -/
-- ub=7, offset=max(8,4)=8, 8>7 → none
#guard nextEntriesSince fi 7 7 UNLT 7 = none

/-! ## Case 15: applied=8, persisted=6, committed=8, limit=0 → None -/
-- ub = min(8,6+0)=6, offset=max(9,4)=9, 9>6 → none (applied > ub)
#guard nextEntriesSince fi 8 6 0 8 = none

/-! ## Case 16: applied=3, persisted=6, committed=7, limit=UNLT → Some [4..7] -/
-- ub=7, offset=max(4,4)=4 → some [4,5,6,7]
#guard nextEntriesSince fi 7 6 UNLT 3 = some [4, 5, 6, 7]

/-! ## Case 17: applied=3, persisted=7, committed=6, limit=UNLT → Some [4,5,6] -/
-- ub=6, offset=4 → some [4,5,6]
#guard nextEntriesSince fi 6 7 UNLT 3 = some [4, 5, 6]

/-! ## Case 18: applied=4, persisted=5, committed=7, limit=UNLT → Some [5,6,7] -/
-- ub=5, offset=max(5,4)=5 → some [5]? No wait: ub=min(7,5+UNLT)=7, offset=5 → [5,6,7]
#guard nextEntriesSince fi 7 5 UNLT 4 = some [5, 6, 7]

/-! ## Case 19: applied=4, persisted=7, committed=5, limit=UNLT → Some [5] -/
-- ub = min(5, UNLT)=5, offset=5, 5≤5 → some [5]
#guard nextEntriesSince fi 5 7 UNLT 4 = some [5]

/-! ## Case 20: applied=4, persisted=7, committed=7, limit=0 → Some [5,6,7] -/
-- ub = min(7, 7+0)=7, offset=5 → some [5,6,7]
#guard nextEntriesSince fi 7 7 0 4 = some [5, 6, 7]

/-! ## NE7: nextEntries calls nextEntriesSince(applied) -/
-- Check nextEntries with applied parameter
#guard nextEntries fi 5 5 UNLT 3 = some [4, 5]  -- case 10 via nextEntries
#guard nextEntries fi 7 7 UNLT 7 = none          -- case 14 via nextEntries
#guard nextEntries fi 5 5 0 5 = none             -- case 12 via nextEntries
