/-!
# Formal Specification: `Progress` — Raft Follower Replication State Machine

Formalises `src/tracker/progress.rs`.

`Progress` tracks how a single Raft follower is catching up with the leader's log.
It is a three-state machine (Probe / Replicate / Snapshot) with an invariant that
`matched + 1 ≤ next_idx`.

This model abstracts away:
- The `Inflights` ring buffer (replaced by a boolean `ins_full : Bool`)
- The `commit_group_id` and `committed_index` fields (not part of the state machine)
- Overflow (all indices modelled as `Nat`)
- The `recent_active` flag (pure metadata, no invariants)

> 🔬 Generated by Lean Squad automated formal verification.
-/

namespace FVSquad.Progress

-- ---------------------------------------------------------------------------
-- Types
-- ---------------------------------------------------------------------------

/-- The three replication states for a follower. -/
inductive ProgressState where
  | Probe    : ProgressState
  | Replicate : ProgressState
  | Snapshot : ProgressState
  deriving DecidableEq, Repr

/-- `INVALID_INDEX` sentinel (matches `src/raft.rs`: `pub const INVALID_INDEX: u64 = 0`). -/
def INVALID_INDEX : Nat := 0

/--
Simplified `Progress` model.  Fields correspond directly to the Rust struct;
`ins_full` abstracts `Inflights::full()`.
-/
structure Progress where
  matched                 : Nat
  next_idx                : Nat
  state                   : ProgressState
  paused                  : Bool
  pending_snapshot        : Nat
  pending_request_snapshot : Nat   -- 0 = INVALID_INDEX
  recent_active           : Bool
  ins_full                : Bool   -- abstraction of Inflights.full()
  deriving Repr

-- ---------------------------------------------------------------------------
-- Well-formedness invariant
-- ---------------------------------------------------------------------------

/-- The core invariant: `matched + 1 ≤ next_idx`. -/
def Progress.wf (p : Progress) : Prop :=
  p.matched + 1 ≤ p.next_idx

-- ---------------------------------------------------------------------------
-- Constructors and helpers
-- ---------------------------------------------------------------------------

/-- `Progress::new(next_idx, ins_size)`.  `ins_full` starts `false`. -/
def Progress.mk_new (next_idx : Nat) : Progress :=
  { matched                  := 0
    next_idx                 := next_idx
    state                    := ProgressState.Probe
    paused                   := false
    pending_snapshot         := 0
    pending_request_snapshot := INVALID_INDEX
    recent_active            := false
    ins_full                 := false }

/-- Internal `reset_state` helper: clears pause and pending_snapshot, sets state. -/
def Progress.resetState (p : Progress) (s : ProgressState) : Progress :=
  { p with paused := false, pending_snapshot := 0, state := s }

-- ---------------------------------------------------------------------------
-- State transitions
-- ---------------------------------------------------------------------------

/-- `Progress::become_probe`. -/
def Progress.becomeProbe (p : Progress) : Progress :=
  if p.state == ProgressState.Snapshot then
    let q := p.resetState ProgressState.Probe
    { q with next_idx := Nat.max (p.matched + 1) (p.pending_snapshot + 1) }
  else
    let q := p.resetState ProgressState.Probe
    { q with next_idx := p.matched + 1 }

/-- `Progress::become_replicate`. -/
def Progress.becomeReplicate (p : Progress) : Progress :=
  let q := p.resetState ProgressState.Replicate
  { q with next_idx := p.matched + 1 }

/-- `Progress::become_snapshot`. -/
def Progress.becomeSnapshot (p : Progress) (snapshot_idx : Nat) : Progress :=
  let q := p.resetState ProgressState.Snapshot
  { q with pending_snapshot := snapshot_idx }

-- ---------------------------------------------------------------------------
-- Mutations
-- ---------------------------------------------------------------------------

/-- `Progress::resume`. -/
def Progress.resume (p : Progress) : Progress := { p with paused := false }

/-- `Progress::pause`. -/
def Progress.pause (p : Progress) : Progress := { p with paused := true }

/--
`Progress::maybe_update(n)`.
Returns `(updated_progress, need_update)`.
Both the matched update and the next_idx advance are modelled faithfully.
-/
def Progress.maybeUpdate (p : Progress) (n : Nat) : Progress × Bool :=
  let need_update := p.matched < n
  let p1 := if need_update then { p with matched := n, paused := false } else p
  let p2 := if p1.next_idx < n + 1 then { p1 with next_idx := n + 1 } else p1
  (p2, need_update)

/-- `Progress::optimistic_update`. -/
def Progress.optimisticUpdate (p : Progress) (n : Nat) : Progress :=
  { p with next_idx := n + 1 }

/-- `Progress::snapshot_failure`. -/
def Progress.snapshotFailure (p : Progress) : Progress :=
  { p with pending_snapshot := 0 }

/-- `Progress::is_paused`. -/
def Progress.isPaused (p : Progress) : Bool :=
  match p.state with
  | ProgressState.Probe     => p.paused
  | ProgressState.Replicate => p.ins_full
  | ProgressState.Snapshot  => true

/-- `Progress::is_snapshot_caught_up`. -/
def Progress.isSnapshotCaughtUp (p : Progress) : Bool :=
  p.state == ProgressState.Snapshot && p.matched >= p.pending_snapshot

/--
`Progress::maybe_decr_to(rejected, match_hint, request_snapshot)`.
Returns `(updated_progress, decremented)`.
In Lean with `Nat`, subtraction saturates at 0; the guard
`next_idx == 0 || next_idx - 1 != rejected` is equivalent to `next_idx != rejected + 1`
over `Nat` (see proof of PR26).
-/
def Progress.maybeDecrTo
    (p : Progress) (rejected match_hint request_snapshot : Nat) : Progress × Bool :=
  if p.state == ProgressState.Replicate then
    -- Stale if rejected ≤ matched (with special case for snapshot request)
    if rejected < p.matched
        || (rejected == p.matched && request_snapshot == INVALID_INDEX) then
      (p, false)
    else if request_snapshot == INVALID_INDEX then
      ({ p with next_idx := p.matched + 1 }, true)
    else
      ({ p with pending_request_snapshot := request_snapshot }, true)
  else
    -- Stale if next_idx - 1 ≠ rejected (and no snapshot request)
    if p.next_idx != rejected + 1 && request_snapshot == INVALID_INDEX then
      (p, false)
    else if request_snapshot == INVALID_INDEX then
      let ni := Nat.min rejected (match_hint + 1)
      let ni' := Nat.max ni (p.matched + 1)
      ({ p with next_idx := ni', paused := false }, true)
    else if p.pending_request_snapshot == INVALID_INDEX then
      ({ p with pending_request_snapshot := request_snapshot, paused := false }, true)
    else
      ({ p with paused := false }, true)

-- ---------------------------------------------------------------------------
-- PR1–PR3: State transitions set the correct state
-- ---------------------------------------------------------------------------

/-- PR1: `becomeReplicate` sets state to `Replicate`. -/
theorem PR1_becomeReplicate_state (p : Progress) :
    p.becomeReplicate.state = ProgressState.Replicate := by
  simp [Progress.becomeReplicate, Progress.resetState]

/-- PR2: `becomeProbe` sets state to `Probe`. -/
theorem PR2_becomeProbe_state (p : Progress) :
    p.becomeProbe.state = ProgressState.Probe := by
  simp only [Progress.becomeProbe, Progress.resetState]
  split <;> simp

/-- PR3: `becomeSnapshot` sets state to `Snapshot`. -/
theorem PR3_becomeSnapshot_state (p : Progress) (si : Nat) :
    (p.becomeSnapshot si).state = ProgressState.Snapshot := by
  simp [Progress.becomeSnapshot, Progress.resetState]

-- ---------------------------------------------------------------------------
-- PR4–PR6: State transitions set `next_idx` correctly
-- ---------------------------------------------------------------------------

/-- PR4: `becomeReplicate` sets next_idx to matched + 1. -/
theorem PR4_becomeReplicate_next_idx (p : Progress) :
    p.becomeReplicate.next_idx = p.matched + 1 := by
  simp [Progress.becomeReplicate, Progress.resetState]

/--
PR5: `becomeProbe` from `Snapshot` sets `next_idx = max(matched+1, pending_snapshot+1)`.
-/
theorem PR5_becomeProbe_next_idx_from_snapshot (p : Progress)
    (h : p.state = ProgressState.Snapshot) :
    p.becomeProbe.next_idx = Nat.max (p.matched + 1) (p.pending_snapshot + 1) := by
  simp [Progress.becomeProbe, Progress.resetState, h]

/-- PR6: `becomeProbe` from a non-Snapshot state sets `next_idx = matched + 1`. -/
theorem PR6_becomeProbe_next_idx_from_non_snapshot (p : Progress)
    (h : p.state ≠ ProgressState.Snapshot) :
    p.becomeProbe.next_idx = p.matched + 1 := by
  simp only [Progress.becomeProbe, Progress.resetState]
  have : ¬(p.state == ProgressState.Snapshot) := by simp [h]
  simp [this]

-- ---------------------------------------------------------------------------
-- PR7–PR9: State transitions clear `paused`
-- ---------------------------------------------------------------------------

/-- PR7: `becomeProbe` clears `paused`. -/
theorem PR7_becomeProbe_clears_pause (p : Progress) :
    p.becomeProbe.paused = false := by
  simp only [Progress.becomeProbe, Progress.resetState]
  split <;> simp

/-- PR8: `becomeReplicate` clears `paused`. -/
theorem PR8_becomeReplicate_clears_pause (p : Progress) :
    p.becomeReplicate.paused = false := by
  simp [Progress.becomeReplicate, Progress.resetState]

/-- PR9: `becomeSnapshot` clears `paused`. -/
theorem PR9_becomeSnapshot_clears_pause (p : Progress) (si : Nat) :
    (p.becomeSnapshot si).paused = false := by
  simp [Progress.becomeSnapshot, Progress.resetState]

-- ---------------------------------------------------------------------------
-- PR10: becomeSnapshot sets pending_snapshot
-- ---------------------------------------------------------------------------

/-- PR10: `becomeSnapshot(si)` sets `pending_snapshot = si`. -/
theorem PR10_becomeSnapshot_sets_pending (p : Progress) (si : Nat) :
    (p.becomeSnapshot si).pending_snapshot = si := by
  simp [Progress.becomeSnapshot, Progress.resetState]

-- ---------------------------------------------------------------------------
-- PR11–PR13: `isPaused` semantics
-- ---------------------------------------------------------------------------

/-- PR11: In `Probe` state, `isPaused = paused`. -/
theorem PR11_isPaused_probe (p : Progress) (h : p.state = ProgressState.Probe) :
    p.isPaused = p.paused := by
  simp [Progress.isPaused, h]

/-- PR12: In `Replicate` state, `isPaused = ins_full`. -/
theorem PR12_isPaused_replicate (p : Progress) (h : p.state = ProgressState.Replicate) :
    p.isPaused = p.ins_full := by
  simp [Progress.isPaused, h]

/-- PR13: In `Snapshot` state, `isPaused = true`. -/
theorem PR13_isPaused_snapshot (p : Progress) (h : p.state = ProgressState.Snapshot) :
    p.isPaused = true := by
  simp [Progress.isPaused, h]

-- ---------------------------------------------------------------------------
-- PR14–PR17: `maybeUpdate` semantics
-- ---------------------------------------------------------------------------

/-- PR14: When `n > matched`, `maybeUpdate` returns `true` and sets `matched = n`. -/
theorem PR14_maybeUpdate_true_updates_matched (p : Progress) (n : Nat)
    (h : p.matched < n) :
    (p.maybeUpdate n).2 = true ∧ (p.maybeUpdate n).1.matched = n := by
  unfold Progress.maybeUpdate
  simp only [h, ite_true]
  by_cases h2 : p.next_idx < n + 1 <;> simp [h2]

/-- PR15: When `n ≤ matched`, `maybeUpdate` returns `false` and leaves `matched` unchanged. -/
theorem PR15_maybeUpdate_false_preserves_matched (p : Progress) (n : Nat)
    (h : ¬(p.matched < n)) :
    (p.maybeUpdate n).2 = false ∧ (p.maybeUpdate n).1.matched = p.matched := by
  unfold Progress.maybeUpdate
  simp only [h, ite_false]
  by_cases h2 : p.next_idx < n + 1 <;> simp [h2]

/-- PR16: `maybeUpdate` always advances `next_idx` to `max(old_next_idx, n + 1)`. -/
theorem PR16_maybeUpdate_next_idx (p : Progress) (n : Nat) :
    (p.maybeUpdate n).1.next_idx = Nat.max p.next_idx (n + 1) := by
  unfold Progress.maybeUpdate
  by_cases h1 : p.matched < n <;> by_cases h2 : p.next_idx < n + 1 <;>
    simp [h1, h2, Nat.max_def] <;> omega

/-- PR17: When `n > matched`, `maybeUpdate` clears `paused` (calls `resume`). -/
theorem PR17_maybeUpdate_resume (p : Progress) (n : Nat)
    (h : p.matched < n) :
    (p.maybeUpdate n).1.paused = false := by
  unfold Progress.maybeUpdate
  simp only [h, ite_true]
  by_cases h2 : p.next_idx < n + 1 <;> simp [h2]

-- ---------------------------------------------------------------------------
-- PR18–PR20: Invariant preservation
-- ---------------------------------------------------------------------------

/-- PR18: `becomeProbe` preserves the well-formedness invariant. -/
theorem PR18_becomeProbe_preserves_wf (p : Progress) :
    p.becomeProbe.wf := by
  simp only [Progress.becomeProbe, Progress.resetState, Progress.wf]
  split
  · simp [Nat.le_max_left]
  · simp

/-- PR19: `becomeReplicate` preserves the well-formedness invariant. -/
theorem PR19_becomeReplicate_preserves_wf (p : Progress) :
    p.becomeReplicate.wf := by
  simp [Progress.becomeReplicate, Progress.resetState, Progress.wf]

/-- PR20: `maybeUpdate` preserves the well-formedness invariant. -/
theorem PR20_maybeUpdate_preserves_wf (p : Progress) (n : Nat) (hw : p.wf) :
    (p.maybeUpdate n).1.wf := by
  unfold Progress.maybeUpdate
  simp only [Progress.wf] at *
  by_cases h1 : p.matched < n <;> by_cases h2 : p.next_idx < n + 1 <;>
    simp [h1, h2] <;> omega

-- ---------------------------------------------------------------------------
-- PR21: `isSnapshotCaughtUp` semantics
-- ---------------------------------------------------------------------------

/-- PR21: `isSnapshotCaughtUp` iff in Snapshot state and matched ≥ pending_snapshot. -/
theorem PR21_isSnapshotCaughtUp_iff (p : Progress) :
    p.isSnapshotCaughtUp = true ↔
    p.state = ProgressState.Snapshot ∧ p.matched ≥ p.pending_snapshot := by
  simp [Progress.isSnapshotCaughtUp, Bool.and_eq_true, beq_iff_eq, ge_iff_le]

-- ---------------------------------------------------------------------------
-- PR22: `mk_new` produces a well-formed Progress (when next_idx ≥ 1)
-- ---------------------------------------------------------------------------

/-- PR22: `mk_new(next_idx)` is well-formed when `next_idx ≥ 1`. -/
theorem PR22_mk_new_wf (next_idx : Nat) (h : 1 ≤ next_idx) :
    (Progress.mk_new next_idx).wf := by
  simp [Progress.mk_new, Progress.wf, h]

-- ---------------------------------------------------------------------------
-- PR23–PR25: State transitions preserve `matched`
-- ---------------------------------------------------------------------------

/-- PR23: `becomeSnapshot` preserves `matched`. -/
theorem PR23_becomeSnapshot_preserves_matched (p : Progress) (si : Nat) :
    (p.becomeSnapshot si).matched = p.matched := by
  simp [Progress.becomeSnapshot, Progress.resetState]

/-- PR24: `becomeProbe` preserves `matched`. -/
theorem PR24_becomeProbe_preserves_matched (p : Progress) :
    p.becomeProbe.matched = p.matched := by
  simp only [Progress.becomeProbe, Progress.resetState]
  split <;> simp

/-- PR25: `becomeReplicate` preserves `matched`. -/
theorem PR25_becomeReplicate_preserves_matched (p : Progress) :
    p.becomeReplicate.matched = p.matched := by
  simp [Progress.becomeReplicate, Progress.resetState]

-- ---------------------------------------------------------------------------
-- PR26: Equivalence of the next_idx guard in `maybeDecrTo`
-- ---------------------------------------------------------------------------

/--
PR26: The Rust guard `next_idx == 0 || next_idx - 1 != rejected` is equivalent
to `next_idx != rejected + 1` over `Nat`.

In Rust this guard prevents underflow on u64; in our `Nat` model the same
condition arises naturally since `Nat.sub` saturates at 0:
  - `next_idx = 0`:  `0 - 1 = 0`, so `0 != rejected` unless `rejected = 0`.
    But the guard is `True` by the first disjunct (`next_idx == 0`), which
    equals `next_idx != rejected + 1` because `rejected + 1 ≥ 1 > 0`.
  - `next_idx > 0`: `next_idx - 1 != rejected` iff `next_idx != rejected + 1`. ✓
-/
theorem PR26_decr_guard_equiv (next_idx rejected : Nat) :
    (next_idx == 0 || next_idx - 1 != rejected) = (next_idx != rejected + 1) := by
  apply Bool.eq_iff_iff.mpr
  simp only [Bool.or_eq_true, beq_iff_eq, bne_iff_ne, ne_eq]
  omega

-- ---------------------------------------------------------------------------
-- PR27–PR28: `maybeDecrTo` in Replicate state
-- ---------------------------------------------------------------------------

/--
PR27: In `Replicate` state, `maybeDecrTo` returns `false` when the rejection is stale
(`rejected < matched` or `rejected = matched` with no snapshot request).
-/
theorem PR27_maybeDecrTo_replicate_stale (p : Progress)
    (rejected match_hint request_snapshot : Nat)
    (hs : p.state = ProgressState.Replicate)
    (hstale : rejected < p.matched ∨
              (rejected = p.matched ∧ request_snapshot = INVALID_INDEX)) :
    (p.maybeDecrTo rejected match_hint request_snapshot).2 = false := by
  simp only [Progress.maybeDecrTo, hs, beq_self_eq_true, ite_true]
  rcases hstale with h | ⟨heq, hrsn⟩
  · simp [h]
  · simp [heq, hrsn, INVALID_INDEX]

/--
PR28: In `Replicate` state, when `rejected > matched`, `maybeDecrTo` with no snapshot
request sets `next_idx = matched + 1` and returns `true`.
-/
theorem PR28_maybeDecrTo_replicate_non_stale_no_snapshot (p : Progress)
    (rejected match_hint : Nat)
    (hs : p.state = ProgressState.Replicate)
    (hgt : p.matched < rejected) :
    (p.maybeDecrTo rejected match_hint INVALID_INDEX).1.next_idx = p.matched + 1 ∧
    (p.maybeDecrTo rejected match_hint INVALID_INDEX).2 = true := by
  have hnlt : ¬(rejected < p.matched) := by omega
  have hne : ¬(rejected = p.matched) := by omega
  simp [Progress.maybeDecrTo, hs, INVALID_INDEX, hnlt, hne]

-- ---------------------------------------------------------------------------
-- PR29: `becomeSnapshot` preserves `wf`
-- ---------------------------------------------------------------------------

/-- PR29: `becomeSnapshot` preserves the well-formedness invariant. -/
theorem PR29_becomeSnapshot_preserves_wf (p : Progress) (si : Nat) (hw : p.wf) :
    (p.becomeSnapshot si).wf := by
  simp [Progress.becomeSnapshot, Progress.resetState, Progress.wf]
  exact hw

-- ---------------------------------------------------------------------------
-- PR30: `resume` and `pause` do not change state-machine fields
-- ---------------------------------------------------------------------------

/-- PR30a: `resume` does not change `matched`, `next_idx`, `state`, or `pending_snapshot`. -/
theorem PR30a_resume_preserves_core (p : Progress) :
    p.resume.matched = p.matched ∧
    p.resume.next_idx = p.next_idx ∧
    p.resume.state = p.state ∧
    p.resume.pending_snapshot = p.pending_snapshot := by
  simp [Progress.resume]

/-- PR30b: `pause` preserves `wf`. -/
theorem PR30b_pause_preserves_wf (p : Progress) (hw : p.wf) :
    p.pause.wf := by
  simp [Progress.pause, Progress.wf]
  exact hw

-- ---------------------------------------------------------------------------
-- PR31–PR33: Non-Replicate state `maybeDecrTo` behaviour
-- ---------------------------------------------------------------------------

/-- Helper: `p.state ≠ Replicate → (p.state == Replicate) = false`. -/
private theorem beq_replicate_false_of_ne (p : Progress)
    (h : p.state ≠ ProgressState.Replicate) :
    (p.state == ProgressState.Replicate) = false :=
  beq_eq_false_iff_ne.mpr h

/-- PR31: In non-Replicate state, a stale rejection (next_idx ≠ rejected + 1) with no
    snapshot request leaves the progress unchanged and returns false. -/
theorem PR31_maybeDecrTo_non_replicate_stale (p : Progress)
    (rejected match_hint : Nat)
    (hs : p.state ≠ ProgressState.Replicate)
    (hstale : p.next_idx ≠ rejected + 1) :
    p.maybeDecrTo rejected match_hint INVALID_INDEX = (p, false) := by
  have hbeq : (p.state == ProgressState.Replicate) = false :=
    beq_replicate_false_of_ne p hs
  simp only [Progress.maybeDecrTo, hbeq, ite_false, INVALID_INDEX]
  have hbne : (p.next_idx != rejected + 1) = true := by simp [bne_iff_ne, hstale]
  simp [hbne]

/-- PR32: In non-Replicate state, when the rejection is fresh (next_idx = rejected + 1)
    and no snapshot is requested, `maybeDecrTo` decrements `next_idx` to
    `max(min(rejected, match_hint + 1), matched + 1)` and returns true. -/
theorem PR32_maybeDecrTo_non_replicate_decr (p : Progress)
    (rejected match_hint : Nat)
    (hs : p.state ≠ ProgressState.Replicate)
    (hfresh : p.next_idx = rejected + 1) :
    let ni' := Nat.max (Nat.min rejected (match_hint + 1)) (p.matched + 1)
    (p.maybeDecrTo rejected match_hint INVALID_INDEX).2 = true ∧
    (p.maybeDecrTo rejected match_hint INVALID_INDEX).1.next_idx = ni' := by
  have hbeq : (p.state == ProgressState.Replicate) = false :=
    beq_replicate_false_of_ne p hs
  simp only [Progress.maybeDecrTo, hbeq, ite_false, INVALID_INDEX]
  have hbne : (p.next_idx != rejected + 1) = false := by
    simp [bne_iff_ne, hfresh]
  simp only [hbne, false_and, ite_false, beq_self_eq_true, ite_true]
  simp

/-- PR33: `maybeDecrTo` preserves the well-formedness invariant (`matched + 1 ≤ next_idx`)
    in all states and for all argument values. -/
theorem PR33_maybeDecrTo_preserves_wf (p : Progress)
    (rejected match_hint request_snapshot : Nat) (hw : p.wf) :
    (p.maybeDecrTo rejected match_hint request_snapshot).1.wf := by
  by_cases hrep : p.state = ProgressState.Replicate
  · -- Replicate branch
    simp only [Progress.maybeDecrTo, hrep, beq_self_eq_true, ite_true]
    by_cases hstale : rejected < p.matched ||
        (rejected == p.matched && request_snapshot == INVALID_INDEX)
    · simp only [hstale, ite_true]; exact hw
    · simp only [hstale, ite_false]
      by_cases hnosnap : request_snapshot == INVALID_INDEX
      · simp only [hnosnap, ite_true]; simp [Progress.wf]
      · simp only [hnosnap, ite_false]; exact hw
  · -- Probe / Snapshot branch
    have hbeq : (p.state == ProgressState.Replicate) = false :=
      beq_replicate_false_of_ne p hrep
    simp only [Progress.maybeDecrTo, hbeq, ite_false]
    by_cases hguard : p.next_idx != rejected + 1 && request_snapshot == INVALID_INDEX
    · simp only [hguard, ite_true]; exact hw
    · simp only [hguard, ite_false]
      by_cases hnosnap : request_snapshot == INVALID_INDEX
      · -- decrement path: next_idx := max(min(rejected, match_hint+1), matched+1)
        simp only [hnosnap, ite_true]; simp only [Progress.wf]
        exact Nat.le_max_right _ _
      · simp only [hnosnap, ite_false]
        by_cases hpend : p.pending_request_snapshot == INVALID_INDEX
        · simp only [hpend, ite_true]; exact hw
        · simp only [hpend, ite_false]; exact hw

-- ---------------------------------------------------------------------------
-- PR34–PR35: `optimisticUpdate` semantics and wf preservation
-- ---------------------------------------------------------------------------

/-- PR34: `optimisticUpdate` sets `next_idx` to `n + 1` and leaves all other
    fields unchanged. -/
theorem PR34_optimisticUpdate_semantics (p : Progress) (n : Nat) :
    (p.optimisticUpdate n).next_idx = n + 1 ∧
    (p.optimisticUpdate n).matched = p.matched ∧
    (p.optimisticUpdate n).state = p.state := by
  simp [Progress.optimisticUpdate]

/-- PR35: `optimisticUpdate n` preserves wf when `p.matched ≤ n`.
    In practice, `n` is the index of the last replicated entry, so `matched ≤ n`
    holds by the replication protocol. -/
theorem PR35_optimisticUpdate_preserves_wf (p : Progress) (n : Nat)
    (hn : p.matched ≤ n) :
    (p.optimisticUpdate n).wf := by
  simp [Progress.optimisticUpdate, Progress.wf]
  omega

end FVSquad.Progress
