import FVSquad.Progress
import FVSquad.HasQuorum
import FVSquad.ProgressTracker
import FVSquad.QuorumRecentlyActive

/-!
# Formal Specification: `ProgressTracker` as a Composed Progress Set (PS1–PS8)

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

This file formalises the `ProgressTracker` as a *progress set*: a pairing of a
voter list with a per-peer progress function.  It proves eight key properties of
`quorum_recently_active` as a composed operation.

## Source

`src/tracker.rs` — `ProgressTracker::quorum_recently_active`.

## Abstract Model

```lean
structure ProgressSet where
  voters   : List Nat
  progress : Nat → Progress
```

The active set for `perspectiveOf` is:

```lean
def activeSet (ps : ProgressSet) (perspectiveOf : Nat) : List Nat :=
  ps.voters.filter (fun id => id == perspectiveOf || (ps.progress id).recent_active)
```

`quorumRecentlyActive` calls `hasQuorum` on this set.

## Theorem Index

| ID  | Name                                  | Description                                           |
|-----|---------------------------------------|-------------------------------------------------------|
| PS1 | `activeSet_contains_self`             | perspectiveOf is always in the active set             |
| PS2 | `activeSet_subset_voters`             | Active set ⊆ voters                                   |
| PS3 | `quorumRecentlyActive_monotone`       | Larger active set → quorum preserved                  |
| PS4 | `resetActive_idempotent`              | resetActive is idempotent                             |
| PS5 | `activeSet_after_reset`               | After reset, only perspectiveOf is active             |
| PS6 | `quorumRecentlyActive_nonempty`       | Quorum implies non-empty active set                   |
| PS7 | `resetActive_preserves_all_wf`        | all_wf invariant preserved by resetActive             |
| PS8 | `quorumRecentlyActive_iff`            | Definitional biconditional for quorumRecentlyActive   |

## Abstractions

- `voters : List Nat` models `HashMap<u64, Progress>` keys (no uniqueness enforced).
- `progress : Nat → Progress` is a total function (undefined entries use default values
  but are not accessed in practice since we restrict to voters).
- The side-effects of `quorum_recently_active` (flag resets) are modelled separately
  as `resetActive`, which is not part of the boolean result.
- `u64` → `Nat`; no overflow.

**Sorry count**: 0.  All 8 theorems proved without `sorry`.

> 🔬 Generated by Lean Squad automated formal verification (Run 122).
-/

namespace FVSquad.ProgressSet

open FVSquad.Progress
open FVSquad.ProgressTracker

-- ---------------------------------------------------------------------------
-- Types
-- ---------------------------------------------------------------------------

/-- Abstract progress set: a voter list and a progress function.

    Models `ProgressTracker` (voters + per-peer Progress map).
    Key uniqueness (Rust's `HashMap`) is not enforced here; proofs work for
    any `List Nat` of voter IDs. -/
structure ProgressSet where
  voters   : List Nat
  progress : Nat → Progress

-- ---------------------------------------------------------------------------
-- Core operations
-- ---------------------------------------------------------------------------

/-- The set of recently-active voters from `perspectiveOf`'s perspective.

    The leader (`perspectiveOf`) is **always** included; all other peers are
    included only if `recent_active = true`.

    Models the inner loop of `quorum_recently_active`:
    ```rust
    if *id == perspective_of { active.insert(*id); }
    else if pr.recent_active { active.insert(*id); }
    ``` -/
def activeSet (ps : ProgressSet) (perspectiveOf : Nat) : List Nat :=
  ps.voters.filter (fun id => id == perspectiveOf || (ps.progress id).recent_active)

/-- Reset the `recent_active` flags:
    - `perspectiveOf` → `true` (leader stays active).
    - All other IDs → `false` (heartbeat acknowledgements expire).

    Models the side-effect of `quorum_recently_active`. -/
def resetActive (ps : ProgressSet) (perspectiveOf : Nat) : ProgressSet :=
  { ps with progress := fun id =>
      if id == perspectiveOf then
        { (ps.progress id) with recent_active := true }
      else
        { (ps.progress id) with recent_active := false } }

/-- `quorumRecentlyActive ps perspectiveOf` returns `true` iff the recently-active
    voter set forms a majority quorum.

    Delegates to `hasQuorum` (from `HasQuorum.lean`). -/
def quorumRecentlyActive (ps : ProgressSet) (perspectiveOf : Nat) : Bool :=
  hasQuorum ps.voters (fun id => (activeSet ps perspectiveOf).contains id)

-- ---------------------------------------------------------------------------
-- Auxiliary lemmas
-- ---------------------------------------------------------------------------

-- filter_subset: membership in filter implies membership in original
private theorem filter_subset {α : Type} (l : List α) (p : α → Bool) (x : α)
    (h : x ∈ l.filter p) : x ∈ l :=
  (List.mem_filter.mp h).1

-- ---------------------------------------------------------------------------
-- PS1: Self inclusion
-- ---------------------------------------------------------------------------

/-- **PS1** — `perspectiveOf` is always in `activeSet`.

    If `perspectiveOf` is in the voter list, it appears in the active set
    regardless of its `recent_active` flag, because the filter condition
    `id == perspectiveOf` is always satisfied for `id = perspectiveOf`.

    **Proof**: `List.mem_filter.mpr` requires membership in voters (given) and
    filter predicate truth.  `id == perspectiveOf` at `id = perspectiveOf` is
    `Nat.beq_refl`. -/
theorem PS1_activeSet_contains_self (ps : ProgressSet) (perspectiveOf : Nat)
    (hmem : perspectiveOf ∈ ps.voters) :
    perspectiveOf ∈ activeSet ps perspectiveOf := by
  simp only [activeSet, List.mem_filter]
  exact ⟨hmem, by simp [Nat.beq_refl]⟩

-- ---------------------------------------------------------------------------
-- PS2: Active set ⊆ voters
-- ---------------------------------------------------------------------------

/-- **PS2** — Every member of `activeSet` is a voter.

    `activeSet` is defined as a `List.filter` on `voters`, so every element of
    `activeSet` is also in `voters`. -/
theorem PS2_activeSet_subset_voters (ps : ProgressSet) (perspectiveOf : Nat)
    (x : Nat) (hx : x ∈ activeSet ps perspectiveOf) :
    x ∈ ps.voters :=
  filter_subset ps.voters _ x hx

-- ---------------------------------------------------------------------------
-- PS3: Monotonicity
-- ---------------------------------------------------------------------------

/-- **PS3** — If the active set of `ps2` covers at least as many voters as `ps1`,
    then `quorumRecentlyActive` is preserved.

    **Proof**: `hasQuorum_monotone` (HQ5) requires that whenever `s₁ v = true`,
    also `s₂ v = true`.  We instantiate this with the `contains` predicates of
    `activeSet ps1` and `activeSet ps2`. -/
theorem PS3_quorumRecentlyActive_monotone (ps1 ps2 : ProgressSet)
    (perspectiveOf : Nat)
    (hvoters : ps1.voters = ps2.voters)
    (hmono : ∀ id, id ∈ activeSet ps1 perspectiveOf → id ∈ activeSet ps2 perspectiveOf)
    (hq : quorumRecentlyActive ps1 perspectiveOf = true) :
    quorumRecentlyActive ps2 perspectiveOf = true := by
  simp only [quorumRecentlyActive] at *
  have hmono' : ∀ v : Nat, (activeSet ps1 perspectiveOf).contains v = true →
      (activeSet ps2 perspectiveOf).contains v = true := by
    intro v hv
    rw [List.contains_iff_mem] at hv ⊢
    exact hmono v hv
  calc hasQuorum ps2.voters (fun id => (activeSet ps2 perspectiveOf).contains id)
      = hasQuorum ps1.voters (fun id => (activeSet ps2 perspectiveOf).contains id) := by
          rw [← hvoters]
    _ = true := hasQuorum_monotone _ _ _ hmono' hq

-- ---------------------------------------------------------------------------
-- PS4: resetActive is idempotent
-- ---------------------------------------------------------------------------

/-- **PS4** — Applying `resetActive` twice has the same effect as applying it once.

    After one call, `perspectiveOf.recent_active = true` and every other id has
    `recent_active = false`.  Applying `resetActive` again produces the same result
    because:
    - `perspectiveOf`: `true → true` (identity).
    - Others: `false → false` (identity). -/
theorem PS4_resetActive_idempotent (ps : ProgressSet) (perspectiveOf : Nat) :
    resetActive (resetActive ps perspectiveOf) perspectiveOf =
    resetActive ps perspectiveOf := by
  simp only [resetActive]
  congr 1
  funext id
  by_cases h : id = perspectiveOf
  · subst h; simp
  · simp [h]

-- ---------------------------------------------------------------------------
-- PS5: Active set after reset is singleton
-- ---------------------------------------------------------------------------

/-- **PS5** — After `resetActive`, only `perspectiveOf` is in the active set.

    For any `id ≠ perspectiveOf`, `resetActive` sets `recent_active = false`,
    so the filter predicate `id == p || recent_active` reduces to `id == p`.
    Therefore `activeSet (resetActive ps p) p = voters.filter (· == p)`. -/
theorem PS5_activeSet_after_reset (ps : ProgressSet) (perspectiveOf : Nat) :
    activeSet (resetActive ps perspectiveOf) perspectiveOf =
    ps.voters.filter (fun id => id == perspectiveOf) := by
  simp only [activeSet, resetActive]
  congr 1
  funext id
  by_cases h : id = perspectiveOf
  · subst h; simp
  · simp [h]

-- ---------------------------------------------------------------------------
-- PS6: Quorum implies non-empty active set
-- ---------------------------------------------------------------------------

/-- **PS6** — If `quorumRecentlyActive` returns `true` and the voter list is non-empty,
    then `activeSet` is non-empty.

    **Proof**: `hasQuorum voters s = true` with non-empty `voters` implies
    `overlapCount ≥ majority ≥ 1`, so some voter satisfies `s`.  Since `s v = true`
    means `v ∈ activeSet`, the active set is non-empty.

    Note: empty voter lists give vacuous quorum (`hasQuorum [] _ = true`) with
    `activeSet = []`, so the non-empty voter assumption is necessary. -/
theorem PS6_quorumRecentlyActive_nonempty (ps : ProgressSet) (perspectiveOf : Nat)
    (hvoters : ps.voters ≠ [])
    (hq : quorumRecentlyActive ps perspectiveOf = true) :
    activeSet ps perspectiveOf ≠ [] := by
  intro hempty
  simp only [quorumRecentlyActive] at hq
  have hzero : overlapCount ps.voters (fun id => (activeSet ps perspectiveOf).contains id) = 0 :=
    overlapCount_none_in _ _ (fun v _ => by simp [hempty])
  have hfq : hasQuorum ps.voters (fun id => (activeSet ps perspectiveOf).contains id) = false := by
    cases hq' : hasQuorum ps.voters (fun id => (activeSet ps perspectiveOf).contains id) with
    | false => rfl
    | true =>
      exfalso
      rw [hasQuorum_iff_overlap] at hq'
      cases hq' with
      | inl h => exact absurd h hvoters
      | inr h =>
        cases hps : ps.voters with
        | nil => exact absurd hps hvoters
        | cons v vs =>
          rw [hps] at h hzero
          simp only [majority] at h
          omega
  rw [hfq] at hq; exact absurd hq (by decide)

-- ---------------------------------------------------------------------------
-- PS7: resetActive preserves all_wf
-- ---------------------------------------------------------------------------

/-- **PS7** — The `all_wf` invariant (`∀ p, p.wf ↔ p.matched + 1 ≤ p.next_idx`) is
    preserved by `resetActive`.

    `resetActive` only modifies the `recent_active` boolean field, which plays no role
    in the `wf` predicate (`matched + 1 ≤ next_idx`).  Therefore, if the original
    progress entries are well-formed, the reset entries are well-formed too.

    We model `all_wf` here as: for all IDs in voters, `(ps.progress id).wf`. -/
def all_wf_fn (ps : ProgressSet) : Prop :=
  ∀ id ∈ ps.voters, (ps.progress id).wf

theorem PS7_resetActive_preserves_all_wf (ps : ProgressSet) (perspectiveOf : Nat)
    (h : all_wf_fn ps) :
    all_wf_fn (resetActive ps perspectiveOf) := by
  intro id hmem
  simp only [all_wf_fn] at h
  have hwf := h id (by simpa [resetActive] using hmem)
  simp only [resetActive, Progress.wf] at *
  by_cases heq : id = perspectiveOf
  · subst heq; simp [hwf]
  · simp [heq, hwf]

-- ---------------------------------------------------------------------------
-- PS8: Definitional biconditional
-- ---------------------------------------------------------------------------

/-- **PS8** — `quorumRecentlyActive ps p = true` iff `hasQuorum` holds for the
    active set membership predicate.

    This is definitional: `quorumRecentlyActive` is defined as exactly that
    `hasQuorum` call, so the biconditional is proved by `rfl` + `iff_self`. -/
theorem PS8_quorumRecentlyActive_iff (ps : ProgressSet) (perspectiveOf : Nat) :
    quorumRecentlyActive ps perspectiveOf = true ↔
    hasQuorum ps.voters (fun id => (activeSet ps perspectiveOf).contains id) = true := by
  simp [quorumRecentlyActive]

-- ---------------------------------------------------------------------------
-- Evaluation examples
-- ---------------------------------------------------------------------------

section Eval

-- Example 1: 3-voter cluster, all active
-- PS1: leader (0) is in activeSet
#eval
  let voters := [0, 1, 2]
  let prog := fun (id : Nat) => { Progress.mk_new 1 with recent_active := true }
  let ps : ProgressSet := ⟨voters, prog⟩
  activeSet ps 0  -- expected: [0, 1, 2]

-- Example 2: 3-voter cluster, only leader (0) active
#eval
  let voters := [0, 1, 2]
  let prog := fun (id : Nat) => { Progress.mk_new 1 with recent_active := (id == 0) }
  let ps : ProgressSet := ⟨voters, prog⟩
  (activeSet ps 0, quorumRecentlyActive ps 0)  -- active = [0], quorum = false (1/3 < majority)

-- Example 3: 3-voter cluster, leader + 1 other active → quorum
#eval
  let voters := [0, 1, 2]
  let prog := fun (id : Nat) => { Progress.mk_new 1 with recent_active := (id == 0 || id == 1) }
  let ps : ProgressSet := ⟨voters, prog⟩
  (activeSet ps 0, quorumRecentlyActive ps 0)  -- active = [0, 1], quorum = true (2/3 ≥ majority)

-- Example 4: PS5 — after reset, only leader is active
#eval
  let voters := [0, 1, 2]
  let prog := fun (id : Nat) => { Progress.mk_new 1 with recent_active := true }
  let ps : ProgressSet := ⟨voters, prog⟩
  activeSet (resetActive ps 0) 0  -- expected: [0]

-- Example 5: PS4 — idempotency of resetActive
#eval
  let voters := [0, 1, 2]
  let prog := fun (id : Nat) => { Progress.mk_new 1 with recent_active := true }
  let ps : ProgressSet := ⟨voters, prog⟩
  let ps1 := resetActive ps 0
  let ps2 := resetActive ps1 0
  -- active sets should be equal
  (activeSet ps1 0, activeSet ps2 0)  -- expected: ([0], [0])

end Eval

end FVSquad.ProgressSet
