import FVSquad.Progress

/-!
# Formal Specification: `ProgressTracker` — Multi-Peer Progress Invariant

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

Formalises the per-peer invariant lifting from `src/tracker.rs`.

`ProgressTracker` maintains a map from peer IDs to `Progress` records.
This file proves that the well-formedness invariant
`∀ peer p, (peer, p) ∈ tracker.progress → p.wf`
is preserved by every tracker-level operation:

- **`removePeer`** (models `apply_conf` Remove): trivial by subset
- **`insertPeer`** (models `apply_conf` Add): new peer uses `Progress.mk_new` which is wf
- **`updatePeer`** (models per-peer state transitions): delegates to per-peer wf theorems
- **`applyChanges`** (models the full `apply_conf` loop): proved by induction over the
  change list using PT1–PT3
- **Per-peer lift** (PT7–PT12): each of the six Progress state-transition operations
  (`becomeProbe`, `becomeReplicate`, `becomeSnapshot`, `maybeUpdate`,
  `maybeDecrTo`, `optimisticUpdate`) preserves the tracker-level invariant

This closes the "Progress ↔ ProgressTracker integration" gap identified in
`formal-verification/CRITIQUE.md` by lifting PR1–PR35 from `Progress.lean`
to the multi-peer level.

Source: `src/tracker.rs`  (see `ProgressTracker::apply_conf`, `ProgressTracker::get_mut`)
Progress model: `FVSquad/Progress.lean`

**Abstractions**:
- The `ProgressTracker` is modelled as a bare association list `List (Nat × Progress)`.
  Key uniqueness (enforced by the Rust `HashMap`) is not required for the wf proofs.
- `apply_conf`'s voter-configuration update (`self.conf = conf`) is omitted — only the
  progress-map changes are modelled.
- The `recent_active = true` flag set on newly-added peers (a metadata detail) is omitted.

**Sorry count**: 0.  All 15 theorems are proved without `sorry`.

> 🔬 Generated by Lean Squad automated formal verification (Run 96).
-/

namespace FVSquad.ProgressTracker

open FVSquad.Progress

-- ---------------------------------------------------------------------------
-- Types
-- ---------------------------------------------------------------------------

/-- An abstract progress map: association list of peer-id → Progress. -/
abbrev ProgressMap := List (Nat × Progress)

/-- The kind of change in `apply_conf`. -/
inductive ChangeType where
  | Add    : ChangeType
  | Remove : ChangeType

-- ---------------------------------------------------------------------------
-- Core operations
-- ---------------------------------------------------------------------------

/-- Remove a peer from the progress map.  Models `MapChangeType::Remove`. -/
def removePeer (pm : ProgressMap) (id : Nat) : ProgressMap :=
  pm.filter (fun pair => pair.1 != id)

/-- Insert (or replace) a peer in the progress map.  Models `MapChangeType::Add`. -/
def insertPeer (pm : ProgressMap) (id : Nat) (p : Progress) : ProgressMap :=
  (id, p) :: removePeer pm id

/-- Apply a function to every progress entry for a given peer.  Used to model
    in-place mutations such as `becomeProbe`, `maybeUpdate`, etc. -/
def updatePeer (pm : ProgressMap) (id : Nat) (f : Progress → Progress) : ProgressMap :=
  pm.map (fun pair => if pair.1 = id then (pair.1, f pair.2) else pair)

/-- Apply a single `(id, ChangeType)` change to the progress map. -/
def applyChange (pm : ProgressMap) (id : Nat) (ct : ChangeType) (next_idx : Nat) : ProgressMap :=
  match ct with
  | ChangeType.Add    => insertPeer pm id (Progress.mk_new next_idx)
  | ChangeType.Remove => removePeer pm id

/-- Apply a list of `(id, ChangeType)` changes in order.
    Models the `for (id, change_type) in changes` loop inside `apply_conf`. -/
def applyChanges (pm : ProgressMap) (changes : List (Nat × ChangeType)) (next_idx : Nat) :
    ProgressMap :=
  changes.foldl (fun acc ⟨id, ct⟩ => applyChange acc id ct next_idx) pm

-- ---------------------------------------------------------------------------
-- Well-formedness invariant
-- ---------------------------------------------------------------------------

/-- The tracker-level wf invariant: every peer's `Progress` is wf. -/
def all_wf (pm : ProgressMap) : Prop :=
  ∀ id p, (id, p) ∈ pm → p.wf

-- ---------------------------------------------------------------------------
-- Auxiliary: filter preserves all_wf
-- ---------------------------------------------------------------------------

/-- Filtering any subset of a wf map yields a wf map. -/
private theorem filter_preserves_all_wf (pm : ProgressMap) (pred : Nat × Progress → Bool)
    (h : all_wf pm) : all_wf (pm.filter pred) := by
  intro id p hmem
  rw [List.mem_filter] at hmem
  exact h id p hmem.1

-- ---------------------------------------------------------------------------
-- PT1: removePeer preserves all_wf
-- ---------------------------------------------------------------------------

/-- PT1: Removing a peer from a wf tracker yields a wf tracker.

    Proof: `removePeer` is a filter; membership in the result implies membership
    in the original list, which satisfies `all_wf` by hypothesis. -/
theorem PT1_removePeer_preserves_all_wf (pm : ProgressMap) (id : Nat)
    (h : all_wf pm) : all_wf (removePeer pm id) :=
  filter_preserves_all_wf pm (fun pair => pair.1 != id) h

-- ---------------------------------------------------------------------------
-- PT2: insertPeer preserves all_wf when the new entry is wf
-- ---------------------------------------------------------------------------

/-- PT2: Inserting a wf `Progress` record preserves the tracker invariant.

    Proof: membership in `(id, p) :: filter ...` is either the new head or an element
    of the filtered tail; in both cases wf holds — by `hp` and `h` respectively. -/
theorem PT2_insertPeer_preserves_all_wf (pm : ProgressMap) (id : Nat) (p : Progress)
    (h : all_wf pm) (hp : p.wf) : all_wf (insertPeer pm id p) := by
  intro i q hmem
  unfold insertPeer at hmem
  rw [List.mem_cons] at hmem
  cases hmem with
  | inl heq =>
    have := Prod.mk.inj heq
    rw [this.2]; exact hp
  | inr hmem =>
    exact filter_preserves_all_wf pm (fun pair => pair.1 != id) h i q hmem

-- ---------------------------------------------------------------------------
-- PT3: updatePeer preserves all_wf when the update function preserves wf
-- ---------------------------------------------------------------------------

/-- PT3: Updating a peer's progress with a wf-preserving function preserves the
    tracker invariant.

    Proof: membership in `pm.map g` gives `(i, q) = g (j, p)` for some `(j, p) ∈ pm`.
    In the case `j = id`, `q = f p`; wf holds by `hf` applied to `h j p hjp`.
    In the case `j ≠ id`, `q = p`; wf holds directly from `h`. -/
theorem PT3_updatePeer_preserves_all_wf (pm : ProgressMap) (id : Nat) (f : Progress → Progress)
    (h : all_wf pm) (hf : ∀ p, p.wf → (f p).wf) : all_wf (updatePeer pm id f) := by
  intro i q hmem
  unfold updatePeer at hmem
  rw [List.mem_map] at hmem
  obtain ⟨⟨j, p⟩, hjp, heq⟩ := hmem
  simp only at heq
  by_cases hji : j = id
  · simp only [hji, ite_true] at heq
    have := Prod.mk.inj heq
    rw [← this.2]
    exact hf p (h j p hjp)
  · simp only [hji, ite_false] at heq
    have := Prod.mk.inj heq
    rw [← this.2]
    exact h j p hjp

-- ---------------------------------------------------------------------------
-- PT4: applyChange preserves all_wf
-- ---------------------------------------------------------------------------

/-- PT4: A single `apply_conf` change preserves the tracker-level wf invariant,
    provided the `next_idx` for new peers satisfies `1 ≤ next_idx`.

    - **Add**: delegates to PT2 + PR22 (`Progress.mk_new next_idx` is wf when `1 ≤ next_idx`)
    - **Remove**: delegates to PT1. -/
theorem PT4_applyChange_preserves_all_wf (pm : ProgressMap) (id : Nat) (ct : ChangeType)
    (next_idx : Nat) (hnext : 1 ≤ next_idx) (h : all_wf pm) :
    all_wf (applyChange pm id ct next_idx) := by
  unfold applyChange
  match ct with
  | ChangeType.Add =>
    exact PT2_insertPeer_preserves_all_wf pm id (Progress.mk_new next_idx) h
      (PR22_mk_new_wf next_idx hnext)
  | ChangeType.Remove =>
    exact PT1_removePeer_preserves_all_wf pm id h

-- ---------------------------------------------------------------------------
-- PT5: applyChanges preserves all_wf (inductive over the change list)
-- ---------------------------------------------------------------------------

/-- PT5: Applying a sequence of `apply_conf` changes preserves the tracker wf invariant.

    Proof: by induction over `changes`; the base case is trivial, and the inductive step
    uses PT4 (which covers both Add and Remove). -/
theorem PT5_applyChanges_preserves_all_wf (pm : ProgressMap)
    (changes : List (Nat × ChangeType)) (next_idx : Nat) (hnext : 1 ≤ next_idx)
    (h : all_wf pm) : all_wf (applyChanges pm changes next_idx) := by
  unfold applyChanges
  induction changes generalizing pm with
  | nil => exact h
  | cons head rest ih =>
    obtain ⟨id, ct⟩ := head
    simp only [List.foldl_cons]
    exact ih (applyChange pm id ct next_idx) (PT4_applyChange_preserves_all_wf pm id ct next_idx hnext h)

-- ---------------------------------------------------------------------------
-- PT6: empty tracker is trivially all_wf
-- ---------------------------------------------------------------------------

/-- PT6: The empty progress map satisfies `all_wf`. -/
theorem PT6_empty_all_wf : all_wf ([] : ProgressMap) := by
  intro id p hmem; simp at hmem

-- ---------------------------------------------------------------------------
-- PT7–PT12: Lifting per-peer wf-preservation theorems to the tracker level
-- ---------------------------------------------------------------------------

/-- PT7: Applying `becomeProbe` to one peer preserves the tracker-level `all_wf`.

    Uses PR18 (`becomeProbe` always produces a wf `Progress`). -/
theorem PT7_becomeProbe_preserves_tracker_wf (pm : ProgressMap) (id : Nat)
    (h : all_wf pm) : all_wf (updatePeer pm id Progress.becomeProbe) :=
  PT3_updatePeer_preserves_all_wf pm id Progress.becomeProbe h
    (fun p _ => PR18_becomeProbe_preserves_wf p)

/-- PT8: Applying `becomeReplicate` to one peer preserves the tracker-level `all_wf`.

    Uses PR19 (`becomeReplicate` always produces a wf `Progress`). -/
theorem PT8_becomeReplicate_preserves_tracker_wf (pm : ProgressMap) (id : Nat)
    (h : all_wf pm) : all_wf (updatePeer pm id Progress.becomeReplicate) :=
  PT3_updatePeer_preserves_all_wf pm id Progress.becomeReplicate h
    (fun p _ => PR19_becomeReplicate_preserves_wf p)

/-- PT9: Applying `becomeSnapshot si` to one peer preserves the tracker-level `all_wf`.

    Uses PR29 (`becomeSnapshot` preserves wf when the input is wf). -/
theorem PT9_becomeSnapshot_preserves_tracker_wf (pm : ProgressMap) (id : Nat) (si : Nat)
    (h : all_wf pm) : all_wf (updatePeer pm id (fun p => p.becomeSnapshot si)) :=
  PT3_updatePeer_preserves_all_wf pm id (fun p => p.becomeSnapshot si) h
    (fun p hp => PR29_becomeSnapshot_preserves_wf p si hp)

/-- PT10: Applying `maybeUpdate n` to one peer preserves the tracker-level `all_wf`.

    Uses PR20 (`maybeUpdate` preserves wf when the input is wf). -/
theorem PT10_maybeUpdate_preserves_tracker_wf (pm : ProgressMap) (id : Nat) (n : Nat)
    (h : all_wf pm) : all_wf (updatePeer pm id (fun p => (p.maybeUpdate n).1)) :=
  PT3_updatePeer_preserves_all_wf pm id (fun p => (p.maybeUpdate n).1) h
    (fun p hp => PR20_maybeUpdate_preserves_wf p n hp)

/-- PT11: Applying `maybeDecrTo` to one peer preserves the tracker-level `all_wf`.

    Uses PR33 (`maybeDecrTo` preserves wf when the input is wf). -/
theorem PT11_maybeDecrTo_preserves_tracker_wf
    (pm : ProgressMap) (id : Nat) (rejected match_hint req_snap : Nat)
    (h : all_wf pm) :
    all_wf (updatePeer pm id (fun p => (p.maybeDecrTo rejected match_hint req_snap).1)) :=
  PT3_updatePeer_preserves_all_wf pm id
    (fun p => (p.maybeDecrTo rejected match_hint req_snap).1) h
    (fun p hp => PR33_maybeDecrTo_preserves_wf p rejected match_hint req_snap hp)

/-- PT12: Applying `optimisticUpdate n` to one peer preserves the tracker-level `all_wf`
    when `p.matched ≤ n` holds for that peer.

    Uses PR35 (`optimisticUpdate` preserves wf when `matched ≤ n`). -/
theorem PT12_optimisticUpdate_preserves_tracker_wf
    (pm : ProgressMap) (id : Nat) (n : Nat)
    (hmn : ∀ p, (id, p) ∈ pm → p.matched ≤ n)
    (h : all_wf pm) :
    all_wf (updatePeer pm id (fun p => p.optimisticUpdate n)) := by
  intro i q hmem
  unfold updatePeer at hmem
  rw [List.mem_map] at hmem
  obtain ⟨⟨j, p⟩, hjp, heq⟩ := hmem
  simp only at heq
  by_cases hji : j = id
  · simp only [hji, ite_true] at heq
    have := Prod.mk.inj heq
    rw [← this.2]
    exact PR35_optimisticUpdate_preserves_wf p n (hmn p (hji ▸ hjp))
  · simp only [hji, ite_false] at heq
    have := Prod.mk.inj heq
    rw [← this.2]
    exact h j p hjp

-- ---------------------------------------------------------------------------
-- PT13: Initialising a fresh tracker from a list of voter IDs
-- ---------------------------------------------------------------------------

/-- Build a fresh progress map from a list of peer IDs.
    Each peer starts with `Progress.mk_new next_idx`.
    Models the initial peer setup when a Raft node is first configured. -/
def initTracker (ids : List Nat) (next_idx : Nat) : ProgressMap :=
  ids.map (fun id => (id, Progress.mk_new next_idx))

/-- PT13: A freshly initialised tracker is wf when `1 ≤ next_idx`. -/
theorem PT13_initTracker_all_wf (ids : List Nat) (next_idx : Nat) (h : 1 ≤ next_idx) :
    all_wf (initTracker ids next_idx) := by
  intro id p hmem
  unfold initTracker at hmem
  rw [List.mem_map] at hmem
  obtain ⟨i, _, heq⟩ := hmem
  have := Prod.mk.inj heq
  rw [← this.2]
  exact PR22_mk_new_wf next_idx h

-- ---------------------------------------------------------------------------
-- PT14: Composition — applyChanges on a fresh tracker is all_wf
-- ---------------------------------------------------------------------------

/-- PT14: Starting from an initialised tracker and applying `apply_conf` changes
    yields a wf tracker (as long as `1 ≤ next_idx`).

    This combines PT5 and PT13 to give an end-to-end result covering the full
    `ProgressTracker::apply_conf` path from cold start. -/
theorem PT14_applyChanges_on_init_all_wf
    (ids : List Nat) (changes : List (Nat × ChangeType))
    (next_idx : Nat) (h : 1 ≤ next_idx) :
    all_wf (applyChanges (initTracker ids next_idx) changes next_idx) :=
  PT5_applyChanges_preserves_all_wf _ changes next_idx h (PT13_initTracker_all_wf ids next_idx h)

-- ---------------------------------------------------------------------------
-- PT15: Tracker wf is monotone under repeated updatePeer with wf-preserving f
-- ---------------------------------------------------------------------------

/-- PT15: Applying `updatePeer` for multiple peers in sequence preserves `all_wf`,
    as long as the update function preserves wf on each peer individually.

    Proof: each step uses PT3; the induction is over the list of (id, f) pairs. -/
theorem PT15_updatePeers_preserves_all_wf
    (pm : ProgressMap)
    (updates : List (Nat × (Progress → Progress)))
    (hfs : ∀ id f, (id, f) ∈ updates → ∀ p, p.wf → (f p).wf)
    (h : all_wf pm) :
    all_wf (updates.foldl (fun acc ⟨id, f⟩ => updatePeer acc id f) pm) := by
  induction updates generalizing pm with
  | nil => simpa
  | cons head rest ih =>
    obtain ⟨id, f⟩ := head
    simp only [List.foldl_cons]
    apply ih
    · intro id' f' hmem
      exact hfs id' f' (List.mem_cons_of_mem _ hmem)
    · apply PT3_updatePeer_preserves_all_wf pm id f h
      exact hfs id f (List.mem_cons_self)

end FVSquad.ProgressTracker
