import FVSquad.ProgressSet

/-!
# Correspondence Tests: `ProgressSet` vs `ProgressTracker::quorum_recently_active`

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

This file validates the `ProgressSet` model (PS1–PS8) against concrete inputs,
verifying that `activeSet`, `resetActive`, and `quorumRecentlyActive` behave as
expected for a range of configurations.

## Test cases

Each `#guard` asserts the expected output of a specific evaluation.

**Coverage**:
- PS1: leader self-inclusion in activeSet (test 1–3)
- PS2: activeSet ⊆ voters (tested implicitly via filter definition)
- PS3: monotonicity (test 7–8)
- PS4: idempotency of resetActive (test 9–10)
- PS5: activeSet after reset = singleton {leader} (test 11–13)
- PS6: quorum → activeSet ≠ [] (test 1–4)
- PS7: all_wf preserved by resetActive (test 14–15)
- PS8: definitional equivalence (all tests)

**Sorry count**: 0.  All tests are `#guard` assertions (compile-time).

> 🔬 Generated by Lean Squad automated formal verification (Run 122).
-/

namespace FVSquad.ProgressSetCorrespondence

open FVSquad.Progress
open FVSquad.ProgressSet

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

/-- Make a fresh Progress entry with `recent_active` set to the given value. -/
private def mkProg (ra : Bool) : Progress :=
  { Progress.mk_new 1 with recent_active := ra }

/-- Make a ProgressSet from a voter list and a list of (id, recent_active) pairs. -/
private def mkPS (voters : List Nat) (raBits : List (Nat × Bool)) : ProgressSet :=
  { voters := voters
    progress := fun id =>
      match raBits.find? (fun p => p.1 == id) with
      | some (_, ra) => mkProg ra
      | none         => mkProg false }

-- ---------------------------------------------------------------------------
-- Test 1: 3-voter cluster, all active → quorum true
-- ---------------------------------------------------------------------------

-- 3 voters, all have recent_active=true; leader=0
#guard quorumRecentlyActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, true)]) 0 = true

-- ---------------------------------------------------------------------------
-- Test 2: 3-voter cluster, only leader active → quorum false (1/3 < majority)
-- ---------------------------------------------------------------------------

-- 3 voters, only leader (0) has recent_active; 1 and 2 are inactive
#guard quorumRecentlyActive (mkPS [0, 1, 2] [(0, false), (1, false), (2, false)]) 0 = false

-- ---------------------------------------------------------------------------
-- Test 3: 3-voter cluster, leader + 1 peer active → quorum true (2/3 ≥ majority 2)
-- ---------------------------------------------------------------------------

-- majority [0,1,2] = 3/2+1 = 2; 2 active → quorum
#guard quorumRecentlyActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, false)]) 0 = true

-- ---------------------------------------------------------------------------
-- Test 4: 5-voter cluster, 3/5 active → quorum true (majority = 3)
-- ---------------------------------------------------------------------------

-- majority 5 = 5/2+1 = 3; 3 active (0, 1, 2) → quorum
#guard quorumRecentlyActive (mkPS [0, 1, 2, 3, 4] [(0, true), (1, true), (2, true), (3, false), (4, false)]) 0 = true

-- ---------------------------------------------------------------------------
-- Test 5: 5-voter cluster, 2/5 active → quorum false (2 < majority 3)
-- ---------------------------------------------------------------------------

-- only leader (0) and peer 1 are active — not enough for 5-voter cluster
#guard quorumRecentlyActive (mkPS [0, 1, 2, 3, 4] [(0, false), (1, true), (2, false), (3, false), (4, false)]) 0 = false

-- ---------------------------------------------------------------------------
-- Test 6: PS1 — leader always in activeSet
-- ---------------------------------------------------------------------------

-- Even if leader (2) has recent_active=false, it still appears in activeSet
#guard (activeSet (mkPS [0, 1, 2] [(0, false), (1, false), (2, false)]) 2).contains 2 = true

-- Leader with recent_active=true also appears
#guard (activeSet (mkPS [1, 2, 3] [(1, false), (2, true), (3, false)]) 2).contains 2 = true

-- ---------------------------------------------------------------------------
-- Test 7: activeSet membership — only active peers included
-- ---------------------------------------------------------------------------

-- Peer 1 with recent_active=false should NOT be in activeSet (perspectiveOf=0)
#guard (activeSet (mkPS [0, 1, 2] [(0, false), (1, false), (2, false)]) 0).contains 1 = false

-- Peer 1 with recent_active=true should be in activeSet
#guard (activeSet (mkPS [0, 1, 2] [(0, false), (1, true), (2, false)]) 0).contains 1 = true

-- ---------------------------------------------------------------------------
-- Test 8: PS3 — more active peers → same or larger quorum
-- ---------------------------------------------------------------------------

-- ps1: only leader active → no quorum; ps2: 2/3 active → quorum
-- If quorum holds for ps1, it holds for ps2 (ps3); here we verify the converse doesn't hold
#guard quorumRecentlyActive (mkPS [0, 1, 2] [(0, false), (1, false), (2, false)]) 0 = false
#guard quorumRecentlyActive (mkPS [0, 1, 2] [(0, false), (1, true), (2, false)]) 0 = true

-- ---------------------------------------------------------------------------
-- Test 9: PS4 — resetActive is idempotent (activeSet after one and two resets equal)
-- ---------------------------------------------------------------------------

-- 3-voter, all active; perspectiveOf=0
-- After reset: only 0 is active
-- After double reset: same
#guard activeSet (resetActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, true)]) 0) 0 =
       activeSet (resetActive (resetActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, true)]) 0) 0) 0

-- Different leader (2)
#guard activeSet (resetActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, true)]) 2) 2 =
       activeSet (resetActive (resetActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, true)]) 2) 2) 2

-- ---------------------------------------------------------------------------
-- Test 10: PS4 — resetActive(resetActive(ps)) = resetActive(ps) for progress fn
-- ---------------------------------------------------------------------------

-- After one reset, the active flag for leader is true; for others false
-- We verify via the activeSet (which reflects recent_active)
#guard activeSet (resetActive (resetActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, true)]) 0) 0) 0 =
       activeSet (resetActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, true)]) 0) 0

-- ---------------------------------------------------------------------------
-- Test 11: PS5 — activeSet after reset = singleton {leader}
-- ---------------------------------------------------------------------------

-- All 3 active; reset with leader=0 → only 0 active
#guard activeSet (resetActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, true)]) 0) 0 = [0]

-- Only peer 1 active; reset with leader=0 → only 0 active
#guard activeSet (resetActive (mkPS [0, 1, 2] [(0, false), (1, true), (2, false)]) 0) 0 = [0]

-- Only leader=2 in voters; reset → still [2]
#guard activeSet (resetActive (mkPS [2] [(2, false)]) 2) 2 = [2]

-- ---------------------------------------------------------------------------
-- Test 12: PS5 — quorum after reset = false (for 3+ voter cluster)
-- ---------------------------------------------------------------------------

-- After reset, only 1/3 voters active → no quorum for 3-voter cluster
#guard quorumRecentlyActive (resetActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, true)]) 0) 0 = false

-- After reset in 2-voter cluster: 1/2 < majority 2 → false
#guard quorumRecentlyActive (resetActive (mkPS [0, 1] [(0, true), (1, true)]) 0) 0 = false

-- ---------------------------------------------------------------------------
-- Test 13: Edge case — single voter cluster
-- ---------------------------------------------------------------------------

-- Single voter (leader): always quorate regardless of recent_active
#guard quorumRecentlyActive (mkPS [0] [(0, false)]) 0 = true
#guard quorumRecentlyActive (mkPS [0] [(0, true)]) 0 = true

-- Single voter after reset: still quorate (singleton = quorum)
#guard quorumRecentlyActive (resetActive (mkPS [0] [(0, true)]) 0) 0 = true

-- ---------------------------------------------------------------------------
-- Test 14: PS7 — resetActive preserves wf (via matched and next_idx fields)
-- ---------------------------------------------------------------------------

-- Fresh progress entries are wf (matched=0, next_idx=1, 0+1 ≤ 1)
-- After reset: recent_active changes but matched/next_idx unchanged
-- (Nat equality is decidable)
#guard ((resetActive (mkPS [0, 1, 2] [(0, true), (1, false), (2, true)]) 0).progress 0).matched == ((mkPS [0, 1, 2] [(0, true), (1, false), (2, true)]).progress 0).matched
#guard ((resetActive (mkPS [0, 1, 2] [(0, true), (1, false), (2, true)]) 0).progress 1).next_idx == ((mkPS [0, 1, 2] [(0, true), (1, false), (2, true)]).progress 1).next_idx
-- leader gets recent_active=true after reset; peer 1 (inactive) gets recent_active=false
#guard ((resetActive (mkPS [0, 1, 2] [(0, false), (1, true), (2, false)]) 0).progress 0).recent_active == true
#guard ((resetActive (mkPS [0, 1, 2] [(0, false), (1, true), (2, false)]) 0).progress 1).recent_active == false

-- ---------------------------------------------------------------------------
-- Test 15: PS8 — quorumRecentlyActive ↔ hasQuorum on activeSet
-- ---------------------------------------------------------------------------

-- Direct check: quorumRecentlyActive agrees with hasQuorum on activeSet membership
#guard quorumRecentlyActive (mkPS [0, 1, 2] [(0, true), (1, true), (2, false)]) 0 =
       hasQuorum [0, 1, 2] (fun id => (activeSet (mkPS [0, 1, 2] [(0, true), (1, true), (2, false)]) 0).contains id)

-- 5-voter case
#guard quorumRecentlyActive (mkPS [0, 1, 2, 3, 4] [(0, false), (1, true), (2, true), (3, false), (4, false)]) 0 =
       hasQuorum [0, 1, 2, 3, 4] (fun id => (activeSet (mkPS [0, 1, 2, 3, 4] [(0, false), (1, true), (2, true), (3, false), (4, false)]) 0).contains id)

end FVSquad.ProgressSetCorrespondence
