import FVSquad.QuorumRecentlyActive

/-!
# QuorumRecentlyActive Correspondence Tests — Lean 4

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

Static correspondence validation for `quorum_recently_active`:
each `#guard` assertion runs the Lean model on a concrete test case and
verifies the result at compile time (`lake build`).

## Strategy (Task 8, Route B)

The test cases below are mirrored both here (Lean model side) and in
`src/tracker.rs::tests::test_quorum_recently_active_correspondence`
(Rust source side).  Both sides must produce the same `expected` Boolean on the
same `(voters, entries, perspectiveOf)` input.

- **Lean side**: `#guard` evaluates `quorumRecentlyActive voters entries perspectiveOf == expected`
  at lake-build time.  A compile error means the Lean model gives a different answer.
- **Rust side**: `assert_eq!` in the test function verifies the same expected values at
  `cargo test` time.

Together they demonstrate that the Lean `quorumRecentlyActive` model agrees with
the Rust `ProgressTracker::quorum_recently_active` on all 14 correspondence cases.

## Lean model recap

```lean
def isActive (entries : List (Nat × Progress)) (perspectiveOf : Nat) (n : Nat) : Bool :=
  entries.any (fun e => e.1 == n && (e.1 == perspectiveOf || e.2.recent_active))

def quorumRecentlyActive (voters : List Nat) (entries : List (Nat × Progress))
    (perspectiveOf : Nat) : Bool :=
  hasQuorum voters (isActive entries perspectiveOf)
```

## Correspondence notes

The Lean model captures the **return value** semantics of `quorum_recently_active`.
The Rust function also mutates `recent_active` flags (side-effects), but those do
not affect the current return value.  The Lean model deliberately abstracts them.

**perspectiveOf must be in `entries`** to be counted as active.  In practice the
leader always has a `Progress` entry in `self.progress`, so this is a minor
abstraction detail that the test cases handle explicitly.

## Test cases (14 total)

| ID | voters | entries (id, recent_active) | perspectiveOf | expected | Rationale |
|----|--------|-----------------------------|---------------|----------|-----------|
| 1  | [] | [] | 1 | true | Empty voters → vacuous quorum |
| 2  | [1] | [(1,F)] | 1 | true | Leader only voter, in entries → active |
| 3  | [1] | [] | 1 | false | Leader not in entries → 0 < majority(1)=1 |
| 4  | [1,2,3] | [(1,F),(2,T),(3,F)] | 1 | true | {1,2} active, 2 ≥ majority(3)=2 |
| 5  | [1,2,3] | [(1,F),(2,F),(3,F)] | 1 | false | Only {1} active, 1 < 2 |
| 6  | [1,2,3] | [(2,T),(3,T)] | 1 | true | perspectiveOf not in entries, {2,3} active, 2 ≥ 2 |
| 7  | [1,2,3] | [(1,T),(2,T),(3,T)] | 1 | true | All 3 active → true |
| 8  | [1,2,3] | [] | 1 | false | No entries → 0 < 2 |
| 9  | [1,2,3,4,5] | [(1,F),(2,T),(3,T),(4,F),(5,F)] | 1 | true | {1,2,3} active, 3 ≥ majority(5)=3 |
| 10 | [1,2,3,4,5] | [(1,F),(2,T),(3,F),(4,F),(5,F)] | 1 | false | {1,2} active, 2 < 3 |
| 11 | [1,2,3,4,5] | [(1,F)] | 1 | false | Only leader active, 1 < 3 |
| 12 | [1,2,3] | [(1,F),(2,F),(3,T)] | 2 | true | {2(leader),3} active, 2 ≥ 2 |
| 13 | [1,2,3] | [(1,T),(2,F),(3,F)] | 2 | true | {1,2(leader)} active, 2 ≥ 2 |
| 14 | [1,2,3] | [(1,F),(2,F),(3,F)] | 2 | false | Only {2(leader)}, 1 < 2 |

🔬 Generated by Lean Squad automated formal verification (Run 92).
-/

namespace FVSquad.QuorumRecentlyActiveCorrespondence

open FVSquad.QuorumRecentlyActive
open FVSquad.Progress

/-! ## Helper: construct a `Progress` value with a given `recent_active` flag -/

/-- Build a minimal `Progress` value for correspondence tests.
    Only `recent_active` varies; all other fields use their default values. -/
private def mkPr (ra : Bool) : Progress :=
  { matched := 0, next_idx := 1, state := .Probe, paused := false,
    pending_snapshot := 0, pending_request_snapshot := 0,
    recent_active := ra, ins_full := false }

/-! ## Case 1: Empty voters → always true (vacuous majority) -/

#guard quorumRecentlyActive [] [] 1 == true

/-! ## Case 2: Single voter = perspectiveOf, has entry → true
    Leader always counts itself when it has a progress entry.
    `isActive [(1,F)] 1 1 = true` (because `1 == perspectiveOf = 1`).
    overlap([1], 1 active) = 1 ≥ majority(1) = 1 → true. -/

#guard quorumRecentlyActive [1] [(1, mkPr false)] 1 == true

/-! ## Case 3: Single voter = perspectiveOf, NOT in entries → false
    `isActive [] 1 1 = false` (no entries).
    overlap([1], 0 active) = 0 < majority(1) = 1 → false. -/

#guard quorumRecentlyActive [1] [] 1 == false

/-! ## Case 4: 3 voters; leader + one recently-active follower → true
    voters = [1,2,3], perspectiveOf = 1.
    Active: {1 (leader), 2 (recent_active=T)}. Inactive: {3}.
    overlap = 2 ≥ majority(3) = 2 → true. -/

#guard quorumRecentlyActive [1, 2, 3]
  [(1, mkPr false), (2, mkPr true), (3, mkPr false)] 1 == true

/-! ## Case 5: 3 voters; only leader active → false
    voters = [1,2,3], perspectiveOf = 1.
    Active: {1}. All others have recent_active = false.
    overlap = 1 < majority(3) = 2 → false. -/

#guard quorumRecentlyActive [1, 2, 3]
  [(1, mkPr false), (2, mkPr false), (3, mkPr false)] 1 == false

/-! ## Case 6: Leader NOT in entries; two followers active → true
    voters = [1,2,3], perspectiveOf = 1 (not in entries).
    Active: {2, 3} (recent_active = true). Leader 1 not counted.
    overlap = 2 ≥ majority(3) = 2 → true.
    Demonstrates that leader-not-in-entries still allows quorum from followers. -/

#guard quorumRecentlyActive [1, 2, 3]
  [(2, mkPr true), (3, mkPr true)] 1 == true

/-! ## Case 7: All three entries have recent_active = true → true -/

#guard quorumRecentlyActive [1, 2, 3]
  [(1, mkPr true), (2, mkPr true), (3, mkPr true)] 1 == true

/-! ## Case 8: No entries at all → false
    No node is active (not even the leader). overlap = 0 < 2 → false. -/

#guard quorumRecentlyActive [1, 2, 3] [] 1 == false

/-! ## Case 9: 5 voters; leader + 2 followers active = majority → true
    Active: {1, 2, 3}. overlap = 3 = majority(5) = 3 → true. -/

#guard quorumRecentlyActive [1, 2, 3, 4, 5]
  [(1, mkPr false), (2, mkPr true), (3, mkPr true),
   (4, mkPr false), (5, mkPr false)] 1 == true

/-! ## Case 10: 5 voters; leader + 1 follower active → false
    Active: {1, 2}. overlap = 2 < majority(5) = 3 → false. -/

#guard quorumRecentlyActive [1, 2, 3, 4, 5]
  [(1, mkPr false), (2, mkPr true), (3, mkPr false),
   (4, mkPr false), (5, mkPr false)] 1 == false

/-! ## Case 11: 5 voters; only leader active → false
    Active: {1}. overlap = 1 < majority(5) = 3 → false. -/

#guard quorumRecentlyActive [1, 2, 3, 4, 5]
  [(1, mkPr false)] 1 == false

/-! ## Case 12: perspectiveOf = 2; follower 3 active → true
    voters = [1,2,3], perspectiveOf = 2.
    Active: {2 (leader), 3 (recent_active=T)}. Inactive: {1}.
    overlap = 2 ≥ majority(3) = 2 → true. -/

#guard quorumRecentlyActive [1, 2, 3]
  [(1, mkPr false), (2, mkPr false), (3, mkPr true)] 2 == true

/-! ## Case 13: perspectiveOf = 2; follower 1 active → true
    voters = [1,2,3], perspectiveOf = 2.
    Active: {1 (recent_active=T), 2 (leader)}. Inactive: {3}.
    overlap = 2 ≥ majority(3) = 2 → true. -/

#guard quorumRecentlyActive [1, 2, 3]
  [(1, mkPr true), (2, mkPr false), (3, mkPr false)] 2 == true

/-! ## Case 14: perspectiveOf = 2; all recent_active = false → false
    voters = [1,2,3], perspectiveOf = 2.
    Active: {2 (leader only)}. overlap = 1 < 2 → false. -/

#guard quorumRecentlyActive [1, 2, 3]
  [(1, mkPr false), (2, mkPr false), (3, mkPr false)] 2 == false

end FVSquad.QuorumRecentlyActiveCorrespondence
