import FVSquad.LogUnstable

/-!
  # RaftLog::append — Lean 4 Specification

  Formalises `RaftLog::append` from `src/raft_log.rs` (line 382).

  ## Algorithm (Rust)

  ```rust
  pub fn append(&mut self, ents: &[Entry]) -> u64 {
      if ents.is_empty() { return self.last_index(); }
      let after = ents[0].index - 1;
      if after < self.committed { fatal!(...) }   // panic — not modelled
      self.unstable.truncate_and_append(ents);
      self.last_index()
  }
  ```

  Note: `raft_log::append` passes `ents` directly to `Unstable::truncate_and_append`,
  which internally reads `after = ents[0].index`.  The `let after = ents[0].index - 1`
  in `raft_log::append` is used **only** for the committed-boundary safety check.

  ## Model

  * `RaftLog.committed : Nat` — highest committed index (never decreases)
  * `RaftLog.stableLastIdx : Nat` — last index in stable storage (read-only here)
  * `RaftLog.unstable : Unstable` — mutable unstable segment (reuses `LogUnstable`)
  * `Entry := Nat × Nat` — (index, term); payload omitted
  * `raftLastIndex` = unstable's last index if non-empty, else stable last index

  ## Approximations / Omissions

  * Entry payloads omitted (only index/term modelled)
  * `u64` → `Nat`; no overflow
  * Logger / tracing side effects elided
  * Stable storage is read-only; only `stableLastIdx` is consulted
  * Panic path (`ents[0].index - 1 < committed`) not modelled; spec covers success path

  Source: `src/raft_log.rs`
  Informal spec: `formal-verification/specs/raft_log_append_informal.md`
  Depends on: `FVSquad/LogUnstable.lean` (for `Unstable`, `truncateAndAppend`, etc.)

  🔬 Generated by Lean Squad automated formal verification.
-/

namespace FVSquad.RaftLogAppend

-- LogUnstable definitions and theorems are at the top level (no namespace in LogUnstable.lean)

-- ═══════════════════════════════════════════════════════════
-- Data structures
-- ═══════════════════════════════════════════════════════════

/-- Abstract model of the Raft log combining stable and unstable segments.
    Corresponds to `struct RaftLog<T>` in `src/raft_log.rs`. -/
structure RaftLog where
  /-- Highest committed log index (monotone, never decreases). -/
  committed     : Nat
  /-- Last index in stable storage — read-only in `append`. -/
  stableLastIdx : Nat
  /-- Unstable (not-yet-persisted) log segment. -/
  unstable      : Unstable
  deriving Repr

/-- A log entry: (log-index, term).  Payload omitted from this model. -/
abbrev Entry := Nat × Nat

-- ═══════════════════════════════════════════════════════════
-- Core functions
-- ═══════════════════════════════════════════════════════════

/-- Overall last log index: unstable segment's last index if non-empty,
    otherwise the stable storage's last index.
    Models `RaftLog::last_index`. -/
def raftLastIndex (rl : RaftLog) : Nat :=
  (maybeLastIndex rl.unstable).getD rl.stableLastIdx

/-- Append a batch of entries to the raft log.
    Preconditions (success path, panic not modelled):
      • `ents` non-empty → `ents[0].1 > rl.committed`   (P4 safety guard)
      • `ents[0].1 ≤ rl.unstable.offset + rl.unstable.entries.length` (no-gap; normal Raft invariant)
    Returns `(updated_log, new_last_index)`.
    Models `RaftLog::append`. -/
def raftLogAppend (rl : RaftLog) (ents : List Entry) : RaftLog × Nat :=
  match ents with
  | []    => (rl, raftLastIndex rl)
  | e :: _ =>
    let after    := e.1                      -- ents[0].index
    let newTerms := ents.map (·.2)           -- extract terms
    let newU     := truncateAndAppend rl.unstable newTerms after
    let newRl    := { rl with unstable := newU }
    (newRl, raftLastIndex newRl)

-- ═══════════════════════════════════════════════════════════
-- Eval examples (sanity-check against raft_log.rs test_append)
-- ═══════════════════════════════════════════════════════════
-- Stable storage has entries [(index=1,term=1),(index=2,term=2)], committed=0.
-- Unstable is empty at offset=3 (= stable.last_index + 1).
private def exLog : RaftLog :=
  { committed := 0, stableLastIdx := 2,
    unstable := { offset := 3, entries := [], snapshot := none } }

-- No entries: returns last_index = 2 (stable)
#eval (raftLogAppend exLog []).2                            -- expected: 2

-- Append [(3,2)]: last_index becomes 3
#eval (raftLogAppend exLog [(3, 2)]).2                      -- expected: 3

-- Overwrite from index 1 with [(1,2)]: last_index becomes 1
-- (unstable now covers index 1 onwards, replacing stable view at that index)
#eval (raftLogAppend exLog [(1, 2)]).2                      -- expected: 1

-- Overwrite from index 2 with [(2,3),(3,3)]: last_index becomes 3
#eval (raftLogAppend exLog [(2, 3), (3, 3)]).2              -- expected: 3

-- ═══════════════════════════════════════════════════════════
-- Helper: truncateAndAppend with non-empty newTerms
-- ═══════════════════════════════════════════════════════════

/-- HTAA1: truncateAndAppend produces non-empty entries when newTerms is non-empty. -/
theorem taa_entries_nonempty (u : Unstable) (newTerms : List Nat) (after : Nat)
    (hne : newTerms ≠ []) :
    (truncateAndAppend u newTerms after).entries ≠ [] := by
  unfold truncateAndAppend
  by_cases h1 : after = u.offset + u.entries.length
  · rw [if_pos h1]
    cases newTerms with
    | nil  => exact absurd rfl hne
    | cons => simp
  · rw [if_neg h1]
    by_cases h2 : after ≤ u.offset
    · rw [if_pos h2]; exact hne
    · rw [if_neg h2]
      cases newTerms with
      | nil  => exact absurd rfl hne
      | cons => simp

/-- HTAA2: maybeLastIndex after truncateAndAppend with non-empty newTerms and no-gap precondition.
    Key lemma: the new last index is `after + newTerms.length - 1`.
    Precondition `hle`: the batch starts at or before the next available slot
    (i.e., no gap is introduced in the log). -/
theorem taa_maybeLastIndex (u : Unstable) (newTerms : List Nat) (after : Nat)
    (hne : newTerms ≠ []) (hle : after ≤ u.offset + u.entries.length) :
    maybeLastIndex (truncateAndAppend u newTerms after) =
    some (after + newTerms.length - 1) := by
  have hlen : 0 < newTerms.length := by
    cases newTerms with | nil => exact absurd rfl hne | cons => simp
  by_cases h1 : after = u.offset + u.entries.length
  · -- Case 1: after = offset + len → append directly
    have hcase : truncateAndAppend u newTerms after =
        { u with entries := u.entries ++ newTerms } := by
      unfold truncateAndAppend; rw [if_pos h1]
    have hne2 : (u.entries ++ newTerms) ≠ [] := by
      cases newTerms with | nil => exact absurd rfl hne | cons => simp
    rw [hcase, maybeLastIndex_entries _ hne2, List.length_append]
    congr 1
    show u.offset + (u.entries.length + newTerms.length) - 1 = after + newTerms.length - 1
    omega
  · by_cases h2 : after ≤ u.offset
    · -- Case 2: after ≤ offset → replace entries and set offset = after
      have hcase : truncateAndAppend u newTerms after =
          { u with offset := after, entries := newTerms } := by
        unfold truncateAndAppend; rw [if_neg h1, if_pos h2]
      rw [hcase, maybeLastIndex_entries _ hne]
    · -- Case 3: offset < after < offset + len → truncate then append
      have hgt : u.offset < after := Nat.lt_of_not_le h2
      have hlt : after < u.offset + u.entries.length := Nat.lt_of_le_of_ne hle h1
      have hd : after - u.offset ≤ u.entries.length := by omega
      have hne3 : u.entries.take (after - u.offset) ++ newTerms ≠ [] := by
        cases newTerms with | nil => exact absurd rfl hne | cons => simp
      have hcase : truncateAndAppend u newTerms after =
          { u with entries := u.entries.take (after - u.offset) ++ newTerms } := by
        unfold truncateAndAppend; rw [if_neg h1, if_neg h2]
      rw [hcase, maybeLastIndex_entries _ hne3, List.length_append, List.length_take,
          Nat.min_eq_left hd]
      congr 1
      show u.offset + (after - u.offset + newTerms.length) - 1 = after + newTerms.length - 1
      omega

-- ═══════════════════════════════════════════════════════════
-- Main theorems
-- ═══════════════════════════════════════════════════════════

/-- RA1: Empty batch is a no-op; returns the unchanged log and current last_index.
    Postcondition P1 from the informal spec. -/
theorem ra1_empty_noop (rl : RaftLog) :
    raftLogAppend rl [] = (rl, raftLastIndex rl) := by
  simp [raftLogAppend]

/-- RA2: The returned index is always the new `raftLastIndex`.
    Postcondition P2 from the informal spec. -/
theorem ra2_return_is_lastIndex (rl : RaftLog) (ents : List Entry) :
    (raftLogAppend rl ents).2 = raftLastIndex (raftLogAppend rl ents).1 := by
  cases ents with
  | nil => simp [raftLogAppend]
  | cons e rest => simp [raftLogAppend]

/-- RA3: Non-empty batch with no-gap precondition: the returned index equals
    `first.index + (first :: rest).length - 1`.
    This is the last entry's index assuming entries are consecutive.
    (Postcondition P3 from the informal spec.)
    `hle` ensures no gap is created (normal Raft no-gap invariant). -/
theorem ra3_return_lastEntry (rl : RaftLog) (first : Entry) (rest : List Entry)
    (hle : first.1 ≤ rl.unstable.offset + rl.unstable.entries.length) :
    (raftLogAppend rl (first :: rest)).2 = first.1 + (first :: rest).length - 1 := by
  simp only [raftLogAppend, List.length_cons, raftLastIndex]
  have hne : (first :: rest).map (·.2) ≠ [] := by simp
  rw [taa_maybeLastIndex rl.unstable ((first :: rest).map (·.2)) first.1 hne (by simpa using hle)]
  simp [List.length_map]

/-- RA4: `committed` is never modified by `raftLogAppend`.
    Invariant I1 (partial) / Postcondition P8 from the informal spec. -/
theorem ra4_committed_unchanged (rl : RaftLog) (ents : List Entry) :
    (raftLogAppend rl ents).1.committed = rl.committed := by
  cases ents with
  | nil  => simp [raftLogAppend]
  | cons => simp [raftLogAppend]

/-- RA5: `stableLastIdx` is never modified by `raftLogAppend`. -/
theorem ra5_stableLastIdx_unchanged (rl : RaftLog) (ents : List Entry) :
    (raftLogAppend rl ents).1.stableLastIdx = rl.stableLastIdx := by
  cases ents with
  | nil  => simp [raftLogAppend]
  | cons => simp [raftLogAppend]

/-- RA6: The pending snapshot is preserved (not affected by appending entries).
    Uses `truncateAndAppend_snapshot_preserved` from LogUnstable. -/
theorem ra6_snapshot_preserved (rl : RaftLog) (ents : List Entry) :
    (raftLogAppend rl ents).1.unstable.snapshot = rl.unstable.snapshot := by
  cases ents with
  | nil  => simp [raftLogAppend]
  | cons e rest =>
    simp only [raftLogAppend]
    exact truncateAndAppend_snapshot_preserved rl.unstable ((e :: rest).map (·.2)) e.1

/-- RA7: Safety guard — if the batch starts strictly after `committed` (the Rust panic guard),
    then `committed` is strictly less than the returned last index.
    Preconditions mirror the Rust: `hguard` (non-overwrite of committed) and `hle` (no gap).
    Proves the structural invariant enforced by `fatal!` in `src/raft_log.rs:393`. -/
theorem ra7_committed_below_return (rl : RaftLog) (first : Entry) (rest : List Entry)
    (hguard : rl.committed < first.1)
    (hle : first.1 ≤ rl.unstable.offset + rl.unstable.entries.length) :
    rl.committed < (raftLogAppend rl (first :: rest)).2 := by
  rw [ra3_return_lastEntry rl first rest hle]
  simp [List.length_cons]
  omega

/-- RA8: When the batch is empty, raftLastIndex is unchanged. -/
theorem ra8_empty_lastIndex_stable (rl : RaftLog) :
    (raftLogAppend rl []).2 = raftLastIndex rl := by
  simp [raftLogAppend]

/-- RA9 (Summary composition): For a non-empty no-gap batch,
    the returned index matches `first.index + batch.length - 1`.
    For consecutive entries this equals the last entry's index.
    This is a named alias for RA3. -/
theorem ra9_return_is_batch_last
    (rl : RaftLog)
    (first : Entry) (rest : List Entry)
    (hle : first.1 ≤ rl.unstable.offset + rl.unstable.entries.length) :
    (raftLogAppend rl (first :: rest)).2 = first.1 + (first :: rest).length - 1 :=
  ra3_return_lastEntry rl first rest hle

-- ═══════════════════════════════════════════════════════════
-- Prefix preservation theorems (P4 / P5 of the informal spec)
-- ═══════════════════════════════════════════════════════════

/-- RA-PFIX1: `truncateAndAppend` preserves `maybeTerm` at every index strictly
    before `after` (the start of the new batch).

    This is the key log-monotonicity property used for P4/P5 of the informal spec:
    entries that predate the batch's start index are not modified.

    Precondition `hle` (no-gap): `after ≤ u.offset + u.entries.length`.
    Without this, a gap could introduce new entries at indices < `after`. -/
theorem taa_maybeTerm_before (u : Unstable) (newTerms : List Nat) (after idx : Nat)
    (hidx : idx < after) (hle : after ≤ u.offset + u.entries.length) :
    maybeTerm (truncateAndAppend u newTerms after) idx = maybeTerm u idx := by
  by_cases h1 : after = u.offset + u.entries.length
  · -- Case 1: after = offset + len → append
    have hE := truncateAndAppend_case1 u newTerms after h1
    have hO := truncateAndAppend_case1_offset u newTerms after h1
    have hS := truncateAndAppend_snapshot_preserved u newTerms after
    simp only [maybeTerm, hO, hS, hE]
    by_cases h2 : idx < u.offset
    · simp [h2]
    · simp only [if_neg h2]
      have hidxu : idx - u.offset < u.entries.length := by omega
      exact List.getElem?_append_left hidxu
  · by_cases h2 : after ≤ u.offset
    · -- Case 2: after ≤ offset → replace
      obtain ⟨hO, hE⟩ := truncateAndAppend_case2 u newTerms after h1 h2
      have hS := truncateAndAppend_snapshot_preserved u newTerms after
      simp only [maybeTerm, hO, hS]
      simp [show idx < after from hidx, show idx < u.offset from by omega]
    · -- Case 3: offset < after (and after < offset + len, from hle + h1)
      have hgt : u.offset < after := Nat.lt_of_not_le h2
      have hE := truncateAndAppend_case3 u newTerms after h1 h2
      have hS := truncateAndAppend_snapshot_preserved u newTerms after
      have hO : (truncateAndAppend u newTerms after).offset = u.offset := by
        unfold truncateAndAppend; rw [if_neg h1, if_neg h2]
      simp only [maybeTerm, hO, hS, hE]
      by_cases h3 : idx < u.offset
      · simp [h3]
      · simp only [if_neg h3]
        have hidxt : idx - u.offset < after - u.offset := by omega
        have htlen : (u.entries.take (after - u.offset)).length = after - u.offset := by
          simp [List.length_take]; omega
        rw [List.getElem?_append_left (by rw [htlen]; exact hidxt)]
        simp [show idx - u.offset < after - u.offset from hidxt]

/-- RA-PFIX2: `raftLogAppend` preserves `maybeTerm` in the unstable segment for every
    index `k` strictly before the batch's start index (`first.1 = after`).

    This captures **postcondition P5** from the informal spec: entries at indices
    `≤ ents[0].index - 1 = after` are not modified by `raftLogAppend`.

    Precondition `hle` (no-gap): `first.1 ≤ rl.unstable.offset + rl.unstable.entries.length`. -/
theorem ra_prefix_preserved (rl : RaftLog) (first : Entry) (rest : List Entry)
    (k : Nat) (hk : k < first.1)
    (hle : first.1 ≤ rl.unstable.offset + rl.unstable.entries.length) :
    maybeTerm (raftLogAppend rl (first :: rest)).1.unstable k = maybeTerm rl.unstable k := by
  simp only [raftLogAppend]
  exact taa_maybeTerm_before rl.unstable ((first :: rest).map (·.2)) first.1 k hk
    (by simpa using hle)

/-- RA-PFIX3: **Postcondition P4** — entries at indices `≤ committed` are not modified.

    This is the invariant that the panic guard in `raftLogAppend` is designed to protect:
    any batch satisfying `committed < first.1` (i.e., `first.1 > committed`) cannot
    touch any committed prefix entry.  Hence committed entries are preserved in the
    unstable segment after `raftLogAppend`. -/
theorem ra_committed_prefix_preserved (rl : RaftLog) (first : Entry) (rest : List Entry)
    (k : Nat) (hk : k ≤ rl.committed)
    (hguard : rl.committed < first.1)
    (hle : first.1 ≤ rl.unstable.offset + rl.unstable.entries.length) :
    maybeTerm (raftLogAppend rl (first :: rest)).1.unstable k = maybeTerm rl.unstable k :=
  ra_prefix_preserved rl first rest k (by omega) hle

-- ═══════════════════════════════════════════════════════════
-- Batch-placement and beyond-batch helpers (P6 / P7)
-- ═══════════════════════════════════════════════════════════

/-- Helper: `truncateAndAppend` offset never exceeds `after`. -/
private theorem taa_offset_le_after (u : Unstable) (newTerms : List Nat) (after : Nat) :
    (truncateAndAppend u newTerms after).offset ≤ after := by
  by_cases h1 : after = u.offset + u.entries.length
  · rw [truncateAndAppend_case1_offset u newTerms after h1]; omega
  · by_cases h2 : after ≤ u.offset
    · obtain ⟨hO, _⟩ := truncateAndAppend_case2 u newTerms after h1 h2; simp [hO]
    · have hO : (truncateAndAppend u newTerms after).offset = u.offset := by
        simp only [truncateAndAppend, if_neg h1, if_neg h2]
      rw [hO]; omega

/-- Helper: the total extent (offset + length) of `truncateAndAppend` equals
    `after + newTerms.length` in all three cases. -/
private theorem taa_total_extent (u : Unstable) (newTerms : List Nat) (after : Nat)
    (hle : after ≤ u.offset + u.entries.length) :
    (truncateAndAppend u newTerms after).offset +
    (truncateAndAppend u newTerms after).entries.length = after + newTerms.length := by
  by_cases h1 : after = u.offset + u.entries.length
  · rw [truncateAndAppend_case1_offset u newTerms after h1,
        truncateAndAppend_case1_length u newTerms after h1]
    omega
  · by_cases h2 : after ≤ u.offset
    · obtain ⟨hO, hE⟩ := truncateAndAppend_case2 u newTerms after h1 h2
      simp [hO, hE]
    · have hO : (truncateAndAppend u newTerms after).offset = u.offset := by
        simp only [truncateAndAppend, if_neg h1, if_neg h2]
      -- truncateAndAppend_case3_length gives: entries.length = (after - u.offset) + newTerms.length
      rw [hO, truncateAndAppend_case3_length u newTerms after h1 h2 (by omega)]
      omega

/-- Helper: `truncateAndAppend` places new terms at the expected positions.
    For `after ≤ k < after + newTerms.length`, the `maybeTerm` equals `newTerms[k - after]?`. -/
private theorem taa_maybeTerm_at_batch (u : Unstable) (newTerms : List Nat) (after : Nat)
    (k : Nat) (hk1 : after ≤ k) (hk2 : k < after + newTerms.length)
    (hle : after ≤ u.offset + u.entries.length) :
    maybeTerm (truncateAndAppend u newTerms after) k = newTerms[k - after]? := by
  by_cases h1 : after = u.offset + u.entries.length
  · have hE := truncateAndAppend_case1 u newTerms after h1
    have hO := truncateAndAppend_case1_offset u newTerms after h1
    simp only [maybeTerm, hO, if_neg (by omega : ¬k < u.offset), hE]
    rw [List.getElem?_append_right (by omega : u.entries.length ≤ k - u.offset)]
    congr 1; omega
  · by_cases h2 : after ≤ u.offset
    · obtain ⟨hO, hE⟩ := truncateAndAppend_case2 u newTerms after h1 h2
      simp only [maybeTerm, hO, if_neg (by omega : ¬k < after), hE]
    · have hO : (truncateAndAppend u newTerms after).offset = u.offset := by
        simp only [truncateAndAppend, if_neg h1, if_neg h2]
      have hE := truncateAndAppend_case3 u newTerms after h1 h2
      simp only [maybeTerm, hO, if_neg (by omega : ¬k < u.offset), hE]
      rw [List.getElem?_append_right
            (by rw [List.length_take, Nat.min_eq_left (by omega)]; omega)]
      congr 1
      rw [List.length_take, Nat.min_eq_left (by omega)]; omega

/-- **P6 (RA-BATCH)** — Postcondition: batch entries are placed at the expected positions.

    After `raftLogAppend rl (first :: rest)`, for index `k` in the batch range
    `[first.1, first.1 + batch.length)`, the unstable term equals the entry's term.

    This closes the "batch suffix matches" postcondition (P6) from the informal spec.

    **Proof**: reduces to `taa_maybeTerm_at_batch` on the inner `truncateAndAppend`.
    🔬 Generated by Lean Squad automated formal verification (Run 50). -/
theorem ra_batch_term (rl : RaftLog) (first : Entry) (rest : List Entry)
    (k : Nat)
    (hk1 : first.1 ≤ k) (hk2 : k < first.1 + (first :: rest).length)
    (hle : first.1 ≤ rl.unstable.offset + rl.unstable.entries.length) :
    maybeTerm (raftLogAppend rl (first :: rest)).1.unstable k =
    ((first :: rest).map (·.2))[k - first.1]? := by
  simp only [raftLogAppend]
  exact taa_maybeTerm_at_batch rl.unstable ((first :: rest).map (·.2)) first.1 k
    hk1 (by simpa [List.length_map] using hk2) (by simpa using hle)

/-- **P7 (RA-BEYOND)** — Postcondition: entries beyond the batch are discarded.

    After `raftLogAppend rl (first :: rest)`, for index `k ≥ first.1 + batch.length`,
    the unstable term is `none` — the truncation removes any prior unstable content there.

    This closes the "beyond-batch discarded" postcondition (P7) from the informal spec.

    **Proof**: `taa_total_extent` gives offset + length = after + terms.length ≤ k,
    then `maybeTerm_entries_miss` (MT5) yields `none`.
    🔬 Generated by Lean Squad automated formal verification (Run 50). -/
theorem ra_beyond_batch_none (rl : RaftLog) (first : Entry) (rest : List Entry)
    (k : Nat) (hk : first.1 + (first :: rest).length ≤ k)
    (hle : first.1 ≤ rl.unstable.offset + rl.unstable.entries.length) :
    maybeTerm (raftLogAppend rl (first :: rest)).1.unstable k = none := by
  simp only [raftLogAppend]
  have hle' : first.1 ≤ rl.unstable.offset + rl.unstable.entries.length := by simpa using hle
  have hext := taa_total_extent rl.unstable ((first :: rest).map (·.2)) first.1
    (by simpa using hle)
  have hoffset := taa_offset_le_after rl.unstable ((first :: rest).map (·.2)) first.1
  simp only [List.length_map] at hext hk
  apply maybeTerm_entries_miss
  · omega
  · omega

end FVSquad.RaftLogAppend
