import FVSquad.ReadOnly

/-!
  # ReadOnly — Correspondence Validation (Task 8 Route B)

  Validates that the Lean 4 `ReadOnly` model in `FVSquad/ReadOnly.lean`
  corresponds to the Rust implementation in `src/read_only.rs`.

  Each `#guard` assertion evaluates the Lean model on a concrete test case at
  `lake build` time.  The matching Rust test `test_read_only_correspondence` in
  `src/read_only.rs` runs the same 14 cases via `cargo test`.

  ## Correspondence level: **exact** (with documented abstractions)

  | Lean model             | Rust implementation              | Level      |
  |------------------------|----------------------------------|------------|
  | `Ctx = Nat`            | `ctx: Vec<u8>` (key)             | abstraction |
  | `ReadIndexStatus.acks` | `ReadIndexStatus.acks: HashSet`  | exact       |
  | `addRequest`           | `ReadOnly::add_request`          | exact       |
  | `recvAck`              | `ReadOnly::recv_ack`             | exact       |
  | `advance`              | `ReadOnly::advance`              | exact       |
  | `lastPendingRequestCtx`| `ReadOnly::last_pending_request_ctx` | exact   |
  | `pendingReadCount`     | `ReadOnly::pending_read_count`   | exact       |

  ## Abstractions and omissions

  * `Ctx = Nat` models `Vec<u8>` keys: each Lean `Nat` k corresponds to Rust `vec![k as u8]`.
  * `ReadIndexStatus.req: Message` elided (only `index` and `acks` tested).
  * Rust `acks: HashSet<u64>` is compared after sorting; Lean `acks: List Nat` is ordered.
  * The `logger` parameter of `advance` is omitted; panic path not modelled.
  * `ReadOnlyOption` (Safe vs LeaseBased) not modelled.

  Source: `src/read_only.rs`
  🔬 Generated by Lean Squad automated formal verification.
-/

open FVSquad.ReadOnly

-- ═══════════════════════════════════════════════════════════
-- Helpers
-- ═══════════════════════════════════════════════════════════

private def ro0 : ReadOnly := ReadOnly.mk [] []

-- ═══════════════════════════════════════════════════════════
-- Case 1: Empty state
-- pending_read_count = 0, last_pending_request_ctx = none
-- ═══════════════════════════════════════════════════════════
#guard pendingReadCount ro0 == 0
#guard lastPendingRequestCtx ro0 == none

-- ═══════════════════════════════════════════════════════════
-- Case 2: Add one request
-- add_request(ctx=1, index=100, selfId=1)
-- → pending_read_count=1, last_ctx=some 1, acks=[1]
-- ═══════════════════════════════════════════════════════════
#guard
  let ro := addRequest ro0 1 100 1
  pendingReadCount ro == 1 &&
  lastPendingRequestCtx ro == some 1 &&
  alookup 1 ro.pending == some { index := 100, acks := [1] }

-- ═══════════════════════════════════════════════════════════
-- Case 3: Duplicate add_request (idempotent)
-- add_request(1,100,1) twice → same state
-- ═══════════════════════════════════════════════════════════
#guard
  let ro1 := addRequest ro0 1 100 1
  let ro2 := addRequest ro1 1 200 2
  pendingReadCount ro2 == 1 &&
  alookup 1 ro2.pending == some { index := 100, acks := [1] }

-- ═══════════════════════════════════════════════════════════
-- Case 4: Add two distinct requests
-- queue = [1, 2], count = 2
-- ═══════════════════════════════════════════════════════════
#guard
  let ro := addRequest (addRequest ro0 1 100 1) 2 101 1
  pendingReadCount ro == 2 &&
  ro.queue == [1, 2] &&
  lastPendingRequestCtx ro == some 2

-- ═══════════════════════════════════════════════════════════
-- Case 5: Add three requests
-- queue = [1, 2, 3], count = 3
-- ═══════════════════════════════════════════════════════════
#guard
  let ro := addRequest (addRequest (addRequest ro0 1 100 1) 2 101 1) 3 102 1
  pendingReadCount ro == 3 &&
  ro.queue == [1, 2, 3] &&
  lastPendingRequestCtx ro == some 3

-- ═══════════════════════════════════════════════════════════
-- Case 6: recv_ack on absent ctx → none
-- ═══════════════════════════════════════════════════════════
#guard (recvAck ro0 7 99).1 == none

-- ═══════════════════════════════════════════════════════════
-- Case 7: recv_ack adds new id to ack set
-- add(1,100,1) → recv_ack(2,1) → acks = [1,2]
-- ═══════════════════════════════════════════════════════════
#guard
  let ro  := addRequest ro0 1 100 1
  let (acks, ro') := recvAck ro 2 1
  acks == some [1, 2] &&
  (alookup 1 ro'.pending).map (·.acks) == some [1, 2]

-- ═══════════════════════════════════════════════════════════
-- Case 8: recv_ack duplicate id is idempotent
-- after acks=[1,2], recv_ack(2,1) again → acks unchanged
-- ═══════════════════════════════════════════════════════════
#guard
  let ro        := addRequest ro0 1 100 1
  let (_, ro1)  := recvAck ro 2 1
  let (acks2, ro2) := recvAck ro1 2 1
  acks2 == some [1, 2] && ro2 == ro1

-- ═══════════════════════════════════════════════════════════
-- Case 9: advance on absent ctx → no-op
-- ═══════════════════════════════════════════════════════════
#guard
  let ro := addRequest ro0 1 100 1
  (advance ro 99).1 == [] && (advance ro 99).2 == ro

-- ═══════════════════════════════════════════════════════════
-- Case 10: advance first of three
-- queue=[1,2,3], advance(1) → queue=[2,3], returns 1 status
-- ═══════════════════════════════════════════════════════════
#guard
  let ro3 := addRequest (addRequest (addRequest ro0 1 100 1) 2 101 1) 3 102 1
  let (ss, ro') := advance ro3 1
  ss.length == 1 &&
  ss[0]!.index == 100 &&
  ro'.queue == [2, 3] &&
  pendingReadCount ro' == 2

-- ═══════════════════════════════════════════════════════════
-- Case 11: advance second of three (middle)
-- queue=[1,2,3], advance(2) → queue=[3], returns 2 statuses
-- ═══════════════════════════════════════════════════════════
#guard
  let ro3 := addRequest (addRequest (addRequest ro0 1 100 1) 2 101 1) 3 102 1
  let (ss, ro') := advance ro3 2
  ss.length == 2 &&
  ss[0]!.index == 100 &&
  ss[1]!.index == 101 &&
  ro'.queue == [3] &&
  pendingReadCount ro' == 1

-- ═══════════════════════════════════════════════════════════
-- Case 12: advance last of three (drains all)
-- queue=[1,2,3], advance(3) → queue=[], count=0
-- ═══════════════════════════════════════════════════════════
#guard
  let ro3 := addRequest (addRequest (addRequest ro0 1 100 1) 2 101 1) 3 102 1
  let (ss, ro') := advance ro3 3
  ss.length == 3 &&
  ss[0]!.index == 100 && ss[1]!.index == 101 && ss[2]!.index == 102 &&
  ro'.queue == [] &&
  pendingReadCount ro' == 0

-- ═══════════════════════════════════════════════════════════
-- Case 13: advance then add new request
-- queue=[1,2], advance(1) → queue=[2]; add(3,103,1) → queue=[2,3]
-- ═══════════════════════════════════════════════════════════
#guard
  let ro2 := addRequest (addRequest ro0 1 100 1) 2 101 1
  let (_, ro') := advance ro2 1
  let ro'' := addRequest ro' 3 103 1
  ro''.queue == [2, 3] && pendingReadCount ro'' == 2

-- ═══════════════════════════════════════════════════════════
-- Case 14: recv_ack then advance returns enriched status
-- add(1,100,1), recv_ack(2,1), advance(1) → status.acks = [1,2]
-- ═══════════════════════════════════════════════════════════
#guard
  let ro       := addRequest ro0 1 100 1
  let (_, ro1) := recvAck ro 2 1
  let (ss, ro') := advance ro1 1
  ss.length == 1 &&
  ss[0]!.acks.contains 1 &&
  ss[0]!.acks.contains 2 &&
  ro'.queue == []
