import FVSquad.Basic

/-!
  # ReadOnly — Lean 4 Specification and Implementation Model

  Formalises `ReadOnly` from `src/read_only.rs`.

  ## What ReadOnly does

  ReadOnly implements the leader-side bookkeeping for the ReadIndex linearisability
  protocol (Raft §6.4).  When a client issues a read-only query the leader:

  1. Records the current commit index and the request context (`add_request`).
  2. Broadcasts a heartbeat and waits for a quorum of acks (`recv_ack`).
  3. Once a quorum has acked, delivers all requests up to that heartbeat (`advance`).

  Because `advance` delivers in FIFO order, every linearisable read is served at or
  after the commit index captured when the request was received.

  ## Model

  * Contexts (`Ctx = Nat`) represent opaque byte keys, modelled as natural numbers.
  * `ReadIndexStatus` pairs the captured commit index with the set of acknowledging node IDs.
  * `ReadOnly` is an association list `pending : List (Ctx × ReadIndexStatus)` (ordered
    by insertion) together with a FIFO queue `queue : List Ctx`.

  The pair `(pending, queue)` maintains the invariant that every ctx in `queue` has
  a corresponding entry in `pending`, and every key in `pending` appears in `queue`.

  ## Approximations / Omissions

  * Byte contexts (`Vec<u8>`) are modelled as `Nat` (keys); payload data elided.
  * The `req : Message` field of `ReadIndexStatus` is elided (only `index` and `acks` kept).
  * The `logger` argument of `advance` (used for a fatal-panic check) is omitted;
    the model assumes the precondition `ctx ∈ queue` is always satisfied.
  * Node IDs are `Nat` (vs `u64`); no overflow.
  * `ReadOnlyOption` (Safe vs LeaseBased) is not modelled — it only affects call sites,
    not the data structure invariants.

  Source: `src/read_only.rs`
  🔬 Generated by Lean Squad automated formal verification.
-/

namespace FVSquad.ReadOnly

-- ═══════════════════════════════════════════════════════════
-- Types
-- ═══════════════════════════════════════════════════════════

/-- Context key (models `Vec<u8>` in Rust, simplified to `Nat`). -/
abbrev Ctx := Nat

/-- Status entry for a single pending read-only request.
    Mirrors `ReadIndexStatus` in `src/read_only.rs`. -/
structure ReadIndexStatus where
  /-- Commit index at the time the request was received. -/
  index : Nat
  /-- Set of node IDs that have acknowledged the attached heartbeat. -/
  acks  : List Nat
  deriving DecidableEq, Repr, Inhabited

/-- ReadOnly bookkeeping state.
    Mirrors `ReadOnly` in `src/read_only.rs`.

    Invariant: `queue` and `pending` contain the same set of keys. -/
structure ReadOnly where
  /-- Association list mapping `Ctx` to its `ReadIndexStatus` (insertion-ordered). -/
  pending : List (Ctx × ReadIndexStatus)
  /-- FIFO queue of ctx keys; determines delivery order in `advance`. -/
  queue   : List Ctx
  deriving DecidableEq, Repr

-- ═══════════════════════════════════════════════════════════
-- Helper functions for association lists
-- ═══════════════════════════════════════════════════════════

/-- Look up a value by key in an association list. -/
def alookup (k : Ctx) (l : List (Ctx × ReadIndexStatus)) : Option ReadIndexStatus :=
  (l.find? (fun p => p.1 == k)).map Prod.snd

/-- Update the value for an existing key in an association list. -/
def aupdate (k : Ctx) (v : ReadIndexStatus) (l : List (Ctx × ReadIndexStatus))
    : List (Ctx × ReadIndexStatus) :=
  l.map (fun p => if p.1 == k then (k, v) else p)

/-- Test whether a key exists in an association list. -/
def amember (k : Ctx) (l : List (Ctx × ReadIndexStatus)) : Bool :=
  l.any (fun p => p.1 == k)

-- ═══════════════════════════════════════════════════════════
-- Implementation model
-- ═══════════════════════════════════════════════════════════

/-- `addRequest ro ctx index selfId`

    Models `ReadOnly::add_request` from `src/read_only.rs:81`.

    If `ctx` is already in `pending`, returns `ro` unchanged (idempotent guard).
    Otherwise appends `ctx` to both `pending` and `queue`, with `selfId` as the
    initial acknowledger. -/
def addRequest (ro : ReadOnly) (ctx : Ctx) (index : Nat) (selfId : Nat) : ReadOnly :=
  if amember ctx ro.pending then ro
  else
    let status : ReadIndexStatus := { index, acks := [selfId] }
    { pending := ro.pending ++ [(ctx, status)]
      queue   := ro.queue ++ [ctx] }

/-- `recvAck ro id ctx`

    Models `ReadOnly::recv_ack` from `src/read_only.rs:96`.

    If `ctx` is in `pending`, inserts `id` into its ack set (set-insert semantics).
    Returns the updated ack set (or `none` if `ctx` not found) and the updated state. -/
def recvAck (ro : ReadOnly) (id : Nat) (ctx : Ctx)
    : Option (List Nat) × ReadOnly :=
  match alookup ctx ro.pending with
  | none => (none, ro)
  | some rs =>
    let newAcks := if rs.acks.contains id then rs.acks else rs.acks ++ [id]
    let newStatus := { rs with acks := newAcks }
    (some newAcks, { ro with pending := aupdate ctx newStatus ro.pending })

/-- `advance ro ctx`

    Models `ReadOnly::advance` from `src/read_only.rs:105`.

    Dequeues all entries up to and including `ctx` from `queue` (FIFO prefix).
    Removes the corresponding entries from `pending`.
    Returns the list of `ReadIndexStatus` values in queue order.

    Precondition: `ctx ∈ ro.queue` (fatal panic in Rust if not; modelled as no-op). -/
def advance (ro : ReadOnly) (ctx : Ctx) : List ReadIndexStatus × ReadOnly :=
  match ro.queue.findIdx? (· == ctx) with
  | none => ([], ro)
  | some i =>
    let toDequeue := ro.queue.take (i + 1)
    let statuses  := toDequeue.filterMap (fun k => alookup k ro.pending)
    let newQueue   := ro.queue.drop (i + 1)
    let newPending := ro.pending.filter (fun p => !toDequeue.contains p.1)
    (statuses, { pending := newPending, queue := newQueue })

/-- `lastPendingRequestCtx ro`

    Models `ReadOnly::last_pending_request_ctx` from `src/read_only.rs:128`. -/
def lastPendingRequestCtx (ro : ReadOnly) : Option Ctx :=
  ro.queue.getLast?

/-- `pendingReadCount ro`

    Models `ReadOnly::pending_read_count` from `src/read_only.rs:133`. -/
def pendingReadCount (ro : ReadOnly) : Nat :=
  ro.queue.length

-- ═══════════════════════════════════════════════════════════
-- Invariant
-- ═══════════════════════════════════════════════════════════

/-- **QueuePendingInv**: every context in `queue` has a corresponding entry in `pending`,
    and every key in `pending` appears in `queue`. -/
def QueuePendingInv (ro : ReadOnly) : Prop :=
  (∀ ctx ∈ ro.queue, amember ctx ro.pending = true) ∧
  (∀ p ∈ ro.pending, p.1 ∈ ro.queue)

-- ═══════════════════════════════════════════════════════════
-- Theorems
-- ═══════════════════════════════════════════════════════════

/-- **RO1** `addRequest` is idempotent when `ctx` is already in `pending`. -/
theorem RO1_addRequest_idempotent
    (ro : ReadOnly) (ctx : Ctx) (index : Nat) (selfId : Nat)
    (h : amember ctx ro.pending = true) :
    addRequest ro ctx index selfId = ro := by
  simp [addRequest, h]

/-- **RO2** When `ctx` is new, `addRequest` appends exactly `[ctx]` to `queue`. -/
theorem RO2_addRequest_extends_queue
    (ro : ReadOnly) (ctx : Ctx) (index : Nat) (selfId : Nat)
    (h : amember ctx ro.pending = false) :
    (addRequest ro ctx index selfId).queue = ro.queue ++ [ctx] := by
  simp [addRequest, h]

/-- **RO3** When `ctx` is new, `addRequest` appends the correct entry to `pending`. -/
theorem RO3_addRequest_extends_pending
    (ro : ReadOnly) (ctx : Ctx) (index : Nat) (selfId : Nat)
    (h : amember ctx ro.pending = false) :
    (addRequest ro ctx index selfId).pending =
      ro.pending ++ [(ctx, { index, acks := [selfId] })] := by
  simp [addRequest, h]

/-- **RO4** After a successful `addRequest`, the new entry can be retrieved with selfId acked.
    Proof: by RO3, pending is `old ++ [(ctx, {index, [selfId]})]`;
    `alookup ctx` finds the appended entry since ctx was absent from old pending. -/
theorem RO4_addRequest_entry_present
    (ro : ReadOnly) (ctx : Ctx) (index : Nat) (selfId : Nat)
    (h : amember ctx ro.pending = false) :
    alookup ctx (addRequest ro ctx index selfId).pending =
      some { index, acks := [selfId] } := by
  rw [RO3_addRequest_extends_pending ro ctx index selfId h]
  simp only [alookup]
  have hno : ro.pending.find? (fun p => p.1 == ctx) = none := by
    rw [List.find?_eq_none]
    intro x hx hbeq
    have := List.any_eq_false.mp h x hx
    simp [hbeq] at this
  simp [List.find?_append, hno]

/-- **RO5** `recvAck` returns `none` iff `ctx` is absent from `pending`. -/
theorem RO5_recvAck_none_iff_absent
    (ro : ReadOnly) (id : Nat) (ctx : Ctx) :
    (recvAck ro id ctx).1 = none ↔ alookup ctx ro.pending = none := by
  simp only [recvAck]
  cases halookup : alookup ctx ro.pending with
  | none => simp
  | some rs => simp

/-- **RO6** `recvAck` adds `id` to the ack set when `ctx` is present and `id` was absent. -/
theorem RO6_recvAck_adds_id
    (ro : ReadOnly) (id : Nat) (ctx : Ctx) (rs : ReadIndexStatus)
    (hpresent : alookup ctx ro.pending = some rs)
    (habsent  : rs.acks.contains id = false) :
    (recvAck ro id ctx).1 = some (rs.acks ++ [id]) ∧
    id ∈ (rs.acks ++ [id]) ∧
    ∀ a ∈ rs.acks, a ∈ (rs.acks ++ [id]) := by
  simp only [recvAck, hpresent, habsent]
  exact ⟨rfl, List.mem_append_right _ (List.mem_singleton.mpr rfl),
         fun a ha => List.mem_append_left _ ha⟩

/-- **RO7** `advance` is a no-op when `ctx` is not in queue. -/
theorem RO7_advance_noop_if_absent
    (ro : ReadOnly) (ctx : Ctx)
    (h : ¬ ctx ∈ ro.queue) :
    advance ro ctx = ([], ro) := by
  simp only [advance]
  have hfind : ro.queue.findIdx? (· == ctx) = none := by
    rw [List.findIdx?_eq_none_iff]
    intro x hx
    simp only [Bool.eq_false_iff, ne_eq]
    intro heq
    exact h ((by simpa using heq : x = ctx) ▸ hx)
  simp [hfind]

private theorem ro8_aux_mem_take
    (l : List Nat) (ctx : Nat) (i : Nat)
    (hi : l.findIdx? (· == ctx) = some i) :
    ctx ∈ l.take (i + 1) := by
  induction l generalizing i with
  | nil => simp at hi
  | cons x xs ih =>
    simp only [List.findIdx?_cons] at hi
    by_cases hcond : (x == ctx) = true
    · rw [if_pos hcond] at hi
      simp only [Option.some.injEq] at hi; subst hi
      simp only [List.take_succ_cons, List.take_zero, List.mem_cons, List.not_mem_nil, or_false]
      exact (beq_iff_eq.mp hcond).symm
    · rw [if_neg hcond] at hi
      cases h_xs : xs.findIdx? (· == ctx) with
      | none => simp [h_xs] at hi
      | some j =>
        simp only [h_xs, Option.map_some, Option.some.injEq] at hi
        subst hi
        rw [List.take_succ_cons]
        exact List.mem_cons.mpr (Or.inr (ih j h_xs))

/-- **RO8** After `advance ctx`, `ctx` is not in the resulting queue.
    Requires the no-duplicates invariant on `ro.queue` (maintained by `addRequest`). -/
theorem RO8_advance_removes_ctx
    (ro : ReadOnly) (ctx : Ctx)
    (h : ctx ∈ ro.queue)
    (hnd : ro.queue.Nodup) :
    ctx ∉ (advance ro ctx).2.queue := by
  obtain ⟨i, hi⟩ : ∃ i, ro.queue.findIdx? (· == ctx) = some i := by
    cases h' : ro.queue.findIdx? (· == ctx) with
    | some i => exact ⟨i, rfl⟩
    | none =>
      rw [List.findIdx?_eq_none_iff] at h'
      exact absurd (h' ctx h) (by simp)
  simp only [advance, hi]
  intro hmem
  have hmem_take := ro8_aux_mem_take ro.queue ctx i hi
  rw [← List.take_append_drop (i + 1) ro.queue] at hnd
  rw [List.nodup_append] at hnd
  exact absurd rfl (hnd.2.2 ctx hmem_take ctx hmem)

/-- **RO9** Empty `ReadOnly` satisfies `QueuePendingInv`. -/
theorem RO9_inv_empty : QueuePendingInv { pending := [], queue := [] } := by
  simp [QueuePendingInv, amember]

/-- **RO10** `addRequest` preserves `QueuePendingInv`. -/
theorem RO10_inv_add
    (ro : ReadOnly) (ctx : Ctx) (index : Nat) (selfId : Nat)
    (hinv : QueuePendingInv ro) :
    QueuePendingInv (addRequest ro ctx index selfId) := by
  unfold addRequest
  split
  · exact hinv
  · rename_i hnew
    simp only [Bool.not_eq_true] at hnew
    refine ⟨?_, ?_⟩
    · intro c hc
      simp only [List.mem_append, List.mem_singleton] at hc
      rcases hc with hq | rfl
      · simp only [amember, List.any_append, Bool.or_eq_true]
        exact Or.inl (hinv.1 c hq)
      · simp [amember, List.any_append, List.any_cons]
    · intro p hp
      simp only [List.mem_append, List.mem_singleton] at hp
      simp only [List.mem_append, List.mem_singleton]
      rcases hp with hpo | rfl
      · exact Or.inl (hinv.2 p hpo)
      · exact Or.inr rfl

/-- **RO11** Successful `addRequest` increments `pendingReadCount` by 1. -/
theorem RO11_addRequest_count
    (ro : ReadOnly) (ctx : Ctx) (index : Nat) (selfId : Nat)
    (h : amember ctx ro.pending = false) :
    pendingReadCount (addRequest ro ctx index selfId) = pendingReadCount ro + 1 := by
  simp [pendingReadCount, addRequest, h, List.length_append]

/-- **RO12** `pendingReadCount` is zero iff queue is empty. -/
theorem RO12_pendingReadCount_zero_iff
    (ro : ReadOnly) :
    pendingReadCount ro = 0 ↔ ro.queue = [] := by
  simp [pendingReadCount]

/-- **RO13** `addRequest` preserves `Nodup` on the queue.
    Combined with `RO8`, this ensures the NoDuplicates invariant holds inductively. -/
theorem RO13_addRequest_preserves_nodup
    (ro : ReadOnly) (ctx : Ctx) (index : Nat) (selfId : Nat)
    (hinv : QueuePendingInv ro)
    (hnd : ro.queue.Nodup)
    (hfresh : amember ctx ro.pending = false) :
    (addRequest ro ctx index selfId).queue.Nodup := by
  rw [RO2_addRequest_extends_queue _ _ _ _ hfresh, List.nodup_append]
  refine ⟨hnd, by simp, fun a ha c hc => ?_⟩
  simp only [List.mem_singleton] at hc
  rw [hc]
  intro heq
  exact absurd (hinv.1 ctx (heq ▸ ha)) (by simp [hfresh])

-- ═══════════════════════════════════════════════════════════
-- #guard correspondence tests
-- ═══════════════════════════════════════════════════════════

section GuardTests

private def ro0 : ReadOnly := ReadOnly.mk [] []

-- RO1: addRequest is idempotent when ctx already present
#guard
  let ro := addRequest ro0 42 100 1
  addRequest ro 42 200 2 == ro

-- RO2: addRequest extends queue on new ctx
#guard (addRequest ro0 42 100 1).queue == [42]

-- Multiple adds produce expected queue order
#guard
  (addRequest (addRequest (addRequest ro0 1 100 1) 2 101 1) 3 102 1).queue == [1, 2, 3]

-- RO3: addRequest appends correct status
#guard alookup 5 (addRequest ro0 5 77 42).pending == some { index := 77, acks := [42] }

-- selfId in acks after add
#guard
  match alookup 10 (addRequest ro0 10 50 99).pending with
  | some s => s.acks.contains 99
  | none => false

-- recvAck on absent ctx returns none
#guard (recvAck ro0 7 99).1 == none

-- recvAck on present ctx adds id
#guard
  let ro := addRequest ro0 10 50 1
  let (acks, ro') := recvAck ro 2 10
  acks == some [1, 2] && (alookup 10 ro'.pending).map (·.acks) == some [1, 2]

-- recvAck is idempotent on duplicate id
#guard
  let ro := addRequest ro0 10 50 1
  let (_, ro1) := recvAck ro 2 10
  let (acks2, ro2) := recvAck ro1 2 10
  acks2 == some [1, 2] && ro2 == ro1

-- advance on absent ctx is no-op
#guard
  let ro := addRequest ro0 5 100 1
  advance ro 99 == ([], ro)

-- advance removes prefix and returns statuses in queue order
#guard
  let ro2 := addRequest (addRequest (addRequest ro0 5 100 1) 10 101 1) 15 102 1
  let (ss, ro') := advance ro2 10
  ss.length == 2 && ss[0]!.index == 100 && ss[1]!.index == 101 &&
  ro'.queue == [15] && ro'.pending.length == 1

-- advance on last ctx clears state completely
#guard
  let (ss, ro') := advance (addRequest (addRequest ro0 1 10 1) 2 20 1) 2
  ss.length == 2 && ro'.queue == [] && ro'.pending == []

-- advance on first ctx only removes one entry
#guard
  let (ss, ro') := advance (addRequest (addRequest ro0 1 10 1) 2 20 1) 1
  ss.length == 1 && ro'.queue == [2] && ro'.pending.length == 1

-- pendingReadCount
#guard pendingReadCount (addRequest (addRequest ro0 1 10 1) 2 20 1) == 2

-- lastPendingRequestCtx
#guard lastPendingRequestCtx (addRequest (addRequest ro0 1 10 1) 5 20 1) == some 5

-- lastPendingRequestCtx on empty
#guard lastPendingRequestCtx ro0 == none

-- advance then add: queue maintained correctly
#guard
  let ro3 := (advance (addRequest (addRequest ro0 1 10 1) 2 20 1) 1).2
  (addRequest ro3 3 30 1).queue == [2, 3]

end GuardTests

end FVSquad.ReadOnly
