/-!
# Restore — Model and Proofs for `RaftLog::restore`

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

This file formalises `RaftLog::restore` (`src/raft_log.rs:696`) — the snapshot restoration
operation that fast-forwards a Raft log to a snapshot state.

## Background

When a follower is far behind, the leader sends a snapshot instead of individual log entries.
`restore` applies this snapshot:
1. Clamps `persisted` to `committed` if `persisted > committed` (prevents dangling persisted index)
2. Advances `committed` to the snapshot index
3. Delegates to `Unstable::restore` (clears entries, sets offset, stores snapshot)

## Key Properties

- **RST1** (`restore_committed`): committed equals snapshot index after restore
- **RST2** (`restore_persisted_le_committed`): `persisted ≤ committed` after restore
- **RST3** (`restore_committed_advances`): committed does not decrease
- **RST4** (`restore_persisted_clamp`): persisted is clamped correctly
- **RST5** (`restore_unstable_offset`): unstable offset = snapshot index + 1
- **RST6** (`restore_unstable_entries_cleared`): unstable entries are empty after restore
- **RST7** (`restore_invariant_ordering`): full ordering invariant `applied ≤ persisted ≤ committed`
- **RST8** (`restore_idempotent_committed`): restoring at current committed is a no-op for committed

## Approximations

- The model captures the pure state-transition logic. I/O, logging, and the `Snapshot`
  protobuf type are not modelled — only the metadata index is used.
- The `assert!` in the Rust code (panics if index < committed) is modelled as a precondition.
- `applied` is not modified by `restore`; the model requires `applied ≤ committed` as a
  precondition.

## Theorem Index

| ID   | Name                              | Status    | Description                                         |
|------|-----------------------------------|-----------|-----------------------------------------------------|
| RST1 | `restore_committed`              | ✅ proved | committed = snapshot index                           |
| RST2 | `restore_persisted_le_committed` | ✅ proved | persisted ≤ committed after restore                  |
| RST3 | `restore_committed_advances`     | ✅ proved | committed does not decrease                          |
| RST4 | `restore_persisted_clamp`        | ✅ proved | persisted clamped to min(old_persisted, old_committed)|
| RST5 | `restore_unstable_offset`        | ✅ proved | unstable offset = snapshot_index + 1                 |
| RST6 | `restore_unstable_entries_cleared`| ✅ proved | unstable entries empty after restore                 |
| RST7 | `restore_invariant_ordering`     | ✅ proved | applied ≤ persisted ≤ committed                      |
| RST8 | `restore_idempotent_committed`   | ✅ proved | restore at current committed is no-op for committed  |

🔬 Generated by Lean Squad automated formal verification.
-/

namespace FVSquad.Restore

/-! ## State Model -/

/-- Simplified model of the unstable log segment.
    Only captures offset and entry count (entries are cleared on restore). -/
structure UnstableState where
  offset : Nat
  entryCount : Nat
  hasSnapshot : Bool
  deriving Repr, DecidableEq

/-- Simplified model of the RaftLog state relevant to `restore`. -/
structure RaftLogState where
  committed : Nat
  persisted : Nat
  applied : Nat
  unstable : UnstableState
  deriving Repr, DecidableEq

/-- The well-formedness invariant for a RaftLog: `applied ≤ persisted ≤ committed`. -/
def RaftLogState.wellFormed (s : RaftLogState) : Prop :=
  s.applied ≤ s.persisted ∧ s.persisted ≤ s.committed

/-! ## Restore Operation -/

/-- Model of `Unstable::restore`: clears entries, sets offset to index+1, stores snapshot. -/
def unstableRestore (snapshotIndex : Nat) : UnstableState :=
  { offset := snapshotIndex + 1, entryCount := 0, hasSnapshot := true }

/-- Model of `RaftLog::restore(snapshot)`.

    Precondition: `snapshotIndex ≥ s.committed` (the Rust code asserts this).

    Steps:
    1. If `persisted > committed`, clamp persisted to committed
    2. Set committed to snapshotIndex
    3. Call unstableRestore on the unstable segment -/
def restore (s : RaftLogState) (snapshotIndex : Nat) : RaftLogState :=
  let persisted' := if s.persisted > s.committed then s.committed else s.persisted
  { committed := snapshotIndex,
    persisted := persisted',
    applied := s.applied,
    unstable := unstableRestore snapshotIndex }

/-! ## Theorems -/

/-- **RST1**: After restore, committed equals the snapshot index. -/
theorem restore_committed (s : RaftLogState) (idx : Nat) :
    (restore s idx).committed = idx := by
  simp [restore]

/-- **RST2**: After restore, `persisted ≤ committed`. -/
theorem restore_persisted_le_committed (s : RaftLogState) (idx : Nat)
    (hpre : idx ≥ s.committed) :
    (restore s idx).persisted ≤ (restore s idx).committed := by
  simp [restore]
  split <;> omega

/-- **RST3**: Restore does not decrease committed. -/
theorem restore_committed_advances (s : RaftLogState) (idx : Nat)
    (hpre : idx ≥ s.committed) :
    (restore s idx).committed ≥ s.committed := by
  simp [restore]; omega

/-- **RST4**: Persisted is clamped to `min(old_persisted, old_committed)`. -/
theorem restore_persisted_clamp (s : RaftLogState) (idx : Nat) :
    (restore s idx).persisted = min s.persisted s.committed := by
  simp [restore]
  split <;> omega

/-- **RST5**: After restore, unstable offset = snapshot_index + 1. -/
theorem restore_unstable_offset (s : RaftLogState) (idx : Nat) :
    (restore s idx).unstable.offset = idx + 1 := by
  simp [restore, unstableRestore]

/-- **RST6**: After restore, unstable entries are cleared (count = 0). -/
theorem restore_unstable_entries_cleared (s : RaftLogState) (idx : Nat) :
    (restore s idx).unstable.entryCount = 0 := by
  simp [restore, unstableRestore]

/-- **RST7**: If the log was well-formed and `applied ≤ committed` before,
    the ordering invariant `applied ≤ persisted ≤ committed` holds after restore. -/
theorem restore_invariant_ordering (s : RaftLogState) (idx : Nat)
    (hwf : s.wellFormed) (hpre : idx ≥ s.committed) :
    (restore s idx).wellFormed := by
  obtain ⟨hap, hpc⟩ := hwf
  simp [RaftLogState.wellFormed, restore]
  constructor
  · split <;> omega
  · split <;> omega

/-- **RST8**: Restoring at the current committed index does not change committed. -/
theorem restore_idempotent_committed (s : RaftLogState) :
    (restore s s.committed).committed = s.committed := by
  simp [restore]

end FVSquad.Restore
