import FVSquad.LogUnstable
import FVSquad.MaybePersistFUI

/-!
# UnstablePersistBridge — Integration: `Unstable.wf` ↔ `MaybePersistFUI` safety

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

Bridges `LogUnstable.lean` and `MaybePersistFUI.lean` to close the remaining
gap identified in `CRITIQUE.md` (Run 76):

> **Known gap**: The Lean model abstracts `firstUpdateIndex` as a bare `Nat`
> parameter.  In the Rust implementation, `firstUpdateIndex` is derived from
> `unstable.snapshot?.index` or `unstable.offset`.  If the derivation has bugs
> (returning a value that is too large), MP6 would not catch them.

This file proves that the `Unstable.wf` invariant (`snapshot.index < offset`,
maintained by all `Unstable` operations) is exactly what guarantees the abstract
`MP6` safety property in the concrete model: **persisted can never be advanced
to `offset` or beyond** when `wf` holds.

## Rust source connection

```rust
// src/raft_log.rs, lines 545–565
let first_update_index = match &self.unstable.snapshot {
    Some(s) => s.get_metadata().index,
    None     => self.unstable.offset,
};
if index > self.persisted
    && index < first_update_index
    && self.log_term(index) == term
{
    self.persisted = index;
    return (self.persisted, true);
}
(self.persisted, false)
```

## Lean model chain

```
Unstable.wf (invariant from LogUnstable.lean)
    → unstableFUI u ≤ u.offset                  (UPB3)
    → maybePersistFromUnstable advances → newPersisted < u.offset  (UPB8)
```

## Theorem table

| ID   | Name                                    | Description                                                                  |
|------|-----------------------------------------|------------------------------------------------------------------------------|
| UPB1 | `UPB1_unstableFUI_snap`                 | Snapshot present → `unstableFUI = snap.index`                                |
| UPB2 | `UPB2_unstableFUI_no_snap`              | No snapshot → `unstableFUI = offset`                                         |
| UPB3 | `UPB3_wf_fui_le_offset`                 | `wf u → unstableFUI u ≤ u.offset`                                            |
| UPB4 | `UPB4_wf_snap_fui_lt_offset`            | `wf u → snapshot present → unstableFUI u < u.offset`                        |
| UPB5 | `UPB5_maybePersist_unstable_monotone`   | Persisted never decreases under `maybePersistFromUnstable`                   |
| UPB6 | `UPB6_wf_snap_blocks_above_snap_idx`    | `wf u → snapshot at `sidx` → index ≥ sidx → returns false`                  |
| UPB7 | `UPB7_no_snap_uses_offset`              | No snapshot → advance iff `index < offset ∧ ...`                            |
| UPB8 | `UPB8_wf_advances_below_offset`         | **Key**: `wf u → advance → newPersisted < u.offset` (closes CRITIQUE gap)   |

**Sorry count**: 0.  All theorems proved without `sorry`.

🔬 Generated by Lean Squad automated formal verification (Run 92).
-/

namespace FVSquad.UnstablePersistBridge

open FVSquad.MaybePersistFUI
open FVSquad.MaybePersist

-- ---------------------------------------------------------------------------
-- Core definition
-- ---------------------------------------------------------------------------

/-- Direct wrapper: `maybePersistFromUnstable` applies `maybePersistFui` using
    the two fields of `Unstable` that determine `firstUpdateIndex`. -/
def maybePersistFromUnstable (u : Unstable) (persisted : Nat)
    (logTerm : Nat → Nat) (index term : Nat) : Nat × Bool :=
  maybePersistFui persisted (u.snapshot.map (·.1)) u.offset logTerm index term

-- ---------------------------------------------------------------------------
-- UPB1: FUI in the snapshot-present case
-- ---------------------------------------------------------------------------

/-- **UPB1** When `u.snapshot = some (sidx, _)`, the derived FUI equals `sidx`.

    Direct consequence of `fui_snap_case` and `Option.map`. -/
theorem UPB1_unstableFUI_snap (u : Unstable) (sidx sterm : Nat)
    (h : u.snapshot = some (sidx, sterm)) :
    firstUpdateIndex (u.snapshot.map (·.1)) u.offset = sidx := by
  simp [h, fui_snap_case]

-- ---------------------------------------------------------------------------
-- UPB2: FUI in the no-snapshot case
-- ---------------------------------------------------------------------------

/-- **UPB2** When `u.snapshot = none`, the derived FUI equals `u.offset`.

    Direct consequence of `fui_no_snap_case` and `Option.map`. -/
theorem UPB2_unstableFUI_no_snap (u : Unstable) (h : u.snapshot = none) :
    firstUpdateIndex (u.snapshot.map (·.1)) u.offset = u.offset := by
  simp [h, fui_no_snap_case]

-- ---------------------------------------------------------------------------
-- UPB3: wf implies FUI ≤ offset
-- ---------------------------------------------------------------------------

/-- **UPB3** The `Unstable.wf` invariant guarantees `FUI ≤ u.offset` in all cases.

    - No snapshot: FUI = offset, so FUI ≤ offset trivially.
    - Snapshot at `sidx` with `wf`: `sidx < offset`, so FUI = sidx < offset ≤ offset.

    This is the key consequence of `wf` for the async-persist safety argument. -/
theorem UPB3_wf_fui_le_offset (u : Unstable) (hwf : wf u) :
    firstUpdateIndex (u.snapshot.map (·.1)) u.offset ≤ u.offset := by
  cases h : u.snapshot with
  | none =>
    simp [fui_no_snap_case]
  | some p =>
    obtain ⟨sidx, _⟩ := p
    simp only [h, wf] at hwf
    -- hwf : sidx < u.offset
    have hfui_lt : firstUpdateIndex (some sidx) u.offset < u.offset :=
      fui_snap_lt_offset sidx u.offset hwf
    simp only [Option.map]
    exact Nat.le_of_lt hfui_lt

-- ---------------------------------------------------------------------------
-- UPB4: wf + snapshot implies FUI < offset (strict)
-- ---------------------------------------------------------------------------

/-- **UPB4** When a snapshot is present and `wf` holds, FUI is **strictly**
    below `u.offset`.

    This strictly separates the "stable" and "unstable" index ranges. -/
theorem UPB4_wf_snap_fui_lt_offset (u : Unstable) (sidx sterm : Nat)
    (hsnap : u.snapshot = some (sidx, sterm)) (hwf : wf u) :
    firstUpdateIndex (u.snapshot.map (·.1)) u.offset < u.offset := by
  simp only [hsnap, wf] at hwf
  simp only [hsnap, Option.map]
  exact fui_snap_lt_offset sidx u.offset hwf

-- ---------------------------------------------------------------------------
-- UPB5: monotonicity
-- ---------------------------------------------------------------------------

/-- **UPB5** Persisted never decreases under `maybePersistFromUnstable`. -/
theorem UPB5_maybePersist_unstable_monotone (u : Unstable) (persisted : Nat)
    (logTerm : Nat → Nat) (index term : Nat) :
    persisted ≤ (maybePersistFromUnstable u persisted logTerm index term).1 := by
  exact maybePersistFui_monotone persisted (u.snapshot.map (·.1)) u.offset logTerm index term

-- ---------------------------------------------------------------------------
-- UPB6: wf + snapshot + index ≥ sidx → returns false
-- ---------------------------------------------------------------------------

/-- **UPB6** When `wf u` holds and there is a pending snapshot at `sidx`,
    any `index ≥ sidx` causes `maybePersistFromUnstable` to return `false`.

    This ensures the snapshot's index acts as an upper bound: entries at or
    above the snapshot cannot be persisted while the snapshot is still pending. -/
theorem UPB6_wf_snap_blocks_above_snap_idx (u : Unstable) (sidx sterm : Nat)
    (persisted : Nat) (logTerm : Nat → Nat) (index term : Nat)
    (hsnap : u.snapshot = some (sidx, sterm))
    (hge : index ≥ sidx) :
    (maybePersistFromUnstable u persisted logTerm index term).2 = false := by
  simp only [maybePersistFromUnstable, hsnap, Option.map]
  exact maybePersistFui_snap_blocks_advance_at persisted sidx u.offset logTerm index term hge

-- ---------------------------------------------------------------------------
-- UPB7: no-snapshot case uses offset as upper bound
-- ---------------------------------------------------------------------------

/-- **UPB7** When `u.snapshot = none`, `maybePersistFromUnstable` returns `true`
    iff `index > persisted`, `index < u.offset`, and `logTerm index = term`.

    Without a snapshot, `offset` (the start of the unstable entry window) is
    the exclusive upper bound for the persisted pointer. -/
theorem UPB7_no_snap_uses_offset (u : Unstable) (persisted : Nat)
    (logTerm : Nat → Nat) (index term : Nat)
    (hsnap : u.snapshot = none) :
    (maybePersistFromUnstable u persisted logTerm index term).2 = true ↔
    index > persisted ∧ index < u.offset ∧ logTerm index = term := by
  simp only [maybePersistFromUnstable, hsnap, Option.map]
  exact maybePersistFui_no_snap_uses_offset persisted u.offset logTerm index term

-- ---------------------------------------------------------------------------
-- UPB8: the key gap-closing theorem
-- ---------------------------------------------------------------------------

/-- **UPB8** — **`wf` closes the MP6 gap**: If `wf u` holds and
    `maybePersistFromUnstable` returns `true` (i.e., persisted actually advances),
    then the new `persisted` value is **strictly below `u.offset`**.

    This closes the gap identified in CRITIQUE.md Run 76:
    > The Lean model abstracts `firstUpdateIndex` as a bare `Nat` parameter.
    > If the derivation has bugs (returning a value that is too large), MP6
    > would not catch them.

    With `wf u` as a hypothesis, the derivation is correct: `unstableFUI ≤ u.offset`
    (UPB3), so any successful advance lands strictly below `u.offset`, which is exactly
    the property needed to prevent spurious advancement into the unstable region.

    **Proof chain**:
    1. From `maybePersistFui_true_iff`: `index < FUI` (where FUI = `unstableFUI u`).
    2. From UPB3 (`wf u`): `FUI ≤ u.offset`.
    3. Therefore `index < u.offset`.
    4. From `maybePersist_true_advances`: `newPersisted = index`.
    5. Therefore `newPersisted < u.offset`. -/
theorem UPB8_wf_advances_below_offset (u : Unstable) (persisted : Nat)
    (logTerm : Nat → Nat) (index term : Nat)
    (hwf : wf u)
    (hadv : (maybePersistFromUnstable u persisted logTerm index term).2 = true) :
    (maybePersistFromUnstable u persisted logTerm index term).1 < u.offset := by
  -- Step 1: new persisted = index (from advance case)
  have hval : (maybePersistFromUnstable u persisted logTerm index term).1 = index := by
    simp only [maybePersistFromUnstable, maybePersistFui] at hadv ⊢
    exact maybePersist_true_advances persisted (firstUpdateIndex (u.snapshot.map (·.1)) u.offset)
      logTerm index term hadv
  -- Step 2: index < FUI (from advance condition)
  have hlt_fui : index < firstUpdateIndex (u.snapshot.map (·.1)) u.offset := by
    simp only [maybePersistFromUnstable] at hadv
    exact (maybePersistFui_true_iff persisted (u.snapshot.map (·.1)) u.offset logTerm index term).mp hadv |>.2.1
  -- Step 3: FUI ≤ offset (from wf)
  have hfui_le : firstUpdateIndex (u.snapshot.map (·.1)) u.offset ≤ u.offset :=
    UPB3_wf_fui_le_offset u hwf
  -- Combine: newPersisted = index < FUI ≤ offset
  rw [hval]
  omega

end FVSquad.UnstablePersistBridge
