name = "FVSquad"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["FVSquad"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false

[[lean_lib]]
name = "FVSquad"
